// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"sync"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/2comjie/taoxi-server/app/Api/payment/internal/store/ent/paymentorder"
	"github.com/2comjie/taoxi-server/app/Api/payment/internal/store/ent/predicate"
	paymentTypes "github.com/2comjie/taoxi-server/app/Api/payment/types"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypePaymentOrder = "PaymentOrder"
)

// PaymentOrderMutation represents an operation that mutates the PaymentOrder nodes in the graph.
type PaymentOrderMutation struct {
	config
	op                     Op
	typ                    string
	id                     *uint64
	uid                    *uint64
	adduid                 *int64
	product_id             *int32
	addproduct_id          *int32
	third_party_product_id *string
	payment_type           *int32
	addpayment_type        *int32
	status                 *paymentTypes.OrderStatus
	addstatus              *paymentTypes.OrderStatus
	order_amount_unit      *int64
	addorder_amount_unit   *int64
	order_amount_nanos     *int32
	addorder_amount_nanos  *int32
	order_currency         *string
	real_amount_unit       *int64
	addreal_amount_unit    *int64
	real_amount_nanos      *int32
	addreal_amount_nanos   *int32
	real_currency          *string
	third_party_order_id   *string
	credential             *string
	credential_hash        *string
	rewards                *json.RawMessage
	appendrewards          json.RawMessage
	retry_times            *int32
	addretry_times         *int32
	cancel_reason          *string
	refund_reason          *string
	is_sandbox             *bool
	create_at_unix         *int64
	addcreate_at_unix      *int64
	update_at_unix         *int64
	addupdate_at_unix      *int64
	pay_at_unix            *int64
	addpay_at_unix         *int64
	refund_at_unix         *int64
	addrefund_at_unix      *int64
	cancel_at_unix         *int64
	addcancel_at_unix      *int64
	clearedFields          map[string]struct{}
	done                   bool
	oldValue               func(context.Context) (*PaymentOrder, error)
	predicates             []predicate.PaymentOrder
}

var _ ent.Mutation = (*PaymentOrderMutation)(nil)

// paymentorderOption allows management of the mutation configuration using functional options.
type paymentorderOption func(*PaymentOrderMutation)

// newPaymentOrderMutation creates new mutation for the PaymentOrder entity.
func newPaymentOrderMutation(c config, op Op, opts ...paymentorderOption) *PaymentOrderMutation {
	m := &PaymentOrderMutation{
		config:        c,
		op:            op,
		typ:           TypePaymentOrder,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withPaymentOrderID sets the ID field of the mutation.
func withPaymentOrderID(id uint64) paymentorderOption {
	return func(m *PaymentOrderMutation) {
		var (
			err   error
			once  sync.Once
			value *PaymentOrder
		)
		m.oldValue = func(ctx context.Context) (*PaymentOrder, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().PaymentOrder.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withPaymentOrder sets the old PaymentOrder of the mutation.
func withPaymentOrder(node *PaymentOrder) paymentorderOption {
	return func(m *PaymentOrderMutation) {
		m.oldValue = func(context.Context) (*PaymentOrder, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m PaymentOrderMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m PaymentOrderMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of PaymentOrder entities.
func (m *PaymentOrderMutation) SetID(id uint64) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *PaymentOrderMutation) ID() (id uint64, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *PaymentOrderMutation) IDs(ctx context.Context) ([]uint64, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uint64{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().PaymentOrder.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetUID sets the "uid" field.
func (m *PaymentOrderMutation) SetUID(u uint64) {
	m.uid = &u
	m.adduid = nil
}

// UID returns the value of the "uid" field in the mutation.
func (m *PaymentOrderMutation) UID() (r uint64, exists bool) {
	v := m.uid
	if v == nil {
		return
	}
	return *v, true
}

// OldUID returns the old "uid" field's value of the PaymentOrder entity.
// If the PaymentOrder object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PaymentOrderMutation) OldUID(ctx context.Context) (v uint64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUID: %w", err)
	}
	return oldValue.UID, nil
}

// AddUID adds u to the "uid" field.
func (m *PaymentOrderMutation) AddUID(u int64) {
	if m.adduid != nil {
		*m.adduid += u
	} else {
		m.adduid = &u
	}
}

// AddedUID returns the value that was added to the "uid" field in this mutation.
func (m *PaymentOrderMutation) AddedUID() (r int64, exists bool) {
	v := m.adduid
	if v == nil {
		return
	}
	return *v, true
}

// ResetUID resets all changes to the "uid" field.
func (m *PaymentOrderMutation) ResetUID() {
	m.uid = nil
	m.adduid = nil
}

// SetProductID sets the "product_id" field.
func (m *PaymentOrderMutation) SetProductID(i int32) {
	m.product_id = &i
	m.addproduct_id = nil
}

// ProductID returns the value of the "product_id" field in the mutation.
func (m *PaymentOrderMutation) ProductID() (r int32, exists bool) {
	v := m.product_id
	if v == nil {
		return
	}
	return *v, true
}

// OldProductID returns the old "product_id" field's value of the PaymentOrder entity.
// If the PaymentOrder object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PaymentOrderMutation) OldProductID(ctx context.Context) (v int32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldProductID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldProductID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldProductID: %w", err)
	}
	return oldValue.ProductID, nil
}

// AddProductID adds i to the "product_id" field.
func (m *PaymentOrderMutation) AddProductID(i int32) {
	if m.addproduct_id != nil {
		*m.addproduct_id += i
	} else {
		m.addproduct_id = &i
	}
}

// AddedProductID returns the value that was added to the "product_id" field in this mutation.
func (m *PaymentOrderMutation) AddedProductID() (r int32, exists bool) {
	v := m.addproduct_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetProductID resets all changes to the "product_id" field.
func (m *PaymentOrderMutation) ResetProductID() {
	m.product_id = nil
	m.addproduct_id = nil
}

// SetThirdPartyProductID sets the "third_party_product_id" field.
func (m *PaymentOrderMutation) SetThirdPartyProductID(s string) {
	m.third_party_product_id = &s
}

// ThirdPartyProductID returns the value of the "third_party_product_id" field in the mutation.
func (m *PaymentOrderMutation) ThirdPartyProductID() (r string, exists bool) {
	v := m.third_party_product_id
	if v == nil {
		return
	}
	return *v, true
}

// OldThirdPartyProductID returns the old "third_party_product_id" field's value of the PaymentOrder entity.
// If the PaymentOrder object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PaymentOrderMutation) OldThirdPartyProductID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldThirdPartyProductID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldThirdPartyProductID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldThirdPartyProductID: %w", err)
	}
	return oldValue.ThirdPartyProductID, nil
}

// ResetThirdPartyProductID resets all changes to the "third_party_product_id" field.
func (m *PaymentOrderMutation) ResetThirdPartyProductID() {
	m.third_party_product_id = nil
}

// SetPaymentType sets the "payment_type" field.
func (m *PaymentOrderMutation) SetPaymentType(i int32) {
	m.payment_type = &i
	m.addpayment_type = nil
}

// PaymentType returns the value of the "payment_type" field in the mutation.
func (m *PaymentOrderMutation) PaymentType() (r int32, exists bool) {
	v := m.payment_type
	if v == nil {
		return
	}
	return *v, true
}

// OldPaymentType returns the old "payment_type" field's value of the PaymentOrder entity.
// If the PaymentOrder object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PaymentOrderMutation) OldPaymentType(ctx context.Context) (v int32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPaymentType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPaymentType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPaymentType: %w", err)
	}
	return oldValue.PaymentType, nil
}

// AddPaymentType adds i to the "payment_type" field.
func (m *PaymentOrderMutation) AddPaymentType(i int32) {
	if m.addpayment_type != nil {
		*m.addpayment_type += i
	} else {
		m.addpayment_type = &i
	}
}

// AddedPaymentType returns the value that was added to the "payment_type" field in this mutation.
func (m *PaymentOrderMutation) AddedPaymentType() (r int32, exists bool) {
	v := m.addpayment_type
	if v == nil {
		return
	}
	return *v, true
}

// ResetPaymentType resets all changes to the "payment_type" field.
func (m *PaymentOrderMutation) ResetPaymentType() {
	m.payment_type = nil
	m.addpayment_type = nil
}

// SetStatus sets the "status" field.
func (m *PaymentOrderMutation) SetStatus(pts paymentTypes.OrderStatus) {
	m.status = &pts
	m.addstatus = nil
}

// Status returns the value of the "status" field in the mutation.
func (m *PaymentOrderMutation) Status() (r paymentTypes.OrderStatus, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the PaymentOrder entity.
// If the PaymentOrder object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PaymentOrderMutation) OldStatus(ctx context.Context) (v paymentTypes.OrderStatus, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// AddStatus adds pts to the "status" field.
func (m *PaymentOrderMutation) AddStatus(pts paymentTypes.OrderStatus) {
	if m.addstatus != nil {
		*m.addstatus += pts
	} else {
		m.addstatus = &pts
	}
}

// AddedStatus returns the value that was added to the "status" field in this mutation.
func (m *PaymentOrderMutation) AddedStatus() (r paymentTypes.OrderStatus, exists bool) {
	v := m.addstatus
	if v == nil {
		return
	}
	return *v, true
}

// ResetStatus resets all changes to the "status" field.
func (m *PaymentOrderMutation) ResetStatus() {
	m.status = nil
	m.addstatus = nil
}

// SetOrderAmountUnit sets the "order_amount_unit" field.
func (m *PaymentOrderMutation) SetOrderAmountUnit(i int64) {
	m.order_amount_unit = &i
	m.addorder_amount_unit = nil
}

// OrderAmountUnit returns the value of the "order_amount_unit" field in the mutation.
func (m *PaymentOrderMutation) OrderAmountUnit() (r int64, exists bool) {
	v := m.order_amount_unit
	if v == nil {
		return
	}
	return *v, true
}

// OldOrderAmountUnit returns the old "order_amount_unit" field's value of the PaymentOrder entity.
// If the PaymentOrder object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PaymentOrderMutation) OldOrderAmountUnit(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOrderAmountUnit is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOrderAmountUnit requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOrderAmountUnit: %w", err)
	}
	return oldValue.OrderAmountUnit, nil
}

// AddOrderAmountUnit adds i to the "order_amount_unit" field.
func (m *PaymentOrderMutation) AddOrderAmountUnit(i int64) {
	if m.addorder_amount_unit != nil {
		*m.addorder_amount_unit += i
	} else {
		m.addorder_amount_unit = &i
	}
}

// AddedOrderAmountUnit returns the value that was added to the "order_amount_unit" field in this mutation.
func (m *PaymentOrderMutation) AddedOrderAmountUnit() (r int64, exists bool) {
	v := m.addorder_amount_unit
	if v == nil {
		return
	}
	return *v, true
}

// ResetOrderAmountUnit resets all changes to the "order_amount_unit" field.
func (m *PaymentOrderMutation) ResetOrderAmountUnit() {
	m.order_amount_unit = nil
	m.addorder_amount_unit = nil
}

// SetOrderAmountNanos sets the "order_amount_nanos" field.
func (m *PaymentOrderMutation) SetOrderAmountNanos(i int32) {
	m.order_amount_nanos = &i
	m.addorder_amount_nanos = nil
}

// OrderAmountNanos returns the value of the "order_amount_nanos" field in the mutation.
func (m *PaymentOrderMutation) OrderAmountNanos() (r int32, exists bool) {
	v := m.order_amount_nanos
	if v == nil {
		return
	}
	return *v, true
}

// OldOrderAmountNanos returns the old "order_amount_nanos" field's value of the PaymentOrder entity.
// If the PaymentOrder object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PaymentOrderMutation) OldOrderAmountNanos(ctx context.Context) (v int32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOrderAmountNanos is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOrderAmountNanos requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOrderAmountNanos: %w", err)
	}
	return oldValue.OrderAmountNanos, nil
}

// AddOrderAmountNanos adds i to the "order_amount_nanos" field.
func (m *PaymentOrderMutation) AddOrderAmountNanos(i int32) {
	if m.addorder_amount_nanos != nil {
		*m.addorder_amount_nanos += i
	} else {
		m.addorder_amount_nanos = &i
	}
}

// AddedOrderAmountNanos returns the value that was added to the "order_amount_nanos" field in this mutation.
func (m *PaymentOrderMutation) AddedOrderAmountNanos() (r int32, exists bool) {
	v := m.addorder_amount_nanos
	if v == nil {
		return
	}
	return *v, true
}

// ResetOrderAmountNanos resets all changes to the "order_amount_nanos" field.
func (m *PaymentOrderMutation) ResetOrderAmountNanos() {
	m.order_amount_nanos = nil
	m.addorder_amount_nanos = nil
}

// SetOrderCurrency sets the "order_currency" field.
func (m *PaymentOrderMutation) SetOrderCurrency(s string) {
	m.order_currency = &s
}

// OrderCurrency returns the value of the "order_currency" field in the mutation.
func (m *PaymentOrderMutation) OrderCurrency() (r string, exists bool) {
	v := m.order_currency
	if v == nil {
		return
	}
	return *v, true
}

// OldOrderCurrency returns the old "order_currency" field's value of the PaymentOrder entity.
// If the PaymentOrder object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PaymentOrderMutation) OldOrderCurrency(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOrderCurrency is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOrderCurrency requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOrderCurrency: %w", err)
	}
	return oldValue.OrderCurrency, nil
}

// ResetOrderCurrency resets all changes to the "order_currency" field.
func (m *PaymentOrderMutation) ResetOrderCurrency() {
	m.order_currency = nil
}

// SetRealAmountUnit sets the "real_amount_unit" field.
func (m *PaymentOrderMutation) SetRealAmountUnit(i int64) {
	m.real_amount_unit = &i
	m.addreal_amount_unit = nil
}

// RealAmountUnit returns the value of the "real_amount_unit" field in the mutation.
func (m *PaymentOrderMutation) RealAmountUnit() (r int64, exists bool) {
	v := m.real_amount_unit
	if v == nil {
		return
	}
	return *v, true
}

// OldRealAmountUnit returns the old "real_amount_unit" field's value of the PaymentOrder entity.
// If the PaymentOrder object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PaymentOrderMutation) OldRealAmountUnit(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRealAmountUnit is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRealAmountUnit requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRealAmountUnit: %w", err)
	}
	return oldValue.RealAmountUnit, nil
}

// AddRealAmountUnit adds i to the "real_amount_unit" field.
func (m *PaymentOrderMutation) AddRealAmountUnit(i int64) {
	if m.addreal_amount_unit != nil {
		*m.addreal_amount_unit += i
	} else {
		m.addreal_amount_unit = &i
	}
}

// AddedRealAmountUnit returns the value that was added to the "real_amount_unit" field in this mutation.
func (m *PaymentOrderMutation) AddedRealAmountUnit() (r int64, exists bool) {
	v := m.addreal_amount_unit
	if v == nil {
		return
	}
	return *v, true
}

// ResetRealAmountUnit resets all changes to the "real_amount_unit" field.
func (m *PaymentOrderMutation) ResetRealAmountUnit() {
	m.real_amount_unit = nil
	m.addreal_amount_unit = nil
}

// SetRealAmountNanos sets the "real_amount_nanos" field.
func (m *PaymentOrderMutation) SetRealAmountNanos(i int32) {
	m.real_amount_nanos = &i
	m.addreal_amount_nanos = nil
}

// RealAmountNanos returns the value of the "real_amount_nanos" field in the mutation.
func (m *PaymentOrderMutation) RealAmountNanos() (r int32, exists bool) {
	v := m.real_amount_nanos
	if v == nil {
		return
	}
	return *v, true
}

// OldRealAmountNanos returns the old "real_amount_nanos" field's value of the PaymentOrder entity.
// If the PaymentOrder object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PaymentOrderMutation) OldRealAmountNanos(ctx context.Context) (v int32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRealAmountNanos is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRealAmountNanos requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRealAmountNanos: %w", err)
	}
	return oldValue.RealAmountNanos, nil
}

// AddRealAmountNanos adds i to the "real_amount_nanos" field.
func (m *PaymentOrderMutation) AddRealAmountNanos(i int32) {
	if m.addreal_amount_nanos != nil {
		*m.addreal_amount_nanos += i
	} else {
		m.addreal_amount_nanos = &i
	}
}

// AddedRealAmountNanos returns the value that was added to the "real_amount_nanos" field in this mutation.
func (m *PaymentOrderMutation) AddedRealAmountNanos() (r int32, exists bool) {
	v := m.addreal_amount_nanos
	if v == nil {
		return
	}
	return *v, true
}

// ResetRealAmountNanos resets all changes to the "real_amount_nanos" field.
func (m *PaymentOrderMutation) ResetRealAmountNanos() {
	m.real_amount_nanos = nil
	m.addreal_amount_nanos = nil
}

// SetRealCurrency sets the "real_currency" field.
func (m *PaymentOrderMutation) SetRealCurrency(s string) {
	m.real_currency = &s
}

// RealCurrency returns the value of the "real_currency" field in the mutation.
func (m *PaymentOrderMutation) RealCurrency() (r string, exists bool) {
	v := m.real_currency
	if v == nil {
		return
	}
	return *v, true
}

// OldRealCurrency returns the old "real_currency" field's value of the PaymentOrder entity.
// If the PaymentOrder object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PaymentOrderMutation) OldRealCurrency(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRealCurrency is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRealCurrency requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRealCurrency: %w", err)
	}
	return oldValue.RealCurrency, nil
}

// ResetRealCurrency resets all changes to the "real_currency" field.
func (m *PaymentOrderMutation) ResetRealCurrency() {
	m.real_currency = nil
}

// SetThirdPartyOrderID sets the "third_party_order_id" field.
func (m *PaymentOrderMutation) SetThirdPartyOrderID(s string) {
	m.third_party_order_id = &s
}

// ThirdPartyOrderID returns the value of the "third_party_order_id" field in the mutation.
func (m *PaymentOrderMutation) ThirdPartyOrderID() (r string, exists bool) {
	v := m.third_party_order_id
	if v == nil {
		return
	}
	return *v, true
}

// OldThirdPartyOrderID returns the old "third_party_order_id" field's value of the PaymentOrder entity.
// If the PaymentOrder object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PaymentOrderMutation) OldThirdPartyOrderID(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldThirdPartyOrderID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldThirdPartyOrderID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldThirdPartyOrderID: %w", err)
	}
	return oldValue.ThirdPartyOrderID, nil
}

// ClearThirdPartyOrderID clears the value of the "third_party_order_id" field.
func (m *PaymentOrderMutation) ClearThirdPartyOrderID() {
	m.third_party_order_id = nil
	m.clearedFields[paymentorder.FieldThirdPartyOrderID] = struct{}{}
}

// ThirdPartyOrderIDCleared returns if the "third_party_order_id" field was cleared in this mutation.
func (m *PaymentOrderMutation) ThirdPartyOrderIDCleared() bool {
	_, ok := m.clearedFields[paymentorder.FieldThirdPartyOrderID]
	return ok
}

// ResetThirdPartyOrderID resets all changes to the "third_party_order_id" field.
func (m *PaymentOrderMutation) ResetThirdPartyOrderID() {
	m.third_party_order_id = nil
	delete(m.clearedFields, paymentorder.FieldThirdPartyOrderID)
}

// SetCredential sets the "credential" field.
func (m *PaymentOrderMutation) SetCredential(s string) {
	m.credential = &s
}

// Credential returns the value of the "credential" field in the mutation.
func (m *PaymentOrderMutation) Credential() (r string, exists bool) {
	v := m.credential
	if v == nil {
		return
	}
	return *v, true
}

// OldCredential returns the old "credential" field's value of the PaymentOrder entity.
// If the PaymentOrder object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PaymentOrderMutation) OldCredential(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCredential is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCredential requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCredential: %w", err)
	}
	return oldValue.Credential, nil
}

// ClearCredential clears the value of the "credential" field.
func (m *PaymentOrderMutation) ClearCredential() {
	m.credential = nil
	m.clearedFields[paymentorder.FieldCredential] = struct{}{}
}

// CredentialCleared returns if the "credential" field was cleared in this mutation.
func (m *PaymentOrderMutation) CredentialCleared() bool {
	_, ok := m.clearedFields[paymentorder.FieldCredential]
	return ok
}

// ResetCredential resets all changes to the "credential" field.
func (m *PaymentOrderMutation) ResetCredential() {
	m.credential = nil
	delete(m.clearedFields, paymentorder.FieldCredential)
}

// SetCredentialHash sets the "credential_hash" field.
func (m *PaymentOrderMutation) SetCredentialHash(s string) {
	m.credential_hash = &s
}

// CredentialHash returns the value of the "credential_hash" field in the mutation.
func (m *PaymentOrderMutation) CredentialHash() (r string, exists bool) {
	v := m.credential_hash
	if v == nil {
		return
	}
	return *v, true
}

// OldCredentialHash returns the old "credential_hash" field's value of the PaymentOrder entity.
// If the PaymentOrder object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PaymentOrderMutation) OldCredentialHash(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCredentialHash is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCredentialHash requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCredentialHash: %w", err)
	}
	return oldValue.CredentialHash, nil
}

// ClearCredentialHash clears the value of the "credential_hash" field.
func (m *PaymentOrderMutation) ClearCredentialHash() {
	m.credential_hash = nil
	m.clearedFields[paymentorder.FieldCredentialHash] = struct{}{}
}

// CredentialHashCleared returns if the "credential_hash" field was cleared in this mutation.
func (m *PaymentOrderMutation) CredentialHashCleared() bool {
	_, ok := m.clearedFields[paymentorder.FieldCredentialHash]
	return ok
}

// ResetCredentialHash resets all changes to the "credential_hash" field.
func (m *PaymentOrderMutation) ResetCredentialHash() {
	m.credential_hash = nil
	delete(m.clearedFields, paymentorder.FieldCredentialHash)
}

// SetRewards sets the "rewards" field.
func (m *PaymentOrderMutation) SetRewards(jm json.RawMessage) {
	m.rewards = &jm
	m.appendrewards = nil
}

// Rewards returns the value of the "rewards" field in the mutation.
func (m *PaymentOrderMutation) Rewards() (r json.RawMessage, exists bool) {
	v := m.rewards
	if v == nil {
		return
	}
	return *v, true
}

// OldRewards returns the old "rewards" field's value of the PaymentOrder entity.
// If the PaymentOrder object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PaymentOrderMutation) OldRewards(ctx context.Context) (v json.RawMessage, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRewards is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRewards requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRewards: %w", err)
	}
	return oldValue.Rewards, nil
}

// AppendRewards adds jm to the "rewards" field.
func (m *PaymentOrderMutation) AppendRewards(jm json.RawMessage) {
	m.appendrewards = append(m.appendrewards, jm...)
}

// AppendedRewards returns the list of values that were appended to the "rewards" field in this mutation.
func (m *PaymentOrderMutation) AppendedRewards() (json.RawMessage, bool) {
	if len(m.appendrewards) == 0 {
		return nil, false
	}
	return m.appendrewards, true
}

// ClearRewards clears the value of the "rewards" field.
func (m *PaymentOrderMutation) ClearRewards() {
	m.rewards = nil
	m.appendrewards = nil
	m.clearedFields[paymentorder.FieldRewards] = struct{}{}
}

// RewardsCleared returns if the "rewards" field was cleared in this mutation.
func (m *PaymentOrderMutation) RewardsCleared() bool {
	_, ok := m.clearedFields[paymentorder.FieldRewards]
	return ok
}

// ResetRewards resets all changes to the "rewards" field.
func (m *PaymentOrderMutation) ResetRewards() {
	m.rewards = nil
	m.appendrewards = nil
	delete(m.clearedFields, paymentorder.FieldRewards)
}

// SetRetryTimes sets the "retry_times" field.
func (m *PaymentOrderMutation) SetRetryTimes(i int32) {
	m.retry_times = &i
	m.addretry_times = nil
}

// RetryTimes returns the value of the "retry_times" field in the mutation.
func (m *PaymentOrderMutation) RetryTimes() (r int32, exists bool) {
	v := m.retry_times
	if v == nil {
		return
	}
	return *v, true
}

// OldRetryTimes returns the old "retry_times" field's value of the PaymentOrder entity.
// If the PaymentOrder object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PaymentOrderMutation) OldRetryTimes(ctx context.Context) (v int32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRetryTimes is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRetryTimes requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRetryTimes: %w", err)
	}
	return oldValue.RetryTimes, nil
}

// AddRetryTimes adds i to the "retry_times" field.
func (m *PaymentOrderMutation) AddRetryTimes(i int32) {
	if m.addretry_times != nil {
		*m.addretry_times += i
	} else {
		m.addretry_times = &i
	}
}

// AddedRetryTimes returns the value that was added to the "retry_times" field in this mutation.
func (m *PaymentOrderMutation) AddedRetryTimes() (r int32, exists bool) {
	v := m.addretry_times
	if v == nil {
		return
	}
	return *v, true
}

// ResetRetryTimes resets all changes to the "retry_times" field.
func (m *PaymentOrderMutation) ResetRetryTimes() {
	m.retry_times = nil
	m.addretry_times = nil
}

// SetCancelReason sets the "cancel_reason" field.
func (m *PaymentOrderMutation) SetCancelReason(s string) {
	m.cancel_reason = &s
}

// CancelReason returns the value of the "cancel_reason" field in the mutation.
func (m *PaymentOrderMutation) CancelReason() (r string, exists bool) {
	v := m.cancel_reason
	if v == nil {
		return
	}
	return *v, true
}

// OldCancelReason returns the old "cancel_reason" field's value of the PaymentOrder entity.
// If the PaymentOrder object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PaymentOrderMutation) OldCancelReason(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCancelReason is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCancelReason requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCancelReason: %w", err)
	}
	return oldValue.CancelReason, nil
}

// ResetCancelReason resets all changes to the "cancel_reason" field.
func (m *PaymentOrderMutation) ResetCancelReason() {
	m.cancel_reason = nil
}

// SetRefundReason sets the "refund_reason" field.
func (m *PaymentOrderMutation) SetRefundReason(s string) {
	m.refund_reason = &s
}

// RefundReason returns the value of the "refund_reason" field in the mutation.
func (m *PaymentOrderMutation) RefundReason() (r string, exists bool) {
	v := m.refund_reason
	if v == nil {
		return
	}
	return *v, true
}

// OldRefundReason returns the old "refund_reason" field's value of the PaymentOrder entity.
// If the PaymentOrder object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PaymentOrderMutation) OldRefundReason(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRefundReason is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRefundReason requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRefundReason: %w", err)
	}
	return oldValue.RefundReason, nil
}

// ResetRefundReason resets all changes to the "refund_reason" field.
func (m *PaymentOrderMutation) ResetRefundReason() {
	m.refund_reason = nil
}

// SetIsSandbox sets the "is_sandbox" field.
func (m *PaymentOrderMutation) SetIsSandbox(b bool) {
	m.is_sandbox = &b
}

// IsSandbox returns the value of the "is_sandbox" field in the mutation.
func (m *PaymentOrderMutation) IsSandbox() (r bool, exists bool) {
	v := m.is_sandbox
	if v == nil {
		return
	}
	return *v, true
}

// OldIsSandbox returns the old "is_sandbox" field's value of the PaymentOrder entity.
// If the PaymentOrder object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PaymentOrderMutation) OldIsSandbox(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIsSandbox is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIsSandbox requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIsSandbox: %w", err)
	}
	return oldValue.IsSandbox, nil
}

// ResetIsSandbox resets all changes to the "is_sandbox" field.
func (m *PaymentOrderMutation) ResetIsSandbox() {
	m.is_sandbox = nil
}

// SetCreateAtUnix sets the "create_at_unix" field.
func (m *PaymentOrderMutation) SetCreateAtUnix(i int64) {
	m.create_at_unix = &i
	m.addcreate_at_unix = nil
}

// CreateAtUnix returns the value of the "create_at_unix" field in the mutation.
func (m *PaymentOrderMutation) CreateAtUnix() (r int64, exists bool) {
	v := m.create_at_unix
	if v == nil {
		return
	}
	return *v, true
}

// OldCreateAtUnix returns the old "create_at_unix" field's value of the PaymentOrder entity.
// If the PaymentOrder object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PaymentOrderMutation) OldCreateAtUnix(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreateAtUnix is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreateAtUnix requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreateAtUnix: %w", err)
	}
	return oldValue.CreateAtUnix, nil
}

// AddCreateAtUnix adds i to the "create_at_unix" field.
func (m *PaymentOrderMutation) AddCreateAtUnix(i int64) {
	if m.addcreate_at_unix != nil {
		*m.addcreate_at_unix += i
	} else {
		m.addcreate_at_unix = &i
	}
}

// AddedCreateAtUnix returns the value that was added to the "create_at_unix" field in this mutation.
func (m *PaymentOrderMutation) AddedCreateAtUnix() (r int64, exists bool) {
	v := m.addcreate_at_unix
	if v == nil {
		return
	}
	return *v, true
}

// ResetCreateAtUnix resets all changes to the "create_at_unix" field.
func (m *PaymentOrderMutation) ResetCreateAtUnix() {
	m.create_at_unix = nil
	m.addcreate_at_unix = nil
}

// SetUpdateAtUnix sets the "update_at_unix" field.
func (m *PaymentOrderMutation) SetUpdateAtUnix(i int64) {
	m.update_at_unix = &i
	m.addupdate_at_unix = nil
}

// UpdateAtUnix returns the value of the "update_at_unix" field in the mutation.
func (m *PaymentOrderMutation) UpdateAtUnix() (r int64, exists bool) {
	v := m.update_at_unix
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdateAtUnix returns the old "update_at_unix" field's value of the PaymentOrder entity.
// If the PaymentOrder object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PaymentOrderMutation) OldUpdateAtUnix(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdateAtUnix is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdateAtUnix requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdateAtUnix: %w", err)
	}
	return oldValue.UpdateAtUnix, nil
}

// AddUpdateAtUnix adds i to the "update_at_unix" field.
func (m *PaymentOrderMutation) AddUpdateAtUnix(i int64) {
	if m.addupdate_at_unix != nil {
		*m.addupdate_at_unix += i
	} else {
		m.addupdate_at_unix = &i
	}
}

// AddedUpdateAtUnix returns the value that was added to the "update_at_unix" field in this mutation.
func (m *PaymentOrderMutation) AddedUpdateAtUnix() (r int64, exists bool) {
	v := m.addupdate_at_unix
	if v == nil {
		return
	}
	return *v, true
}

// ResetUpdateAtUnix resets all changes to the "update_at_unix" field.
func (m *PaymentOrderMutation) ResetUpdateAtUnix() {
	m.update_at_unix = nil
	m.addupdate_at_unix = nil
}

// SetPayAtUnix sets the "pay_at_unix" field.
func (m *PaymentOrderMutation) SetPayAtUnix(i int64) {
	m.pay_at_unix = &i
	m.addpay_at_unix = nil
}

// PayAtUnix returns the value of the "pay_at_unix" field in the mutation.
func (m *PaymentOrderMutation) PayAtUnix() (r int64, exists bool) {
	v := m.pay_at_unix
	if v == nil {
		return
	}
	return *v, true
}

// OldPayAtUnix returns the old "pay_at_unix" field's value of the PaymentOrder entity.
// If the PaymentOrder object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PaymentOrderMutation) OldPayAtUnix(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPayAtUnix is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPayAtUnix requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPayAtUnix: %w", err)
	}
	return oldValue.PayAtUnix, nil
}

// AddPayAtUnix adds i to the "pay_at_unix" field.
func (m *PaymentOrderMutation) AddPayAtUnix(i int64) {
	if m.addpay_at_unix != nil {
		*m.addpay_at_unix += i
	} else {
		m.addpay_at_unix = &i
	}
}

// AddedPayAtUnix returns the value that was added to the "pay_at_unix" field in this mutation.
func (m *PaymentOrderMutation) AddedPayAtUnix() (r int64, exists bool) {
	v := m.addpay_at_unix
	if v == nil {
		return
	}
	return *v, true
}

// ResetPayAtUnix resets all changes to the "pay_at_unix" field.
func (m *PaymentOrderMutation) ResetPayAtUnix() {
	m.pay_at_unix = nil
	m.addpay_at_unix = nil
}

// SetRefundAtUnix sets the "refund_at_unix" field.
func (m *PaymentOrderMutation) SetRefundAtUnix(i int64) {
	m.refund_at_unix = &i
	m.addrefund_at_unix = nil
}

// RefundAtUnix returns the value of the "refund_at_unix" field in the mutation.
func (m *PaymentOrderMutation) RefundAtUnix() (r int64, exists bool) {
	v := m.refund_at_unix
	if v == nil {
		return
	}
	return *v, true
}

// OldRefundAtUnix returns the old "refund_at_unix" field's value of the PaymentOrder entity.
// If the PaymentOrder object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PaymentOrderMutation) OldRefundAtUnix(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRefundAtUnix is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRefundAtUnix requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRefundAtUnix: %w", err)
	}
	return oldValue.RefundAtUnix, nil
}

// AddRefundAtUnix adds i to the "refund_at_unix" field.
func (m *PaymentOrderMutation) AddRefundAtUnix(i int64) {
	if m.addrefund_at_unix != nil {
		*m.addrefund_at_unix += i
	} else {
		m.addrefund_at_unix = &i
	}
}

// AddedRefundAtUnix returns the value that was added to the "refund_at_unix" field in this mutation.
func (m *PaymentOrderMutation) AddedRefundAtUnix() (r int64, exists bool) {
	v := m.addrefund_at_unix
	if v == nil {
		return
	}
	return *v, true
}

// ResetRefundAtUnix resets all changes to the "refund_at_unix" field.
func (m *PaymentOrderMutation) ResetRefundAtUnix() {
	m.refund_at_unix = nil
	m.addrefund_at_unix = nil
}

// SetCancelAtUnix sets the "cancel_at_unix" field.
func (m *PaymentOrderMutation) SetCancelAtUnix(i int64) {
	m.cancel_at_unix = &i
	m.addcancel_at_unix = nil
}

// CancelAtUnix returns the value of the "cancel_at_unix" field in the mutation.
func (m *PaymentOrderMutation) CancelAtUnix() (r int64, exists bool) {
	v := m.cancel_at_unix
	if v == nil {
		return
	}
	return *v, true
}

// OldCancelAtUnix returns the old "cancel_at_unix" field's value of the PaymentOrder entity.
// If the PaymentOrder object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PaymentOrderMutation) OldCancelAtUnix(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCancelAtUnix is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCancelAtUnix requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCancelAtUnix: %w", err)
	}
	return oldValue.CancelAtUnix, nil
}

// AddCancelAtUnix adds i to the "cancel_at_unix" field.
func (m *PaymentOrderMutation) AddCancelAtUnix(i int64) {
	if m.addcancel_at_unix != nil {
		*m.addcancel_at_unix += i
	} else {
		m.addcancel_at_unix = &i
	}
}

// AddedCancelAtUnix returns the value that was added to the "cancel_at_unix" field in this mutation.
func (m *PaymentOrderMutation) AddedCancelAtUnix() (r int64, exists bool) {
	v := m.addcancel_at_unix
	if v == nil {
		return
	}
	return *v, true
}

// ResetCancelAtUnix resets all changes to the "cancel_at_unix" field.
func (m *PaymentOrderMutation) ResetCancelAtUnix() {
	m.cancel_at_unix = nil
	m.addcancel_at_unix = nil
}

// Where appends a list predicates to the PaymentOrderMutation builder.
func (m *PaymentOrderMutation) Where(ps ...predicate.PaymentOrder) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the PaymentOrderMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *PaymentOrderMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.PaymentOrder, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *PaymentOrderMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *PaymentOrderMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (PaymentOrder).
func (m *PaymentOrderMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *PaymentOrderMutation) Fields() []string {
	fields := make([]string, 0, 24)
	if m.uid != nil {
		fields = append(fields, paymentorder.FieldUID)
	}
	if m.product_id != nil {
		fields = append(fields, paymentorder.FieldProductID)
	}
	if m.third_party_product_id != nil {
		fields = append(fields, paymentorder.FieldThirdPartyProductID)
	}
	if m.payment_type != nil {
		fields = append(fields, paymentorder.FieldPaymentType)
	}
	if m.status != nil {
		fields = append(fields, paymentorder.FieldStatus)
	}
	if m.order_amount_unit != nil {
		fields = append(fields, paymentorder.FieldOrderAmountUnit)
	}
	if m.order_amount_nanos != nil {
		fields = append(fields, paymentorder.FieldOrderAmountNanos)
	}
	if m.order_currency != nil {
		fields = append(fields, paymentorder.FieldOrderCurrency)
	}
	if m.real_amount_unit != nil {
		fields = append(fields, paymentorder.FieldRealAmountUnit)
	}
	if m.real_amount_nanos != nil {
		fields = append(fields, paymentorder.FieldRealAmountNanos)
	}
	if m.real_currency != nil {
		fields = append(fields, paymentorder.FieldRealCurrency)
	}
	if m.third_party_order_id != nil {
		fields = append(fields, paymentorder.FieldThirdPartyOrderID)
	}
	if m.credential != nil {
		fields = append(fields, paymentorder.FieldCredential)
	}
	if m.credential_hash != nil {
		fields = append(fields, paymentorder.FieldCredentialHash)
	}
	if m.rewards != nil {
		fields = append(fields, paymentorder.FieldRewards)
	}
	if m.retry_times != nil {
		fields = append(fields, paymentorder.FieldRetryTimes)
	}
	if m.cancel_reason != nil {
		fields = append(fields, paymentorder.FieldCancelReason)
	}
	if m.refund_reason != nil {
		fields = append(fields, paymentorder.FieldRefundReason)
	}
	if m.is_sandbox != nil {
		fields = append(fields, paymentorder.FieldIsSandbox)
	}
	if m.create_at_unix != nil {
		fields = append(fields, paymentorder.FieldCreateAtUnix)
	}
	if m.update_at_unix != nil {
		fields = append(fields, paymentorder.FieldUpdateAtUnix)
	}
	if m.pay_at_unix != nil {
		fields = append(fields, paymentorder.FieldPayAtUnix)
	}
	if m.refund_at_unix != nil {
		fields = append(fields, paymentorder.FieldRefundAtUnix)
	}
	if m.cancel_at_unix != nil {
		fields = append(fields, paymentorder.FieldCancelAtUnix)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *PaymentOrderMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case paymentorder.FieldUID:
		return m.UID()
	case paymentorder.FieldProductID:
		return m.ProductID()
	case paymentorder.FieldThirdPartyProductID:
		return m.ThirdPartyProductID()
	case paymentorder.FieldPaymentType:
		return m.PaymentType()
	case paymentorder.FieldStatus:
		return m.Status()
	case paymentorder.FieldOrderAmountUnit:
		return m.OrderAmountUnit()
	case paymentorder.FieldOrderAmountNanos:
		return m.OrderAmountNanos()
	case paymentorder.FieldOrderCurrency:
		return m.OrderCurrency()
	case paymentorder.FieldRealAmountUnit:
		return m.RealAmountUnit()
	case paymentorder.FieldRealAmountNanos:
		return m.RealAmountNanos()
	case paymentorder.FieldRealCurrency:
		return m.RealCurrency()
	case paymentorder.FieldThirdPartyOrderID:
		return m.ThirdPartyOrderID()
	case paymentorder.FieldCredential:
		return m.Credential()
	case paymentorder.FieldCredentialHash:
		return m.CredentialHash()
	case paymentorder.FieldRewards:
		return m.Rewards()
	case paymentorder.FieldRetryTimes:
		return m.RetryTimes()
	case paymentorder.FieldCancelReason:
		return m.CancelReason()
	case paymentorder.FieldRefundReason:
		return m.RefundReason()
	case paymentorder.FieldIsSandbox:
		return m.IsSandbox()
	case paymentorder.FieldCreateAtUnix:
		return m.CreateAtUnix()
	case paymentorder.FieldUpdateAtUnix:
		return m.UpdateAtUnix()
	case paymentorder.FieldPayAtUnix:
		return m.PayAtUnix()
	case paymentorder.FieldRefundAtUnix:
		return m.RefundAtUnix()
	case paymentorder.FieldCancelAtUnix:
		return m.CancelAtUnix()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *PaymentOrderMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case paymentorder.FieldUID:
		return m.OldUID(ctx)
	case paymentorder.FieldProductID:
		return m.OldProductID(ctx)
	case paymentorder.FieldThirdPartyProductID:
		return m.OldThirdPartyProductID(ctx)
	case paymentorder.FieldPaymentType:
		return m.OldPaymentType(ctx)
	case paymentorder.FieldStatus:
		return m.OldStatus(ctx)
	case paymentorder.FieldOrderAmountUnit:
		return m.OldOrderAmountUnit(ctx)
	case paymentorder.FieldOrderAmountNanos:
		return m.OldOrderAmountNanos(ctx)
	case paymentorder.FieldOrderCurrency:
		return m.OldOrderCurrency(ctx)
	case paymentorder.FieldRealAmountUnit:
		return m.OldRealAmountUnit(ctx)
	case paymentorder.FieldRealAmountNanos:
		return m.OldRealAmountNanos(ctx)
	case paymentorder.FieldRealCurrency:
		return m.OldRealCurrency(ctx)
	case paymentorder.FieldThirdPartyOrderID:
		return m.OldThirdPartyOrderID(ctx)
	case paymentorder.FieldCredential:
		return m.OldCredential(ctx)
	case paymentorder.FieldCredentialHash:
		return m.OldCredentialHash(ctx)
	case paymentorder.FieldRewards:
		return m.OldRewards(ctx)
	case paymentorder.FieldRetryTimes:
		return m.OldRetryTimes(ctx)
	case paymentorder.FieldCancelReason:
		return m.OldCancelReason(ctx)
	case paymentorder.FieldRefundReason:
		return m.OldRefundReason(ctx)
	case paymentorder.FieldIsSandbox:
		return m.OldIsSandbox(ctx)
	case paymentorder.FieldCreateAtUnix:
		return m.OldCreateAtUnix(ctx)
	case paymentorder.FieldUpdateAtUnix:
		return m.OldUpdateAtUnix(ctx)
	case paymentorder.FieldPayAtUnix:
		return m.OldPayAtUnix(ctx)
	case paymentorder.FieldRefundAtUnix:
		return m.OldRefundAtUnix(ctx)
	case paymentorder.FieldCancelAtUnix:
		return m.OldCancelAtUnix(ctx)
	}
	return nil, fmt.Errorf("unknown PaymentOrder field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PaymentOrderMutation) SetField(name string, value ent.Value) error {
	switch name {
	case paymentorder.FieldUID:
		v, ok := value.(uint64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUID(v)
		return nil
	case paymentorder.FieldProductID:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetProductID(v)
		return nil
	case paymentorder.FieldThirdPartyProductID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetThirdPartyProductID(v)
		return nil
	case paymentorder.FieldPaymentType:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPaymentType(v)
		return nil
	case paymentorder.FieldStatus:
		v, ok := value.(paymentTypes.OrderStatus)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	case paymentorder.FieldOrderAmountUnit:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOrderAmountUnit(v)
		return nil
	case paymentorder.FieldOrderAmountNanos:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOrderAmountNanos(v)
		return nil
	case paymentorder.FieldOrderCurrency:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOrderCurrency(v)
		return nil
	case paymentorder.FieldRealAmountUnit:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRealAmountUnit(v)
		return nil
	case paymentorder.FieldRealAmountNanos:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRealAmountNanos(v)
		return nil
	case paymentorder.FieldRealCurrency:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRealCurrency(v)
		return nil
	case paymentorder.FieldThirdPartyOrderID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetThirdPartyOrderID(v)
		return nil
	case paymentorder.FieldCredential:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCredential(v)
		return nil
	case paymentorder.FieldCredentialHash:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCredentialHash(v)
		return nil
	case paymentorder.FieldRewards:
		v, ok := value.(json.RawMessage)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRewards(v)
		return nil
	case paymentorder.FieldRetryTimes:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRetryTimes(v)
		return nil
	case paymentorder.FieldCancelReason:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCancelReason(v)
		return nil
	case paymentorder.FieldRefundReason:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRefundReason(v)
		return nil
	case paymentorder.FieldIsSandbox:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIsSandbox(v)
		return nil
	case paymentorder.FieldCreateAtUnix:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreateAtUnix(v)
		return nil
	case paymentorder.FieldUpdateAtUnix:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdateAtUnix(v)
		return nil
	case paymentorder.FieldPayAtUnix:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPayAtUnix(v)
		return nil
	case paymentorder.FieldRefundAtUnix:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRefundAtUnix(v)
		return nil
	case paymentorder.FieldCancelAtUnix:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCancelAtUnix(v)
		return nil
	}
	return fmt.Errorf("unknown PaymentOrder field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *PaymentOrderMutation) AddedFields() []string {
	var fields []string
	if m.adduid != nil {
		fields = append(fields, paymentorder.FieldUID)
	}
	if m.addproduct_id != nil {
		fields = append(fields, paymentorder.FieldProductID)
	}
	if m.addpayment_type != nil {
		fields = append(fields, paymentorder.FieldPaymentType)
	}
	if m.addstatus != nil {
		fields = append(fields, paymentorder.FieldStatus)
	}
	if m.addorder_amount_unit != nil {
		fields = append(fields, paymentorder.FieldOrderAmountUnit)
	}
	if m.addorder_amount_nanos != nil {
		fields = append(fields, paymentorder.FieldOrderAmountNanos)
	}
	if m.addreal_amount_unit != nil {
		fields = append(fields, paymentorder.FieldRealAmountUnit)
	}
	if m.addreal_amount_nanos != nil {
		fields = append(fields, paymentorder.FieldRealAmountNanos)
	}
	if m.addretry_times != nil {
		fields = append(fields, paymentorder.FieldRetryTimes)
	}
	if m.addcreate_at_unix != nil {
		fields = append(fields, paymentorder.FieldCreateAtUnix)
	}
	if m.addupdate_at_unix != nil {
		fields = append(fields, paymentorder.FieldUpdateAtUnix)
	}
	if m.addpay_at_unix != nil {
		fields = append(fields, paymentorder.FieldPayAtUnix)
	}
	if m.addrefund_at_unix != nil {
		fields = append(fields, paymentorder.FieldRefundAtUnix)
	}
	if m.addcancel_at_unix != nil {
		fields = append(fields, paymentorder.FieldCancelAtUnix)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *PaymentOrderMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case paymentorder.FieldUID:
		return m.AddedUID()
	case paymentorder.FieldProductID:
		return m.AddedProductID()
	case paymentorder.FieldPaymentType:
		return m.AddedPaymentType()
	case paymentorder.FieldStatus:
		return m.AddedStatus()
	case paymentorder.FieldOrderAmountUnit:
		return m.AddedOrderAmountUnit()
	case paymentorder.FieldOrderAmountNanos:
		return m.AddedOrderAmountNanos()
	case paymentorder.FieldRealAmountUnit:
		return m.AddedRealAmountUnit()
	case paymentorder.FieldRealAmountNanos:
		return m.AddedRealAmountNanos()
	case paymentorder.FieldRetryTimes:
		return m.AddedRetryTimes()
	case paymentorder.FieldCreateAtUnix:
		return m.AddedCreateAtUnix()
	case paymentorder.FieldUpdateAtUnix:
		return m.AddedUpdateAtUnix()
	case paymentorder.FieldPayAtUnix:
		return m.AddedPayAtUnix()
	case paymentorder.FieldRefundAtUnix:
		return m.AddedRefundAtUnix()
	case paymentorder.FieldCancelAtUnix:
		return m.AddedCancelAtUnix()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PaymentOrderMutation) AddField(name string, value ent.Value) error {
	switch name {
	case paymentorder.FieldUID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddUID(v)
		return nil
	case paymentorder.FieldProductID:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddProductID(v)
		return nil
	case paymentorder.FieldPaymentType:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddPaymentType(v)
		return nil
	case paymentorder.FieldStatus:
		v, ok := value.(paymentTypes.OrderStatus)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddStatus(v)
		return nil
	case paymentorder.FieldOrderAmountUnit:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddOrderAmountUnit(v)
		return nil
	case paymentorder.FieldOrderAmountNanos:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddOrderAmountNanos(v)
		return nil
	case paymentorder.FieldRealAmountUnit:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddRealAmountUnit(v)
		return nil
	case paymentorder.FieldRealAmountNanos:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddRealAmountNanos(v)
		return nil
	case paymentorder.FieldRetryTimes:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddRetryTimes(v)
		return nil
	case paymentorder.FieldCreateAtUnix:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddCreateAtUnix(v)
		return nil
	case paymentorder.FieldUpdateAtUnix:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddUpdateAtUnix(v)
		return nil
	case paymentorder.FieldPayAtUnix:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddPayAtUnix(v)
		return nil
	case paymentorder.FieldRefundAtUnix:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddRefundAtUnix(v)
		return nil
	case paymentorder.FieldCancelAtUnix:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddCancelAtUnix(v)
		return nil
	}
	return fmt.Errorf("unknown PaymentOrder numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *PaymentOrderMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(paymentorder.FieldThirdPartyOrderID) {
		fields = append(fields, paymentorder.FieldThirdPartyOrderID)
	}
	if m.FieldCleared(paymentorder.FieldCredential) {
		fields = append(fields, paymentorder.FieldCredential)
	}
	if m.FieldCleared(paymentorder.FieldCredentialHash) {
		fields = append(fields, paymentorder.FieldCredentialHash)
	}
	if m.FieldCleared(paymentorder.FieldRewards) {
		fields = append(fields, paymentorder.FieldRewards)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *PaymentOrderMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *PaymentOrderMutation) ClearField(name string) error {
	switch name {
	case paymentorder.FieldThirdPartyOrderID:
		m.ClearThirdPartyOrderID()
		return nil
	case paymentorder.FieldCredential:
		m.ClearCredential()
		return nil
	case paymentorder.FieldCredentialHash:
		m.ClearCredentialHash()
		return nil
	case paymentorder.FieldRewards:
		m.ClearRewards()
		return nil
	}
	return fmt.Errorf("unknown PaymentOrder nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *PaymentOrderMutation) ResetField(name string) error {
	switch name {
	case paymentorder.FieldUID:
		m.ResetUID()
		return nil
	case paymentorder.FieldProductID:
		m.ResetProductID()
		return nil
	case paymentorder.FieldThirdPartyProductID:
		m.ResetThirdPartyProductID()
		return nil
	case paymentorder.FieldPaymentType:
		m.ResetPaymentType()
		return nil
	case paymentorder.FieldStatus:
		m.ResetStatus()
		return nil
	case paymentorder.FieldOrderAmountUnit:
		m.ResetOrderAmountUnit()
		return nil
	case paymentorder.FieldOrderAmountNanos:
		m.ResetOrderAmountNanos()
		return nil
	case paymentorder.FieldOrderCurrency:
		m.ResetOrderCurrency()
		return nil
	case paymentorder.FieldRealAmountUnit:
		m.ResetRealAmountUnit()
		return nil
	case paymentorder.FieldRealAmountNanos:
		m.ResetRealAmountNanos()
		return nil
	case paymentorder.FieldRealCurrency:
		m.ResetRealCurrency()
		return nil
	case paymentorder.FieldThirdPartyOrderID:
		m.ResetThirdPartyOrderID()
		return nil
	case paymentorder.FieldCredential:
		m.ResetCredential()
		return nil
	case paymentorder.FieldCredentialHash:
		m.ResetCredentialHash()
		return nil
	case paymentorder.FieldRewards:
		m.ResetRewards()
		return nil
	case paymentorder.FieldRetryTimes:
		m.ResetRetryTimes()
		return nil
	case paymentorder.FieldCancelReason:
		m.ResetCancelReason()
		return nil
	case paymentorder.FieldRefundReason:
		m.ResetRefundReason()
		return nil
	case paymentorder.FieldIsSandbox:
		m.ResetIsSandbox()
		return nil
	case paymentorder.FieldCreateAtUnix:
		m.ResetCreateAtUnix()
		return nil
	case paymentorder.FieldUpdateAtUnix:
		m.ResetUpdateAtUnix()
		return nil
	case paymentorder.FieldPayAtUnix:
		m.ResetPayAtUnix()
		return nil
	case paymentorder.FieldRefundAtUnix:
		m.ResetRefundAtUnix()
		return nil
	case paymentorder.FieldCancelAtUnix:
		m.ResetCancelAtUnix()
		return nil
	}
	return fmt.Errorf("unknown PaymentOrder field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *PaymentOrderMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *PaymentOrderMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *PaymentOrderMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *PaymentOrderMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *PaymentOrderMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *PaymentOrderMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *PaymentOrderMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown PaymentOrder unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *PaymentOrderMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown PaymentOrder edge %s", name)
}
