// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/2comjie/taoxi-server/app/Api/payment/internal/store/ent/paymentorder"
	"github.com/2comjie/taoxi-server/app/Api/payment/internal/store/ent/predicate"
	paymentTypes "github.com/2comjie/taoxi-server/app/Api/payment/types"
)

// PaymentOrderUpdate is the builder for updating PaymentOrder entities.
type PaymentOrderUpdate struct {
	config
	hooks    []Hook
	mutation *PaymentOrderMutation
}

// Where appends a list predicates to the PaymentOrderUpdate builder.
func (_u *PaymentOrderUpdate) Where(ps ...predicate.PaymentOrder) *PaymentOrderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentOrderUpdate) SetStatus(v paymentTypes.OrderStatus) *PaymentOrderUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableStatus(v *paymentTypes.OrderStatus) *PaymentOrderUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *PaymentOrderUpdate) AddStatus(v paymentTypes.OrderStatus) *PaymentOrderUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// SetRealAmountUnit sets the "real_amount_unit" field.
func (_u *PaymentOrderUpdate) SetRealAmountUnit(v int64) *PaymentOrderUpdate {
	_u.mutation.ResetRealAmountUnit()
	_u.mutation.SetRealAmountUnit(v)
	return _u
}

// SetNillableRealAmountUnit sets the "real_amount_unit" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableRealAmountUnit(v *int64) *PaymentOrderUpdate {
	if v != nil {
		_u.SetRealAmountUnit(*v)
	}
	return _u
}

// AddRealAmountUnit adds value to the "real_amount_unit" field.
func (_u *PaymentOrderUpdate) AddRealAmountUnit(v int64) *PaymentOrderUpdate {
	_u.mutation.AddRealAmountUnit(v)
	return _u
}

// SetRealAmountNanos sets the "real_amount_nanos" field.
func (_u *PaymentOrderUpdate) SetRealAmountNanos(v int32) *PaymentOrderUpdate {
	_u.mutation.ResetRealAmountNanos()
	_u.mutation.SetRealAmountNanos(v)
	return _u
}

// SetNillableRealAmountNanos sets the "real_amount_nanos" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableRealAmountNanos(v *int32) *PaymentOrderUpdate {
	if v != nil {
		_u.SetRealAmountNanos(*v)
	}
	return _u
}

// AddRealAmountNanos adds value to the "real_amount_nanos" field.
func (_u *PaymentOrderUpdate) AddRealAmountNanos(v int32) *PaymentOrderUpdate {
	_u.mutation.AddRealAmountNanos(v)
	return _u
}

// SetRealCurrency sets the "real_currency" field.
func (_u *PaymentOrderUpdate) SetRealCurrency(v string) *PaymentOrderUpdate {
	_u.mutation.SetRealCurrency(v)
	return _u
}

// SetNillableRealCurrency sets the "real_currency" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableRealCurrency(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetRealCurrency(*v)
	}
	return _u
}

// SetThirdPartyOrderID sets the "third_party_order_id" field.
func (_u *PaymentOrderUpdate) SetThirdPartyOrderID(v string) *PaymentOrderUpdate {
	_u.mutation.SetThirdPartyOrderID(v)
	return _u
}

// SetNillableThirdPartyOrderID sets the "third_party_order_id" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableThirdPartyOrderID(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetThirdPartyOrderID(*v)
	}
	return _u
}

// ClearThirdPartyOrderID clears the value of the "third_party_order_id" field.
func (_u *PaymentOrderUpdate) ClearThirdPartyOrderID() *PaymentOrderUpdate {
	_u.mutation.ClearThirdPartyOrderID()
	return _u
}

// SetCredential sets the "credential" field.
func (_u *PaymentOrderUpdate) SetCredential(v string) *PaymentOrderUpdate {
	_u.mutation.SetCredential(v)
	return _u
}

// SetNillableCredential sets the "credential" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableCredential(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetCredential(*v)
	}
	return _u
}

// ClearCredential clears the value of the "credential" field.
func (_u *PaymentOrderUpdate) ClearCredential() *PaymentOrderUpdate {
	_u.mutation.ClearCredential()
	return _u
}

// SetCredentialHash sets the "credential_hash" field.
func (_u *PaymentOrderUpdate) SetCredentialHash(v string) *PaymentOrderUpdate {
	_u.mutation.SetCredentialHash(v)
	return _u
}

// SetNillableCredentialHash sets the "credential_hash" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableCredentialHash(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetCredentialHash(*v)
	}
	return _u
}

// ClearCredentialHash clears the value of the "credential_hash" field.
func (_u *PaymentOrderUpdate) ClearCredentialHash() *PaymentOrderUpdate {
	_u.mutation.ClearCredentialHash()
	return _u
}

// SetRewards sets the "rewards" field.
func (_u *PaymentOrderUpdate) SetRewards(v json.RawMessage) *PaymentOrderUpdate {
	_u.mutation.SetRewards(v)
	return _u
}

// AppendRewards appends value to the "rewards" field.
func (_u *PaymentOrderUpdate) AppendRewards(v json.RawMessage) *PaymentOrderUpdate {
	_u.mutation.AppendRewards(v)
	return _u
}

// ClearRewards clears the value of the "rewards" field.
func (_u *PaymentOrderUpdate) ClearRewards() *PaymentOrderUpdate {
	_u.mutation.ClearRewards()
	return _u
}

// SetRetryTimes sets the "retry_times" field.
func (_u *PaymentOrderUpdate) SetRetryTimes(v int32) *PaymentOrderUpdate {
	_u.mutation.ResetRetryTimes()
	_u.mutation.SetRetryTimes(v)
	return _u
}

// SetNillableRetryTimes sets the "retry_times" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableRetryTimes(v *int32) *PaymentOrderUpdate {
	if v != nil {
		_u.SetRetryTimes(*v)
	}
	return _u
}

// AddRetryTimes adds value to the "retry_times" field.
func (_u *PaymentOrderUpdate) AddRetryTimes(v int32) *PaymentOrderUpdate {
	_u.mutation.AddRetryTimes(v)
	return _u
}

// SetCancelReason sets the "cancel_reason" field.
func (_u *PaymentOrderUpdate) SetCancelReason(v string) *PaymentOrderUpdate {
	_u.mutation.SetCancelReason(v)
	return _u
}

// SetNillableCancelReason sets the "cancel_reason" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableCancelReason(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetCancelReason(*v)
	}
	return _u
}

// SetRefundReason sets the "refund_reason" field.
func (_u *PaymentOrderUpdate) SetRefundReason(v string) *PaymentOrderUpdate {
	_u.mutation.SetRefundReason(v)
	return _u
}

// SetNillableRefundReason sets the "refund_reason" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableRefundReason(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetRefundReason(*v)
	}
	return _u
}

// SetIsSandbox sets the "is_sandbox" field.
func (_u *PaymentOrderUpdate) SetIsSandbox(v bool) *PaymentOrderUpdate {
	_u.mutation.SetIsSandbox(v)
	return _u
}

// SetNillableIsSandbox sets the "is_sandbox" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableIsSandbox(v *bool) *PaymentOrderUpdate {
	if v != nil {
		_u.SetIsSandbox(*v)
	}
	return _u
}

// SetUpdateAtUnix sets the "update_at_unix" field.
func (_u *PaymentOrderUpdate) SetUpdateAtUnix(v int64) *PaymentOrderUpdate {
	_u.mutation.ResetUpdateAtUnix()
	_u.mutation.SetUpdateAtUnix(v)
	return _u
}

// AddUpdateAtUnix adds value to the "update_at_unix" field.
func (_u *PaymentOrderUpdate) AddUpdateAtUnix(v int64) *PaymentOrderUpdate {
	_u.mutation.AddUpdateAtUnix(v)
	return _u
}

// SetPayAtUnix sets the "pay_at_unix" field.
func (_u *PaymentOrderUpdate) SetPayAtUnix(v int64) *PaymentOrderUpdate {
	_u.mutation.ResetPayAtUnix()
	_u.mutation.SetPayAtUnix(v)
	return _u
}

// SetNillablePayAtUnix sets the "pay_at_unix" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillablePayAtUnix(v *int64) *PaymentOrderUpdate {
	if v != nil {
		_u.SetPayAtUnix(*v)
	}
	return _u
}

// AddPayAtUnix adds value to the "pay_at_unix" field.
func (_u *PaymentOrderUpdate) AddPayAtUnix(v int64) *PaymentOrderUpdate {
	_u.mutation.AddPayAtUnix(v)
	return _u
}

// SetRefundAtUnix sets the "refund_at_unix" field.
func (_u *PaymentOrderUpdate) SetRefundAtUnix(v int64) *PaymentOrderUpdate {
	_u.mutation.ResetRefundAtUnix()
	_u.mutation.SetRefundAtUnix(v)
	return _u
}

// SetNillableRefundAtUnix sets the "refund_at_unix" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableRefundAtUnix(v *int64) *PaymentOrderUpdate {
	if v != nil {
		_u.SetRefundAtUnix(*v)
	}
	return _u
}

// AddRefundAtUnix adds value to the "refund_at_unix" field.
func (_u *PaymentOrderUpdate) AddRefundAtUnix(v int64) *PaymentOrderUpdate {
	_u.mutation.AddRefundAtUnix(v)
	return _u
}

// SetCancelAtUnix sets the "cancel_at_unix" field.
func (_u *PaymentOrderUpdate) SetCancelAtUnix(v int64) *PaymentOrderUpdate {
	_u.mutation.ResetCancelAtUnix()
	_u.mutation.SetCancelAtUnix(v)
	return _u
}

// SetNillableCancelAtUnix sets the "cancel_at_unix" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableCancelAtUnix(v *int64) *PaymentOrderUpdate {
	if v != nil {
		_u.SetCancelAtUnix(*v)
	}
	return _u
}

// AddCancelAtUnix adds value to the "cancel_at_unix" field.
func (_u *PaymentOrderUpdate) AddCancelAtUnix(v int64) *PaymentOrderUpdate {
	_u.mutation.AddCancelAtUnix(v)
	return _u
}

// Mutation returns the PaymentOrderMutation object of the builder.
func (_u *PaymentOrderUpdate) Mutation() *PaymentOrderMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PaymentOrderUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentOrderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PaymentOrderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentOrderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentOrderUpdate) defaults() {
	if _, ok := _u.mutation.UpdateAtUnix(); !ok {
		v := paymentorder.UpdateDefaultUpdateAtUnix()
		_u.mutation.SetUpdateAtUnix(v)
	}
}

func (_u *PaymentOrderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(paymentorder.Table, paymentorder.Columns, sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(paymentorder.FieldStatus, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(paymentorder.FieldStatus, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.RealAmountUnit(); ok {
		_spec.SetField(paymentorder.FieldRealAmountUnit, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRealAmountUnit(); ok {
		_spec.AddField(paymentorder.FieldRealAmountUnit, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RealAmountNanos(); ok {
		_spec.SetField(paymentorder.FieldRealAmountNanos, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedRealAmountNanos(); ok {
		_spec.AddField(paymentorder.FieldRealAmountNanos, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.RealCurrency(); ok {
		_spec.SetField(paymentorder.FieldRealCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.ThirdPartyOrderID(); ok {
		_spec.SetField(paymentorder.FieldThirdPartyOrderID, field.TypeString, value)
	}
	if _u.mutation.ThirdPartyOrderIDCleared() {
		_spec.ClearField(paymentorder.FieldThirdPartyOrderID, field.TypeString)
	}
	if value, ok := _u.mutation.Credential(); ok {
		_spec.SetField(paymentorder.FieldCredential, field.TypeString, value)
	}
	if _u.mutation.CredentialCleared() {
		_spec.ClearField(paymentorder.FieldCredential, field.TypeString)
	}
	if value, ok := _u.mutation.CredentialHash(); ok {
		_spec.SetField(paymentorder.FieldCredentialHash, field.TypeString, value)
	}
	if _u.mutation.CredentialHashCleared() {
		_spec.ClearField(paymentorder.FieldCredentialHash, field.TypeString)
	}
	if value, ok := _u.mutation.Rewards(); ok {
		_spec.SetField(paymentorder.FieldRewards, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRewards(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, paymentorder.FieldRewards, value)
		})
	}
	if _u.mutation.RewardsCleared() {
		_spec.ClearField(paymentorder.FieldRewards, field.TypeJSON)
	}
	if value, ok := _u.mutation.RetryTimes(); ok {
		_spec.SetField(paymentorder.FieldRetryTimes, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedRetryTimes(); ok {
		_spec.AddField(paymentorder.FieldRetryTimes, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.CancelReason(); ok {
		_spec.SetField(paymentorder.FieldCancelReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.RefundReason(); ok {
		_spec.SetField(paymentorder.FieldRefundReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsSandbox(); ok {
		_spec.SetField(paymentorder.FieldIsSandbox, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdateAtUnix(); ok {
		_spec.SetField(paymentorder.FieldUpdateAtUnix, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdateAtUnix(); ok {
		_spec.AddField(paymentorder.FieldUpdateAtUnix, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PayAtUnix(); ok {
		_spec.SetField(paymentorder.FieldPayAtUnix, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPayAtUnix(); ok {
		_spec.AddField(paymentorder.FieldPayAtUnix, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RefundAtUnix(); ok {
		_spec.SetField(paymentorder.FieldRefundAtUnix, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRefundAtUnix(); ok {
		_spec.AddField(paymentorder.FieldRefundAtUnix, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CancelAtUnix(); ok {
		_spec.SetField(paymentorder.FieldCancelAtUnix, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCancelAtUnix(); ok {
		_spec.AddField(paymentorder.FieldCancelAtUnix, field.TypeInt64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PaymentOrderUpdateOne is the builder for updating a single PaymentOrder entity.
type PaymentOrderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PaymentOrderMutation
}

// SetStatus sets the "status" field.
func (_u *PaymentOrderUpdateOne) SetStatus(v paymentTypes.OrderStatus) *PaymentOrderUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableStatus(v *paymentTypes.OrderStatus) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *PaymentOrderUpdateOne) AddStatus(v paymentTypes.OrderStatus) *PaymentOrderUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// SetRealAmountUnit sets the "real_amount_unit" field.
func (_u *PaymentOrderUpdateOne) SetRealAmountUnit(v int64) *PaymentOrderUpdateOne {
	_u.mutation.ResetRealAmountUnit()
	_u.mutation.SetRealAmountUnit(v)
	return _u
}

// SetNillableRealAmountUnit sets the "real_amount_unit" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableRealAmountUnit(v *int64) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetRealAmountUnit(*v)
	}
	return _u
}

// AddRealAmountUnit adds value to the "real_amount_unit" field.
func (_u *PaymentOrderUpdateOne) AddRealAmountUnit(v int64) *PaymentOrderUpdateOne {
	_u.mutation.AddRealAmountUnit(v)
	return _u
}

// SetRealAmountNanos sets the "real_amount_nanos" field.
func (_u *PaymentOrderUpdateOne) SetRealAmountNanos(v int32) *PaymentOrderUpdateOne {
	_u.mutation.ResetRealAmountNanos()
	_u.mutation.SetRealAmountNanos(v)
	return _u
}

// SetNillableRealAmountNanos sets the "real_amount_nanos" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableRealAmountNanos(v *int32) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetRealAmountNanos(*v)
	}
	return _u
}

// AddRealAmountNanos adds value to the "real_amount_nanos" field.
func (_u *PaymentOrderUpdateOne) AddRealAmountNanos(v int32) *PaymentOrderUpdateOne {
	_u.mutation.AddRealAmountNanos(v)
	return _u
}

// SetRealCurrency sets the "real_currency" field.
func (_u *PaymentOrderUpdateOne) SetRealCurrency(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetRealCurrency(v)
	return _u
}

// SetNillableRealCurrency sets the "real_currency" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableRealCurrency(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetRealCurrency(*v)
	}
	return _u
}

// SetThirdPartyOrderID sets the "third_party_order_id" field.
func (_u *PaymentOrderUpdateOne) SetThirdPartyOrderID(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetThirdPartyOrderID(v)
	return _u
}

// SetNillableThirdPartyOrderID sets the "third_party_order_id" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableThirdPartyOrderID(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetThirdPartyOrderID(*v)
	}
	return _u
}

// ClearThirdPartyOrderID clears the value of the "third_party_order_id" field.
func (_u *PaymentOrderUpdateOne) ClearThirdPartyOrderID() *PaymentOrderUpdateOne {
	_u.mutation.ClearThirdPartyOrderID()
	return _u
}

// SetCredential sets the "credential" field.
func (_u *PaymentOrderUpdateOne) SetCredential(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetCredential(v)
	return _u
}

// SetNillableCredential sets the "credential" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableCredential(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetCredential(*v)
	}
	return _u
}

// ClearCredential clears the value of the "credential" field.
func (_u *PaymentOrderUpdateOne) ClearCredential() *PaymentOrderUpdateOne {
	_u.mutation.ClearCredential()
	return _u
}

// SetCredentialHash sets the "credential_hash" field.
func (_u *PaymentOrderUpdateOne) SetCredentialHash(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetCredentialHash(v)
	return _u
}

// SetNillableCredentialHash sets the "credential_hash" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableCredentialHash(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetCredentialHash(*v)
	}
	return _u
}

// ClearCredentialHash clears the value of the "credential_hash" field.
func (_u *PaymentOrderUpdateOne) ClearCredentialHash() *PaymentOrderUpdateOne {
	_u.mutation.ClearCredentialHash()
	return _u
}

// SetRewards sets the "rewards" field.
func (_u *PaymentOrderUpdateOne) SetRewards(v json.RawMessage) *PaymentOrderUpdateOne {
	_u.mutation.SetRewards(v)
	return _u
}

// AppendRewards appends value to the "rewards" field.
func (_u *PaymentOrderUpdateOne) AppendRewards(v json.RawMessage) *PaymentOrderUpdateOne {
	_u.mutation.AppendRewards(v)
	return _u
}

// ClearRewards clears the value of the "rewards" field.
func (_u *PaymentOrderUpdateOne) ClearRewards() *PaymentOrderUpdateOne {
	_u.mutation.ClearRewards()
	return _u
}

// SetRetryTimes sets the "retry_times" field.
func (_u *PaymentOrderUpdateOne) SetRetryTimes(v int32) *PaymentOrderUpdateOne {
	_u.mutation.ResetRetryTimes()
	_u.mutation.SetRetryTimes(v)
	return _u
}

// SetNillableRetryTimes sets the "retry_times" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableRetryTimes(v *int32) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetRetryTimes(*v)
	}
	return _u
}

// AddRetryTimes adds value to the "retry_times" field.
func (_u *PaymentOrderUpdateOne) AddRetryTimes(v int32) *PaymentOrderUpdateOne {
	_u.mutation.AddRetryTimes(v)
	return _u
}

// SetCancelReason sets the "cancel_reason" field.
func (_u *PaymentOrderUpdateOne) SetCancelReason(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetCancelReason(v)
	return _u
}

// SetNillableCancelReason sets the "cancel_reason" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableCancelReason(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetCancelReason(*v)
	}
	return _u
}

// SetRefundReason sets the "refund_reason" field.
func (_u *PaymentOrderUpdateOne) SetRefundReason(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetRefundReason(v)
	return _u
}

// SetNillableRefundReason sets the "refund_reason" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableRefundReason(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetRefundReason(*v)
	}
	return _u
}

// SetIsSandbox sets the "is_sandbox" field.
func (_u *PaymentOrderUpdateOne) SetIsSandbox(v bool) *PaymentOrderUpdateOne {
	_u.mutation.SetIsSandbox(v)
	return _u
}

// SetNillableIsSandbox sets the "is_sandbox" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableIsSandbox(v *bool) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetIsSandbox(*v)
	}
	return _u
}

// SetUpdateAtUnix sets the "update_at_unix" field.
func (_u *PaymentOrderUpdateOne) SetUpdateAtUnix(v int64) *PaymentOrderUpdateOne {
	_u.mutation.ResetUpdateAtUnix()
	_u.mutation.SetUpdateAtUnix(v)
	return _u
}

// AddUpdateAtUnix adds value to the "update_at_unix" field.
func (_u *PaymentOrderUpdateOne) AddUpdateAtUnix(v int64) *PaymentOrderUpdateOne {
	_u.mutation.AddUpdateAtUnix(v)
	return _u
}

// SetPayAtUnix sets the "pay_at_unix" field.
func (_u *PaymentOrderUpdateOne) SetPayAtUnix(v int64) *PaymentOrderUpdateOne {
	_u.mutation.ResetPayAtUnix()
	_u.mutation.SetPayAtUnix(v)
	return _u
}

// SetNillablePayAtUnix sets the "pay_at_unix" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillablePayAtUnix(v *int64) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetPayAtUnix(*v)
	}
	return _u
}

// AddPayAtUnix adds value to the "pay_at_unix" field.
func (_u *PaymentOrderUpdateOne) AddPayAtUnix(v int64) *PaymentOrderUpdateOne {
	_u.mutation.AddPayAtUnix(v)
	return _u
}

// SetRefundAtUnix sets the "refund_at_unix" field.
func (_u *PaymentOrderUpdateOne) SetRefundAtUnix(v int64) *PaymentOrderUpdateOne {
	_u.mutation.ResetRefundAtUnix()
	_u.mutation.SetRefundAtUnix(v)
	return _u
}

// SetNillableRefundAtUnix sets the "refund_at_unix" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableRefundAtUnix(v *int64) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetRefundAtUnix(*v)
	}
	return _u
}

// AddRefundAtUnix adds value to the "refund_at_unix" field.
func (_u *PaymentOrderUpdateOne) AddRefundAtUnix(v int64) *PaymentOrderUpdateOne {
	_u.mutation.AddRefundAtUnix(v)
	return _u
}

// SetCancelAtUnix sets the "cancel_at_unix" field.
func (_u *PaymentOrderUpdateOne) SetCancelAtUnix(v int64) *PaymentOrderUpdateOne {
	_u.mutation.ResetCancelAtUnix()
	_u.mutation.SetCancelAtUnix(v)
	return _u
}

// SetNillableCancelAtUnix sets the "cancel_at_unix" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableCancelAtUnix(v *int64) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetCancelAtUnix(*v)
	}
	return _u
}

// AddCancelAtUnix adds value to the "cancel_at_unix" field.
func (_u *PaymentOrderUpdateOne) AddCancelAtUnix(v int64) *PaymentOrderUpdateOne {
	_u.mutation.AddCancelAtUnix(v)
	return _u
}

// Mutation returns the PaymentOrderMutation object of the builder.
func (_u *PaymentOrderUpdateOne) Mutation() *PaymentOrderMutation {
	return _u.mutation
}

// Where appends a list predicates to the PaymentOrderUpdate builder.
func (_u *PaymentOrderUpdateOne) Where(ps ...predicate.PaymentOrder) *PaymentOrderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PaymentOrderUpdateOne) Select(field string, fields ...string) *PaymentOrderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PaymentOrder entity.
func (_u *PaymentOrderUpdateOne) Save(ctx context.Context) (*PaymentOrder, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentOrderUpdateOne) SaveX(ctx context.Context) *PaymentOrder {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PaymentOrderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentOrderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentOrderUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateAtUnix(); !ok {
		v := paymentorder.UpdateDefaultUpdateAtUnix()
		_u.mutation.SetUpdateAtUnix(v)
	}
}

func (_u *PaymentOrderUpdateOne) sqlSave(ctx context.Context) (_node *PaymentOrder, err error) {
	_spec := sqlgraph.NewUpdateSpec(paymentorder.Table, paymentorder.Columns, sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PaymentOrder.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, paymentorder.FieldID)
		for _, f := range fields {
			if !paymentorder.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != paymentorder.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(paymentorder.FieldStatus, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(paymentorder.FieldStatus, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.RealAmountUnit(); ok {
		_spec.SetField(paymentorder.FieldRealAmountUnit, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRealAmountUnit(); ok {
		_spec.AddField(paymentorder.FieldRealAmountUnit, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RealAmountNanos(); ok {
		_spec.SetField(paymentorder.FieldRealAmountNanos, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedRealAmountNanos(); ok {
		_spec.AddField(paymentorder.FieldRealAmountNanos, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.RealCurrency(); ok {
		_spec.SetField(paymentorder.FieldRealCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.ThirdPartyOrderID(); ok {
		_spec.SetField(paymentorder.FieldThirdPartyOrderID, field.TypeString, value)
	}
	if _u.mutation.ThirdPartyOrderIDCleared() {
		_spec.ClearField(paymentorder.FieldThirdPartyOrderID, field.TypeString)
	}
	if value, ok := _u.mutation.Credential(); ok {
		_spec.SetField(paymentorder.FieldCredential, field.TypeString, value)
	}
	if _u.mutation.CredentialCleared() {
		_spec.ClearField(paymentorder.FieldCredential, field.TypeString)
	}
	if value, ok := _u.mutation.CredentialHash(); ok {
		_spec.SetField(paymentorder.FieldCredentialHash, field.TypeString, value)
	}
	if _u.mutation.CredentialHashCleared() {
		_spec.ClearField(paymentorder.FieldCredentialHash, field.TypeString)
	}
	if value, ok := _u.mutation.Rewards(); ok {
		_spec.SetField(paymentorder.FieldRewards, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRewards(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, paymentorder.FieldRewards, value)
		})
	}
	if _u.mutation.RewardsCleared() {
		_spec.ClearField(paymentorder.FieldRewards, field.TypeJSON)
	}
	if value, ok := _u.mutation.RetryTimes(); ok {
		_spec.SetField(paymentorder.FieldRetryTimes, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedRetryTimes(); ok {
		_spec.AddField(paymentorder.FieldRetryTimes, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.CancelReason(); ok {
		_spec.SetField(paymentorder.FieldCancelReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.RefundReason(); ok {
		_spec.SetField(paymentorder.FieldRefundReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsSandbox(); ok {
		_spec.SetField(paymentorder.FieldIsSandbox, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdateAtUnix(); ok {
		_spec.SetField(paymentorder.FieldUpdateAtUnix, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdateAtUnix(); ok {
		_spec.AddField(paymentorder.FieldUpdateAtUnix, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PayAtUnix(); ok {
		_spec.SetField(paymentorder.FieldPayAtUnix, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPayAtUnix(); ok {
		_spec.AddField(paymentorder.FieldPayAtUnix, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RefundAtUnix(); ok {
		_spec.SetField(paymentorder.FieldRefundAtUnix, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRefundAtUnix(); ok {
		_spec.AddField(paymentorder.FieldRefundAtUnix, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CancelAtUnix(); ok {
		_spec.SetField(paymentorder.FieldCancelAtUnix, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCancelAtUnix(); ok {
		_spec.AddField(paymentorder.FieldCancelAtUnix, field.TypeInt64, value)
	}
	_node = &PaymentOrder{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
