// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/2comjie/taoxi-server/app/Api/payment/internal/store/ent/paymentorder"
	"github.com/2comjie/taoxi-server/app/Api/payment/internal/store/ent/schema"
	paymentTypes "github.com/2comjie/taoxi-server/app/Api/payment/types"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	paymentorderFields := schema.PaymentOrder{}.Fields()
	_ = paymentorderFields
	// paymentorderDescStatus is the schema descriptor for status field.
	paymentorderDescStatus := paymentorderFields[5].Descriptor()
	// paymentorder.DefaultStatus holds the default value on creation for the status field.
	paymentorder.DefaultStatus = paymentTypes.OrderStatus(paymentorderDescStatus.Default.(int32))
	// paymentorderDescRealAmountUnit is the schema descriptor for real_amount_unit field.
	paymentorderDescRealAmountUnit := paymentorderFields[9].Descriptor()
	// paymentorder.DefaultRealAmountUnit holds the default value on creation for the real_amount_unit field.
	paymentorder.DefaultRealAmountUnit = paymentorderDescRealAmountUnit.Default.(int64)
	// paymentorderDescRealAmountNanos is the schema descriptor for real_amount_nanos field.
	paymentorderDescRealAmountNanos := paymentorderFields[10].Descriptor()
	// paymentorder.DefaultRealAmountNanos holds the default value on creation for the real_amount_nanos field.
	paymentorder.DefaultRealAmountNanos = paymentorderDescRealAmountNanos.Default.(int32)
	// paymentorderDescRealCurrency is the schema descriptor for real_currency field.
	paymentorderDescRealCurrency := paymentorderFields[11].Descriptor()
	// paymentorder.DefaultRealCurrency holds the default value on creation for the real_currency field.
	paymentorder.DefaultRealCurrency = paymentorderDescRealCurrency.Default.(string)
	// paymentorderDescRetryTimes is the schema descriptor for retry_times field.
	paymentorderDescRetryTimes := paymentorderFields[16].Descriptor()
	// paymentorder.DefaultRetryTimes holds the default value on creation for the retry_times field.
	paymentorder.DefaultRetryTimes = paymentorderDescRetryTimes.Default.(int32)
	// paymentorderDescCancelReason is the schema descriptor for cancel_reason field.
	paymentorderDescCancelReason := paymentorderFields[17].Descriptor()
	// paymentorder.DefaultCancelReason holds the default value on creation for the cancel_reason field.
	paymentorder.DefaultCancelReason = paymentorderDescCancelReason.Default.(string)
	// paymentorderDescRefundReason is the schema descriptor for refund_reason field.
	paymentorderDescRefundReason := paymentorderFields[18].Descriptor()
	// paymentorder.DefaultRefundReason holds the default value on creation for the refund_reason field.
	paymentorder.DefaultRefundReason = paymentorderDescRefundReason.Default.(string)
	// paymentorderDescIsSandbox is the schema descriptor for is_sandbox field.
	paymentorderDescIsSandbox := paymentorderFields[19].Descriptor()
	// paymentorder.DefaultIsSandbox holds the default value on creation for the is_sandbox field.
	paymentorder.DefaultIsSandbox = paymentorderDescIsSandbox.Default.(bool)
	// paymentorderDescCreateAtUnix is the schema descriptor for create_at_unix field.
	paymentorderDescCreateAtUnix := paymentorderFields[20].Descriptor()
	// paymentorder.DefaultCreateAtUnix holds the default value on creation for the create_at_unix field.
	paymentorder.DefaultCreateAtUnix = paymentorderDescCreateAtUnix.Default.(func() int64)
	// paymentorderDescUpdateAtUnix is the schema descriptor for update_at_unix field.
	paymentorderDescUpdateAtUnix := paymentorderFields[21].Descriptor()
	// paymentorder.DefaultUpdateAtUnix holds the default value on creation for the update_at_unix field.
	paymentorder.DefaultUpdateAtUnix = paymentorderDescUpdateAtUnix.Default.(func() int64)
	// paymentorder.UpdateDefaultUpdateAtUnix holds the default value on update for the update_at_unix field.
	paymentorder.UpdateDefaultUpdateAtUnix = paymentorderDescUpdateAtUnix.UpdateDefault.(func() int64)
	// paymentorderDescPayAtUnix is the schema descriptor for pay_at_unix field.
	paymentorderDescPayAtUnix := paymentorderFields[22].Descriptor()
	// paymentorder.DefaultPayAtUnix holds the default value on creation for the pay_at_unix field.
	paymentorder.DefaultPayAtUnix = paymentorderDescPayAtUnix.Default.(int64)
	// paymentorderDescRefundAtUnix is the schema descriptor for refund_at_unix field.
	paymentorderDescRefundAtUnix := paymentorderFields[23].Descriptor()
	// paymentorder.DefaultRefundAtUnix holds the default value on creation for the refund_at_unix field.
	paymentorder.DefaultRefundAtUnix = paymentorderDescRefundAtUnix.Default.(int64)
	// paymentorderDescCancelAtUnix is the schema descriptor for cancel_at_unix field.
	paymentorderDescCancelAtUnix := paymentorderFields[24].Descriptor()
	// paymentorder.DefaultCancelAtUnix holds the default value on creation for the cancel_at_unix field.
	paymentorder.DefaultCancelAtUnix = paymentorderDescCancelAtUnix.Default.(int64)
}
