// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ItemsColumns holds the columns for the "items" table.
	ItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "uid", Type: field.TypeUint64},
		{Name: "item_id", Type: field.TypeInt32},
		{Name: "count", Type: field.TypeInt64},
		{Name: "used_count", Type: field.TypeInt64, Default: 0},
		{Name: "expire_at_unix", Type: field.TypeInt64, Default: 0},
		{Name: "source", Type: field.TypeString, Size: 255, Default: ""},
		{Name: "create_at_unix", Type: field.TypeInt64},
		{Name: "update_at_unix", Type: field.TypeInt64},
	}
	// ItemsTable holds the schema information for the "items" table.
	ItemsTable = &schema.Table{
		Name:       "items",
		Columns:    ItemsColumns,
		PrimaryKey: []*schema.Column{ItemsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "item_expire_at_unix",
				Unique:  false,
				Columns: []*schema.Column{ItemsColumns[5]},
			},
			{
				Name:    "item_uid_item_id_expire_at_unix",
				Unique:  false,
				Columns: []*schema.Column{ItemsColumns[1], ItemsColumns[2], ItemsColumns[5]},
			},
		},
	}
	// ItemNoncesColumns holds the columns for the "item_nonces" table.
	ItemNoncesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "uid", Type: field.TypeUint64},
		{Name: "nonce", Type: field.TypeString, Size: 128},
		{Name: "op_type", Type: field.TypeInt32},
		{Name: "create_at_unix", Type: field.TypeInt64},
	}
	// ItemNoncesTable holds the schema information for the "item_nonces" table.
	ItemNoncesTable = &schema.Table{
		Name:       "item_nonces",
		Columns:    ItemNoncesColumns,
		PrimaryKey: []*schema.Column{ItemNoncesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "itemnonce_uid_nonce_op_type",
				Unique:  true,
				Columns: []*schema.Column{ItemNoncesColumns[1], ItemNoncesColumns[2], ItemNoncesColumns[3]},
			},
		},
	}
	// ItemUserLocksColumns holds the columns for the "item_user_locks" table.
	ItemUserLocksColumns = []*schema.Column{
		{Name: "uid", Type: field.TypeUint64, Increment: true},
	}
	// ItemUserLocksTable holds the schema information for the "item_user_locks" table.
	ItemUserLocksTable = &schema.Table{
		Name:       "item_user_locks",
		Columns:    ItemUserLocksColumns,
		PrimaryKey: []*schema.Column{ItemUserLocksColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ItemsTable,
		ItemNoncesTable,
		ItemUserLocksTable,
	}
)

func init() {
}
