// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AccountColumns holds the columns for the "account" table.
	AccountColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "is_deleted", Type: field.TypeBool, Default: false},
		{Name: "create_at_unix", Type: field.TypeInt64},
		{Name: "update_at_unix", Type: field.TypeInt64},
	}
	// AccountTable holds the schema information for the "account" table.
	AccountTable = &schema.Table{
		Name:       "account",
		Columns:    AccountColumns,
		PrimaryKey: []*schema.Column{AccountColumns[0]},
	}
	// IdentityColumns holds the columns for the "identity" table.
	IdentityColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "uid", Type: field.TypeUint64},
		{Name: "login_type", Type: field.TypeInt32},
		{Name: "app_id", Type: field.TypeString, Size: 255},
		{Name: "open_id", Type: field.TypeString, Size: 255},
		{Name: "union_id", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "create_at_unix", Type: field.TypeInt64},
	}
	// IdentityTable holds the schema information for the "identity" table.
	IdentityTable = &schema.Table{
		Name:       "identity",
		Columns:    IdentityColumns,
		PrimaryKey: []*schema.Column{IdentityColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "identity_login_type_app_id_open_id",
				Unique:  true,
				Columns: []*schema.Column{IdentityColumns[2], IdentityColumns[3], IdentityColumns[4]},
			},
			{
				Name:    "identity_uid_login_type_app_id",
				Unique:  true,
				Columns: []*schema.Column{IdentityColumns[1], IdentityColumns[2], IdentityColumns[3]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AccountTable,
		IdentityTable,
	}
)

func init() {
	AccountTable.Annotation = &entsql.Annotation{
		Table:          "account",
		IncrementStart: func(i int) *int { return &i }(10000000),
	}
	IdentityTable.Annotation = &entsql.Annotation{
		Table: "identity",
	}
}
