// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/2comjie/taoxi-server/app/Api/items/internal/store/ent/itemnonce"
	"github.com/2comjie/taoxi-server/app/Api/items/internal/store/ent/predicate"
)

// ItemNonceUpdate is the builder for updating ItemNonce entities.
type ItemNonceUpdate struct {
	config
	hooks    []Hook
	mutation *ItemNonceMutation
}

// Where appends a list predicates to the ItemNonceUpdate builder.
func (_u *ItemNonceUpdate) Where(ps ...predicate.ItemNonce) *ItemNonceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// Mutation returns the ItemNonceMutation object of the builder.
func (_u *ItemNonceUpdate) Mutation() *ItemNonceMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ItemNonceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ItemNonceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ItemNonceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ItemNonceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ItemNonceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(itemnonce.Table, itemnonce.Columns, sqlgraph.NewFieldSpec(itemnonce.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{itemnonce.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ItemNonceUpdateOne is the builder for updating a single ItemNonce entity.
type ItemNonceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ItemNonceMutation
}

// Mutation returns the ItemNonceMutation object of the builder.
func (_u *ItemNonceUpdateOne) Mutation() *ItemNonceMutation {
	return _u.mutation
}

// Where appends a list predicates to the ItemNonceUpdate builder.
func (_u *ItemNonceUpdateOne) Where(ps ...predicate.ItemNonce) *ItemNonceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ItemNonceUpdateOne) Select(field string, fields ...string) *ItemNonceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ItemNonce entity.
func (_u *ItemNonceUpdateOne) Save(ctx context.Context) (*ItemNonce, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ItemNonceUpdateOne) SaveX(ctx context.Context) *ItemNonce {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ItemNonceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ItemNonceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ItemNonceUpdateOne) sqlSave(ctx context.Context) (_node *ItemNonce, err error) {
	_spec := sqlgraph.NewUpdateSpec(itemnonce.Table, itemnonce.Columns, sqlgraph.NewFieldSpec(itemnonce.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ItemNonce.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, itemnonce.FieldID)
		for _, f := range fields {
			if !itemnonce.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != itemnonce.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &ItemNonce{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{itemnonce.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
