// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/2comjie/taoxi-server/app/Api/items/internal/store/ent/item"
)

// Item is the model entity for the Item schema.
type Item struct {
	config `json:"-"`
	// ID of the ent.
	// 道具记录自增ID
	ID int64 `json:"id,omitempty"`
	// 玩家UID
	UID uint64 `json:"uid,omitempty"`
	// 道具配置ID
	ItemID int32 `json:"item_id,omitempty"`
	// 道具总数量
	Count int64 `json:"count,omitempty"`
	// 已使用数量
	UsedCount int64 `json:"used_count,omitempty"`
	// 过期时间，Unix秒，0表示永不过期
	ExpireAtUnix int64 `json:"expire_at_unix,omitempty"`
	// 道具来源
	Source string `json:"source,omitempty"`
	// 创建时间，Unix秒
	CreateAtUnix int64 `json:"create_at_unix,omitempty"`
	// 更新时间，Unix秒
	UpdateAtUnix int64 `json:"update_at_unix,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Item) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case item.FieldID, item.FieldUID, item.FieldItemID, item.FieldCount, item.FieldUsedCount, item.FieldExpireAtUnix, item.FieldCreateAtUnix, item.FieldUpdateAtUnix:
			values[i] = new(sql.NullInt64)
		case item.FieldSource:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Item fields.
func (_m *Item) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case item.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case item.FieldUID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field uid", values[i])
			} else if value.Valid {
				_m.UID = uint64(value.Int64)
			}
		case item.FieldItemID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field item_id", values[i])
			} else if value.Valid {
				_m.ItemID = int32(value.Int64)
			}
		case item.FieldCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field count", values[i])
			} else if value.Valid {
				_m.Count = value.Int64
			}
		case item.FieldUsedCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field used_count", values[i])
			} else if value.Valid {
				_m.UsedCount = value.Int64
			}
		case item.FieldExpireAtUnix:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field expire_at_unix", values[i])
			} else if value.Valid {
				_m.ExpireAtUnix = value.Int64
			}
		case item.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case item.FieldCreateAtUnix:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field create_at_unix", values[i])
			} else if value.Valid {
				_m.CreateAtUnix = value.Int64
			}
		case item.FieldUpdateAtUnix:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field update_at_unix", values[i])
			} else if value.Valid {
				_m.UpdateAtUnix = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Item.
// This includes values selected through modifiers, order, etc.
func (_m *Item) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Item.
// Note that you need to call Item.Unwrap() before calling this method if this Item
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Item) Update() *ItemUpdateOne {
	return NewItemClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Item entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Item) Unwrap() *Item {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Item is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Item) String() string {
	var builder strings.Builder
	builder.WriteString("Item(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("uid=")
	builder.WriteString(fmt.Sprintf("%v", _m.UID))
	builder.WriteString(", ")
	builder.WriteString("item_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ItemID))
	builder.WriteString(", ")
	builder.WriteString("count=")
	builder.WriteString(fmt.Sprintf("%v", _m.Count))
	builder.WriteString(", ")
	builder.WriteString("used_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.UsedCount))
	builder.WriteString(", ")
	builder.WriteString("expire_at_unix=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExpireAtUnix))
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	builder.WriteString("create_at_unix=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreateAtUnix))
	builder.WriteString(", ")
	builder.WriteString("update_at_unix=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpdateAtUnix))
	builder.WriteByte(')')
	return builder.String()
}

// Items is a parsable slice of Item.
type Items []*Item
