// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/2comjie/taoxi-server/app/Api/items/internal/store/ent/itemnonce"
	itemTypes "github.com/2comjie/taoxi-server/app/Api/items/types"
)

// ItemNonceCreate is the builder for creating a ItemNonce entity.
type ItemNonceCreate struct {
	config
	mutation *ItemNonceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUID sets the "uid" field.
func (_c *ItemNonceCreate) SetUID(v uint64) *ItemNonceCreate {
	_c.mutation.SetUID(v)
	return _c
}

// SetNonce sets the "nonce" field.
func (_c *ItemNonceCreate) SetNonce(v string) *ItemNonceCreate {
	_c.mutation.SetNonce(v)
	return _c
}

// SetOpType sets the "op_type" field.
func (_c *ItemNonceCreate) SetOpType(v itemTypes.OperationType) *ItemNonceCreate {
	_c.mutation.SetOpType(v)
	return _c
}

// SetCreateAtUnix sets the "create_at_unix" field.
func (_c *ItemNonceCreate) SetCreateAtUnix(v int64) *ItemNonceCreate {
	_c.mutation.SetCreateAtUnix(v)
	return _c
}

// SetNillableCreateAtUnix sets the "create_at_unix" field if the given value is not nil.
func (_c *ItemNonceCreate) SetNillableCreateAtUnix(v *int64) *ItemNonceCreate {
	if v != nil {
		_c.SetCreateAtUnix(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ItemNonceCreate) SetID(v uint64) *ItemNonceCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ItemNonceMutation object of the builder.
func (_c *ItemNonceCreate) Mutation() *ItemNonceMutation {
	return _c.mutation
}

// Save creates the ItemNonce in the database.
func (_c *ItemNonceCreate) Save(ctx context.Context) (*ItemNonce, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ItemNonceCreate) SaveX(ctx context.Context) *ItemNonce {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ItemNonceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ItemNonceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ItemNonceCreate) defaults() {
	if _, ok := _c.mutation.CreateAtUnix(); !ok {
		v := itemnonce.DefaultCreateAtUnix()
		_c.mutation.SetCreateAtUnix(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ItemNonceCreate) check() error {
	if _, ok := _c.mutation.UID(); !ok {
		return &ValidationError{Name: "uid", err: errors.New(`ent: missing required field "ItemNonce.uid"`)}
	}
	if _, ok := _c.mutation.Nonce(); !ok {
		return &ValidationError{Name: "nonce", err: errors.New(`ent: missing required field "ItemNonce.nonce"`)}
	}
	if v, ok := _c.mutation.Nonce(); ok {
		if err := itemnonce.NonceValidator(v); err != nil {
			return &ValidationError{Name: "nonce", err: fmt.Errorf(`ent: validator failed for field "ItemNonce.nonce": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OpType(); !ok {
		return &ValidationError{Name: "op_type", err: errors.New(`ent: missing required field "ItemNonce.op_type"`)}
	}
	if _, ok := _c.mutation.CreateAtUnix(); !ok {
		return &ValidationError{Name: "create_at_unix", err: errors.New(`ent: missing required field "ItemNonce.create_at_unix"`)}
	}
	return nil
}

func (_c *ItemNonceCreate) sqlSave(ctx context.Context) (*ItemNonce, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ItemNonceCreate) createSpec() (*ItemNonce, *sqlgraph.CreateSpec) {
	var (
		_node = &ItemNonce{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(itemnonce.Table, sqlgraph.NewFieldSpec(itemnonce.FieldID, field.TypeUint64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.UID(); ok {
		_spec.SetField(itemnonce.FieldUID, field.TypeUint64, value)
		_node.UID = value
	}
	if value, ok := _c.mutation.Nonce(); ok {
		_spec.SetField(itemnonce.FieldNonce, field.TypeString, value)
		_node.Nonce = value
	}
	if value, ok := _c.mutation.OpType(); ok {
		_spec.SetField(itemnonce.FieldOpType, field.TypeInt32, value)
		_node.OpType = value
	}
	if value, ok := _c.mutation.CreateAtUnix(); ok {
		_spec.SetField(itemnonce.FieldCreateAtUnix, field.TypeInt64, value)
		_node.CreateAtUnix = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ItemNonce.Create().
//		SetUID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ItemNonceUpsert) {
//			SetUID(v+v).
//		}).
//		Exec(ctx)
func (_c *ItemNonceCreate) OnConflict(opts ...sql.ConflictOption) *ItemNonceUpsertOne {
	_c.conflict = opts
	return &ItemNonceUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ItemNonce.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ItemNonceCreate) OnConflictColumns(columns ...string) *ItemNonceUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ItemNonceUpsertOne{
		create: _c,
	}
}

type (
	// ItemNonceUpsertOne is the builder for "upsert"-ing
	//  one ItemNonce node.
	ItemNonceUpsertOne struct {
		create *ItemNonceCreate
	}

	// ItemNonceUpsert is the "OnConflict" setter.
	ItemNonceUpsert struct {
		*sql.UpdateSet
	}
)

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ItemNonce.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(itemnonce.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ItemNonceUpsertOne) UpdateNewValues() *ItemNonceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(itemnonce.FieldID)
		}
		if _, exists := u.create.mutation.UID(); exists {
			s.SetIgnore(itemnonce.FieldUID)
		}
		if _, exists := u.create.mutation.Nonce(); exists {
			s.SetIgnore(itemnonce.FieldNonce)
		}
		if _, exists := u.create.mutation.OpType(); exists {
			s.SetIgnore(itemnonce.FieldOpType)
		}
		if _, exists := u.create.mutation.CreateAtUnix(); exists {
			s.SetIgnore(itemnonce.FieldCreateAtUnix)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ItemNonce.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ItemNonceUpsertOne) Ignore() *ItemNonceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ItemNonceUpsertOne) DoNothing() *ItemNonceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ItemNonceCreate.OnConflict
// documentation for more info.
func (u *ItemNonceUpsertOne) Update(set func(*ItemNonceUpsert)) *ItemNonceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ItemNonceUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *ItemNonceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ItemNonceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ItemNonceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ItemNonceUpsertOne) ID(ctx context.Context) (id uint64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ItemNonceUpsertOne) IDX(ctx context.Context) uint64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ItemNonceCreateBulk is the builder for creating many ItemNonce entities in bulk.
type ItemNonceCreateBulk struct {
	config
	err      error
	builders []*ItemNonceCreate
	conflict []sql.ConflictOption
}

// Save creates the ItemNonce entities in the database.
func (_c *ItemNonceCreateBulk) Save(ctx context.Context) ([]*ItemNonce, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ItemNonce, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ItemNonceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ItemNonceCreateBulk) SaveX(ctx context.Context) []*ItemNonce {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ItemNonceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ItemNonceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ItemNonce.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ItemNonceUpsert) {
//			SetUID(v+v).
//		}).
//		Exec(ctx)
func (_c *ItemNonceCreateBulk) OnConflict(opts ...sql.ConflictOption) *ItemNonceUpsertBulk {
	_c.conflict = opts
	return &ItemNonceUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ItemNonce.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ItemNonceCreateBulk) OnConflictColumns(columns ...string) *ItemNonceUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ItemNonceUpsertBulk{
		create: _c,
	}
}

// ItemNonceUpsertBulk is the builder for "upsert"-ing
// a bulk of ItemNonce nodes.
type ItemNonceUpsertBulk struct {
	create *ItemNonceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ItemNonce.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(itemnonce.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ItemNonceUpsertBulk) UpdateNewValues() *ItemNonceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(itemnonce.FieldID)
			}
			if _, exists := b.mutation.UID(); exists {
				s.SetIgnore(itemnonce.FieldUID)
			}
			if _, exists := b.mutation.Nonce(); exists {
				s.SetIgnore(itemnonce.FieldNonce)
			}
			if _, exists := b.mutation.OpType(); exists {
				s.SetIgnore(itemnonce.FieldOpType)
			}
			if _, exists := b.mutation.CreateAtUnix(); exists {
				s.SetIgnore(itemnonce.FieldCreateAtUnix)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ItemNonce.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ItemNonceUpsertBulk) Ignore() *ItemNonceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ItemNonceUpsertBulk) DoNothing() *ItemNonceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ItemNonceCreateBulk.OnConflict
// documentation for more info.
func (u *ItemNonceUpsertBulk) Update(set func(*ItemNonceUpsert)) *ItemNonceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ItemNonceUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *ItemNonceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ItemNonceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ItemNonceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ItemNonceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
