// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/2comjie/taoxi-server/app/Api/items/internal/store/ent/item"
)

// ItemCreate is the builder for creating a Item entity.
type ItemCreate struct {
	config
	mutation *ItemMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUID sets the "uid" field.
func (_c *ItemCreate) SetUID(v uint64) *ItemCreate {
	_c.mutation.SetUID(v)
	return _c
}

// SetItemID sets the "item_id" field.
func (_c *ItemCreate) SetItemID(v int32) *ItemCreate {
	_c.mutation.SetItemID(v)
	return _c
}

// SetCount sets the "count" field.
func (_c *ItemCreate) SetCount(v int64) *ItemCreate {
	_c.mutation.SetCount(v)
	return _c
}

// SetUsedCount sets the "used_count" field.
func (_c *ItemCreate) SetUsedCount(v int64) *ItemCreate {
	_c.mutation.SetUsedCount(v)
	return _c
}

// SetNillableUsedCount sets the "used_count" field if the given value is not nil.
func (_c *ItemCreate) SetNillableUsedCount(v *int64) *ItemCreate {
	if v != nil {
		_c.SetUsedCount(*v)
	}
	return _c
}

// SetExpireAtUnix sets the "expire_at_unix" field.
func (_c *ItemCreate) SetExpireAtUnix(v int64) *ItemCreate {
	_c.mutation.SetExpireAtUnix(v)
	return _c
}

// SetNillableExpireAtUnix sets the "expire_at_unix" field if the given value is not nil.
func (_c *ItemCreate) SetNillableExpireAtUnix(v *int64) *ItemCreate {
	if v != nil {
		_c.SetExpireAtUnix(*v)
	}
	return _c
}

// SetSource sets the "source" field.
func (_c *ItemCreate) SetSource(v string) *ItemCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *ItemCreate) SetNillableSource(v *string) *ItemCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetCreateAtUnix sets the "create_at_unix" field.
func (_c *ItemCreate) SetCreateAtUnix(v int64) *ItemCreate {
	_c.mutation.SetCreateAtUnix(v)
	return _c
}

// SetNillableCreateAtUnix sets the "create_at_unix" field if the given value is not nil.
func (_c *ItemCreate) SetNillableCreateAtUnix(v *int64) *ItemCreate {
	if v != nil {
		_c.SetCreateAtUnix(*v)
	}
	return _c
}

// SetUpdateAtUnix sets the "update_at_unix" field.
func (_c *ItemCreate) SetUpdateAtUnix(v int64) *ItemCreate {
	_c.mutation.SetUpdateAtUnix(v)
	return _c
}

// SetNillableUpdateAtUnix sets the "update_at_unix" field if the given value is not nil.
func (_c *ItemCreate) SetNillableUpdateAtUnix(v *int64) *ItemCreate {
	if v != nil {
		_c.SetUpdateAtUnix(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ItemCreate) SetID(v int64) *ItemCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ItemMutation object of the builder.
func (_c *ItemCreate) Mutation() *ItemMutation {
	return _c.mutation
}

// Save creates the Item in the database.
func (_c *ItemCreate) Save(ctx context.Context) (*Item, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ItemCreate) SaveX(ctx context.Context) *Item {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ItemCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ItemCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ItemCreate) defaults() {
	if _, ok := _c.mutation.UsedCount(); !ok {
		v := item.DefaultUsedCount
		_c.mutation.SetUsedCount(v)
	}
	if _, ok := _c.mutation.ExpireAtUnix(); !ok {
		v := item.DefaultExpireAtUnix
		_c.mutation.SetExpireAtUnix(v)
	}
	if _, ok := _c.mutation.Source(); !ok {
		v := item.DefaultSource
		_c.mutation.SetSource(v)
	}
	if _, ok := _c.mutation.CreateAtUnix(); !ok {
		v := item.DefaultCreateAtUnix()
		_c.mutation.SetCreateAtUnix(v)
	}
	if _, ok := _c.mutation.UpdateAtUnix(); !ok {
		v := item.DefaultUpdateAtUnix()
		_c.mutation.SetUpdateAtUnix(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ItemCreate) check() error {
	if _, ok := _c.mutation.UID(); !ok {
		return &ValidationError{Name: "uid", err: errors.New(`ent: missing required field "Item.uid"`)}
	}
	if _, ok := _c.mutation.ItemID(); !ok {
		return &ValidationError{Name: "item_id", err: errors.New(`ent: missing required field "Item.item_id"`)}
	}
	if _, ok := _c.mutation.Count(); !ok {
		return &ValidationError{Name: "count", err: errors.New(`ent: missing required field "Item.count"`)}
	}
	if v, ok := _c.mutation.Count(); ok {
		if err := item.CountValidator(v); err != nil {
			return &ValidationError{Name: "count", err: fmt.Errorf(`ent: validator failed for field "Item.count": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UsedCount(); !ok {
		return &ValidationError{Name: "used_count", err: errors.New(`ent: missing required field "Item.used_count"`)}
	}
	if v, ok := _c.mutation.UsedCount(); ok {
		if err := item.UsedCountValidator(v); err != nil {
			return &ValidationError{Name: "used_count", err: fmt.Errorf(`ent: validator failed for field "Item.used_count": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpireAtUnix(); !ok {
		return &ValidationError{Name: "expire_at_unix", err: errors.New(`ent: missing required field "Item.expire_at_unix"`)}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "Item.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := item.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "Item.source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreateAtUnix(); !ok {
		return &ValidationError{Name: "create_at_unix", err: errors.New(`ent: missing required field "Item.create_at_unix"`)}
	}
	if _, ok := _c.mutation.UpdateAtUnix(); !ok {
		return &ValidationError{Name: "update_at_unix", err: errors.New(`ent: missing required field "Item.update_at_unix"`)}
	}
	return nil
}

func (_c *ItemCreate) sqlSave(ctx context.Context) (*Item, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ItemCreate) createSpec() (*Item, *sqlgraph.CreateSpec) {
	var (
		_node = &Item{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(item.Table, sqlgraph.NewFieldSpec(item.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.UID(); ok {
		_spec.SetField(item.FieldUID, field.TypeUint64, value)
		_node.UID = value
	}
	if value, ok := _c.mutation.ItemID(); ok {
		_spec.SetField(item.FieldItemID, field.TypeInt32, value)
		_node.ItemID = value
	}
	if value, ok := _c.mutation.Count(); ok {
		_spec.SetField(item.FieldCount, field.TypeInt64, value)
		_node.Count = value
	}
	if value, ok := _c.mutation.UsedCount(); ok {
		_spec.SetField(item.FieldUsedCount, field.TypeInt64, value)
		_node.UsedCount = value
	}
	if value, ok := _c.mutation.ExpireAtUnix(); ok {
		_spec.SetField(item.FieldExpireAtUnix, field.TypeInt64, value)
		_node.ExpireAtUnix = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(item.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.CreateAtUnix(); ok {
		_spec.SetField(item.FieldCreateAtUnix, field.TypeInt64, value)
		_node.CreateAtUnix = value
	}
	if value, ok := _c.mutation.UpdateAtUnix(); ok {
		_spec.SetField(item.FieldUpdateAtUnix, field.TypeInt64, value)
		_node.UpdateAtUnix = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Item.Create().
//		SetUID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ItemUpsert) {
//			SetUID(v+v).
//		}).
//		Exec(ctx)
func (_c *ItemCreate) OnConflict(opts ...sql.ConflictOption) *ItemUpsertOne {
	_c.conflict = opts
	return &ItemUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Item.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ItemCreate) OnConflictColumns(columns ...string) *ItemUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ItemUpsertOne{
		create: _c,
	}
}

type (
	// ItemUpsertOne is the builder for "upsert"-ing
	//  one Item node.
	ItemUpsertOne struct {
		create *ItemCreate
	}

	// ItemUpsert is the "OnConflict" setter.
	ItemUpsert struct {
		*sql.UpdateSet
	}
)

// SetCount sets the "count" field.
func (u *ItemUpsert) SetCount(v int64) *ItemUpsert {
	u.Set(item.FieldCount, v)
	return u
}

// UpdateCount sets the "count" field to the value that was provided on create.
func (u *ItemUpsert) UpdateCount() *ItemUpsert {
	u.SetExcluded(item.FieldCount)
	return u
}

// AddCount adds v to the "count" field.
func (u *ItemUpsert) AddCount(v int64) *ItemUpsert {
	u.Add(item.FieldCount, v)
	return u
}

// SetUsedCount sets the "used_count" field.
func (u *ItemUpsert) SetUsedCount(v int64) *ItemUpsert {
	u.Set(item.FieldUsedCount, v)
	return u
}

// UpdateUsedCount sets the "used_count" field to the value that was provided on create.
func (u *ItemUpsert) UpdateUsedCount() *ItemUpsert {
	u.SetExcluded(item.FieldUsedCount)
	return u
}

// AddUsedCount adds v to the "used_count" field.
func (u *ItemUpsert) AddUsedCount(v int64) *ItemUpsert {
	u.Add(item.FieldUsedCount, v)
	return u
}

// SetExpireAtUnix sets the "expire_at_unix" field.
func (u *ItemUpsert) SetExpireAtUnix(v int64) *ItemUpsert {
	u.Set(item.FieldExpireAtUnix, v)
	return u
}

// UpdateExpireAtUnix sets the "expire_at_unix" field to the value that was provided on create.
func (u *ItemUpsert) UpdateExpireAtUnix() *ItemUpsert {
	u.SetExcluded(item.FieldExpireAtUnix)
	return u
}

// AddExpireAtUnix adds v to the "expire_at_unix" field.
func (u *ItemUpsert) AddExpireAtUnix(v int64) *ItemUpsert {
	u.Add(item.FieldExpireAtUnix, v)
	return u
}

// SetUpdateAtUnix sets the "update_at_unix" field.
func (u *ItemUpsert) SetUpdateAtUnix(v int64) *ItemUpsert {
	u.Set(item.FieldUpdateAtUnix, v)
	return u
}

// UpdateUpdateAtUnix sets the "update_at_unix" field to the value that was provided on create.
func (u *ItemUpsert) UpdateUpdateAtUnix() *ItemUpsert {
	u.SetExcluded(item.FieldUpdateAtUnix)
	return u
}

// AddUpdateAtUnix adds v to the "update_at_unix" field.
func (u *ItemUpsert) AddUpdateAtUnix(v int64) *ItemUpsert {
	u.Add(item.FieldUpdateAtUnix, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Item.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(item.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ItemUpsertOne) UpdateNewValues() *ItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(item.FieldID)
		}
		if _, exists := u.create.mutation.UID(); exists {
			s.SetIgnore(item.FieldUID)
		}
		if _, exists := u.create.mutation.ItemID(); exists {
			s.SetIgnore(item.FieldItemID)
		}
		if _, exists := u.create.mutation.Source(); exists {
			s.SetIgnore(item.FieldSource)
		}
		if _, exists := u.create.mutation.CreateAtUnix(); exists {
			s.SetIgnore(item.FieldCreateAtUnix)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Item.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ItemUpsertOne) Ignore() *ItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ItemUpsertOne) DoNothing() *ItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ItemCreate.OnConflict
// documentation for more info.
func (u *ItemUpsertOne) Update(set func(*ItemUpsert)) *ItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ItemUpsert{UpdateSet: update})
	}))
	return u
}

// SetCount sets the "count" field.
func (u *ItemUpsertOne) SetCount(v int64) *ItemUpsertOne {
	return u.Update(func(s *ItemUpsert) {
		s.SetCount(v)
	})
}

// AddCount adds v to the "count" field.
func (u *ItemUpsertOne) AddCount(v int64) *ItemUpsertOne {
	return u.Update(func(s *ItemUpsert) {
		s.AddCount(v)
	})
}

// UpdateCount sets the "count" field to the value that was provided on create.
func (u *ItemUpsertOne) UpdateCount() *ItemUpsertOne {
	return u.Update(func(s *ItemUpsert) {
		s.UpdateCount()
	})
}

// SetUsedCount sets the "used_count" field.
func (u *ItemUpsertOne) SetUsedCount(v int64) *ItemUpsertOne {
	return u.Update(func(s *ItemUpsert) {
		s.SetUsedCount(v)
	})
}

// AddUsedCount adds v to the "used_count" field.
func (u *ItemUpsertOne) AddUsedCount(v int64) *ItemUpsertOne {
	return u.Update(func(s *ItemUpsert) {
		s.AddUsedCount(v)
	})
}

// UpdateUsedCount sets the "used_count" field to the value that was provided on create.
func (u *ItemUpsertOne) UpdateUsedCount() *ItemUpsertOne {
	return u.Update(func(s *ItemUpsert) {
		s.UpdateUsedCount()
	})
}

// SetExpireAtUnix sets the "expire_at_unix" field.
func (u *ItemUpsertOne) SetExpireAtUnix(v int64) *ItemUpsertOne {
	return u.Update(func(s *ItemUpsert) {
		s.SetExpireAtUnix(v)
	})
}

// AddExpireAtUnix adds v to the "expire_at_unix" field.
func (u *ItemUpsertOne) AddExpireAtUnix(v int64) *ItemUpsertOne {
	return u.Update(func(s *ItemUpsert) {
		s.AddExpireAtUnix(v)
	})
}

// UpdateExpireAtUnix sets the "expire_at_unix" field to the value that was provided on create.
func (u *ItemUpsertOne) UpdateExpireAtUnix() *ItemUpsertOne {
	return u.Update(func(s *ItemUpsert) {
		s.UpdateExpireAtUnix()
	})
}

// SetUpdateAtUnix sets the "update_at_unix" field.
func (u *ItemUpsertOne) SetUpdateAtUnix(v int64) *ItemUpsertOne {
	return u.Update(func(s *ItemUpsert) {
		s.SetUpdateAtUnix(v)
	})
}

// AddUpdateAtUnix adds v to the "update_at_unix" field.
func (u *ItemUpsertOne) AddUpdateAtUnix(v int64) *ItemUpsertOne {
	return u.Update(func(s *ItemUpsert) {
		s.AddUpdateAtUnix(v)
	})
}

// UpdateUpdateAtUnix sets the "update_at_unix" field to the value that was provided on create.
func (u *ItemUpsertOne) UpdateUpdateAtUnix() *ItemUpsertOne {
	return u.Update(func(s *ItemUpsert) {
		s.UpdateUpdateAtUnix()
	})
}

// Exec executes the query.
func (u *ItemUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ItemCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ItemUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ItemUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ItemUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ItemCreateBulk is the builder for creating many Item entities in bulk.
type ItemCreateBulk struct {
	config
	err      error
	builders []*ItemCreate
	conflict []sql.ConflictOption
}

// Save creates the Item entities in the database.
func (_c *ItemCreateBulk) Save(ctx context.Context) ([]*Item, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Item, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ItemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ItemCreateBulk) SaveX(ctx context.Context) []*Item {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ItemCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ItemCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Item.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ItemUpsert) {
//			SetUID(v+v).
//		}).
//		Exec(ctx)
func (_c *ItemCreateBulk) OnConflict(opts ...sql.ConflictOption) *ItemUpsertBulk {
	_c.conflict = opts
	return &ItemUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Item.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ItemCreateBulk) OnConflictColumns(columns ...string) *ItemUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ItemUpsertBulk{
		create: _c,
	}
}

// ItemUpsertBulk is the builder for "upsert"-ing
// a bulk of Item nodes.
type ItemUpsertBulk struct {
	create *ItemCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Item.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(item.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ItemUpsertBulk) UpdateNewValues() *ItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(item.FieldID)
			}
			if _, exists := b.mutation.UID(); exists {
				s.SetIgnore(item.FieldUID)
			}
			if _, exists := b.mutation.ItemID(); exists {
				s.SetIgnore(item.FieldItemID)
			}
			if _, exists := b.mutation.Source(); exists {
				s.SetIgnore(item.FieldSource)
			}
			if _, exists := b.mutation.CreateAtUnix(); exists {
				s.SetIgnore(item.FieldCreateAtUnix)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Item.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ItemUpsertBulk) Ignore() *ItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ItemUpsertBulk) DoNothing() *ItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ItemCreateBulk.OnConflict
// documentation for more info.
func (u *ItemUpsertBulk) Update(set func(*ItemUpsert)) *ItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ItemUpsert{UpdateSet: update})
	}))
	return u
}

// SetCount sets the "count" field.
func (u *ItemUpsertBulk) SetCount(v int64) *ItemUpsertBulk {
	return u.Update(func(s *ItemUpsert) {
		s.SetCount(v)
	})
}

// AddCount adds v to the "count" field.
func (u *ItemUpsertBulk) AddCount(v int64) *ItemUpsertBulk {
	return u.Update(func(s *ItemUpsert) {
		s.AddCount(v)
	})
}

// UpdateCount sets the "count" field to the value that was provided on create.
func (u *ItemUpsertBulk) UpdateCount() *ItemUpsertBulk {
	return u.Update(func(s *ItemUpsert) {
		s.UpdateCount()
	})
}

// SetUsedCount sets the "used_count" field.
func (u *ItemUpsertBulk) SetUsedCount(v int64) *ItemUpsertBulk {
	return u.Update(func(s *ItemUpsert) {
		s.SetUsedCount(v)
	})
}

// AddUsedCount adds v to the "used_count" field.
func (u *ItemUpsertBulk) AddUsedCount(v int64) *ItemUpsertBulk {
	return u.Update(func(s *ItemUpsert) {
		s.AddUsedCount(v)
	})
}

// UpdateUsedCount sets the "used_count" field to the value that was provided on create.
func (u *ItemUpsertBulk) UpdateUsedCount() *ItemUpsertBulk {
	return u.Update(func(s *ItemUpsert) {
		s.UpdateUsedCount()
	})
}

// SetExpireAtUnix sets the "expire_at_unix" field.
func (u *ItemUpsertBulk) SetExpireAtUnix(v int64) *ItemUpsertBulk {
	return u.Update(func(s *ItemUpsert) {
		s.SetExpireAtUnix(v)
	})
}

// AddExpireAtUnix adds v to the "expire_at_unix" field.
func (u *ItemUpsertBulk) AddExpireAtUnix(v int64) *ItemUpsertBulk {
	return u.Update(func(s *ItemUpsert) {
		s.AddExpireAtUnix(v)
	})
}

// UpdateExpireAtUnix sets the "expire_at_unix" field to the value that was provided on create.
func (u *ItemUpsertBulk) UpdateExpireAtUnix() *ItemUpsertBulk {
	return u.Update(func(s *ItemUpsert) {
		s.UpdateExpireAtUnix()
	})
}

// SetUpdateAtUnix sets the "update_at_unix" field.
func (u *ItemUpsertBulk) SetUpdateAtUnix(v int64) *ItemUpsertBulk {
	return u.Update(func(s *ItemUpsert) {
		s.SetUpdateAtUnix(v)
	})
}

// AddUpdateAtUnix adds v to the "update_at_unix" field.
func (u *ItemUpsertBulk) AddUpdateAtUnix(v int64) *ItemUpsertBulk {
	return u.Update(func(s *ItemUpsert) {
		s.AddUpdateAtUnix(v)
	})
}

// UpdateUpdateAtUnix sets the "update_at_unix" field to the value that was provided on create.
func (u *ItemUpsertBulk) UpdateUpdateAtUnix() *ItemUpsertBulk {
	return u.Update(func(s *ItemUpsert) {
		s.UpdateUpdateAtUnix()
	})
}

// Exec executes the query.
func (u *ItemUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ItemCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ItemCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ItemUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
