// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/2comjie/taoxi-server/app/Api/items/internal/store/ent/item"
	"github.com/2comjie/taoxi-server/app/Api/items/internal/store/ent/itemnonce"
	"github.com/2comjie/taoxi-server/app/Api/items/internal/store/ent/predicate"
	itemTypes "github.com/2comjie/taoxi-server/app/Api/items/types"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeItem         = "Item"
	TypeItemNonce    = "ItemNonce"
	TypeItemUserLock = "ItemUserLock"
)

// ItemMutation represents an operation that mutates the Item nodes in the graph.
type ItemMutation struct {
	config
	op                Op
	typ               string
	id                *int64
	uid               *uint64
	adduid            *int64
	item_id           *int32
	additem_id        *int32
	count             *int64
	addcount          *int64
	used_count        *int64
	addused_count     *int64
	expire_at_unix    *int64
	addexpire_at_unix *int64
	source            *string
	create_at_unix    *int64
	addcreate_at_unix *int64
	update_at_unix    *int64
	addupdate_at_unix *int64
	clearedFields     map[string]struct{}
	done              bool
	oldValue          func(context.Context) (*Item, error)
	predicates        []predicate.Item
}

var _ ent.Mutation = (*ItemMutation)(nil)

// itemOption allows management of the mutation configuration using functional options.
type itemOption func(*ItemMutation)

// newItemMutation creates new mutation for the Item entity.
func newItemMutation(c config, op Op, opts ...itemOption) *ItemMutation {
	m := &ItemMutation{
		config:        c,
		op:            op,
		typ:           TypeItem,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withItemID sets the ID field of the mutation.
func withItemID(id int64) itemOption {
	return func(m *ItemMutation) {
		var (
			err   error
			once  sync.Once
			value *Item
		)
		m.oldValue = func(ctx context.Context) (*Item, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Item.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withItem sets the old Item of the mutation.
func withItem(node *Item) itemOption {
	return func(m *ItemMutation) {
		m.oldValue = func(context.Context) (*Item, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ItemMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ItemMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Item entities.
func (m *ItemMutation) SetID(id int64) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ItemMutation) ID() (id int64, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ItemMutation) IDs(ctx context.Context) ([]int64, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int64{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Item.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetUID sets the "uid" field.
func (m *ItemMutation) SetUID(u uint64) {
	m.uid = &u
	m.adduid = nil
}

// UID returns the value of the "uid" field in the mutation.
func (m *ItemMutation) UID() (r uint64, exists bool) {
	v := m.uid
	if v == nil {
		return
	}
	return *v, true
}

// OldUID returns the old "uid" field's value of the Item entity.
// If the Item object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ItemMutation) OldUID(ctx context.Context) (v uint64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUID: %w", err)
	}
	return oldValue.UID, nil
}

// AddUID adds u to the "uid" field.
func (m *ItemMutation) AddUID(u int64) {
	if m.adduid != nil {
		*m.adduid += u
	} else {
		m.adduid = &u
	}
}

// AddedUID returns the value that was added to the "uid" field in this mutation.
func (m *ItemMutation) AddedUID() (r int64, exists bool) {
	v := m.adduid
	if v == nil {
		return
	}
	return *v, true
}

// ResetUID resets all changes to the "uid" field.
func (m *ItemMutation) ResetUID() {
	m.uid = nil
	m.adduid = nil
}

// SetItemID sets the "item_id" field.
func (m *ItemMutation) SetItemID(i int32) {
	m.item_id = &i
	m.additem_id = nil
}

// ItemID returns the value of the "item_id" field in the mutation.
func (m *ItemMutation) ItemID() (r int32, exists bool) {
	v := m.item_id
	if v == nil {
		return
	}
	return *v, true
}

// OldItemID returns the old "item_id" field's value of the Item entity.
// If the Item object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ItemMutation) OldItemID(ctx context.Context) (v int32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldItemID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldItemID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldItemID: %w", err)
	}
	return oldValue.ItemID, nil
}

// AddItemID adds i to the "item_id" field.
func (m *ItemMutation) AddItemID(i int32) {
	if m.additem_id != nil {
		*m.additem_id += i
	} else {
		m.additem_id = &i
	}
}

// AddedItemID returns the value that was added to the "item_id" field in this mutation.
func (m *ItemMutation) AddedItemID() (r int32, exists bool) {
	v := m.additem_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetItemID resets all changes to the "item_id" field.
func (m *ItemMutation) ResetItemID() {
	m.item_id = nil
	m.additem_id = nil
}

// SetCount sets the "count" field.
func (m *ItemMutation) SetCount(i int64) {
	m.count = &i
	m.addcount = nil
}

// Count returns the value of the "count" field in the mutation.
func (m *ItemMutation) Count() (r int64, exists bool) {
	v := m.count
	if v == nil {
		return
	}
	return *v, true
}

// OldCount returns the old "count" field's value of the Item entity.
// If the Item object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ItemMutation) OldCount(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCount is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCount requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCount: %w", err)
	}
	return oldValue.Count, nil
}

// AddCount adds i to the "count" field.
func (m *ItemMutation) AddCount(i int64) {
	if m.addcount != nil {
		*m.addcount += i
	} else {
		m.addcount = &i
	}
}

// AddedCount returns the value that was added to the "count" field in this mutation.
func (m *ItemMutation) AddedCount() (r int64, exists bool) {
	v := m.addcount
	if v == nil {
		return
	}
	return *v, true
}

// ResetCount resets all changes to the "count" field.
func (m *ItemMutation) ResetCount() {
	m.count = nil
	m.addcount = nil
}

// SetUsedCount sets the "used_count" field.
func (m *ItemMutation) SetUsedCount(i int64) {
	m.used_count = &i
	m.addused_count = nil
}

// UsedCount returns the value of the "used_count" field in the mutation.
func (m *ItemMutation) UsedCount() (r int64, exists bool) {
	v := m.used_count
	if v == nil {
		return
	}
	return *v, true
}

// OldUsedCount returns the old "used_count" field's value of the Item entity.
// If the Item object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ItemMutation) OldUsedCount(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUsedCount is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUsedCount requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUsedCount: %w", err)
	}
	return oldValue.UsedCount, nil
}

// AddUsedCount adds i to the "used_count" field.
func (m *ItemMutation) AddUsedCount(i int64) {
	if m.addused_count != nil {
		*m.addused_count += i
	} else {
		m.addused_count = &i
	}
}

// AddedUsedCount returns the value that was added to the "used_count" field in this mutation.
func (m *ItemMutation) AddedUsedCount() (r int64, exists bool) {
	v := m.addused_count
	if v == nil {
		return
	}
	return *v, true
}

// ResetUsedCount resets all changes to the "used_count" field.
func (m *ItemMutation) ResetUsedCount() {
	m.used_count = nil
	m.addused_count = nil
}

// SetExpireAtUnix sets the "expire_at_unix" field.
func (m *ItemMutation) SetExpireAtUnix(i int64) {
	m.expire_at_unix = &i
	m.addexpire_at_unix = nil
}

// ExpireAtUnix returns the value of the "expire_at_unix" field in the mutation.
func (m *ItemMutation) ExpireAtUnix() (r int64, exists bool) {
	v := m.expire_at_unix
	if v == nil {
		return
	}
	return *v, true
}

// OldExpireAtUnix returns the old "expire_at_unix" field's value of the Item entity.
// If the Item object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ItemMutation) OldExpireAtUnix(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldExpireAtUnix is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldExpireAtUnix requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldExpireAtUnix: %w", err)
	}
	return oldValue.ExpireAtUnix, nil
}

// AddExpireAtUnix adds i to the "expire_at_unix" field.
func (m *ItemMutation) AddExpireAtUnix(i int64) {
	if m.addexpire_at_unix != nil {
		*m.addexpire_at_unix += i
	} else {
		m.addexpire_at_unix = &i
	}
}

// AddedExpireAtUnix returns the value that was added to the "expire_at_unix" field in this mutation.
func (m *ItemMutation) AddedExpireAtUnix() (r int64, exists bool) {
	v := m.addexpire_at_unix
	if v == nil {
		return
	}
	return *v, true
}

// ResetExpireAtUnix resets all changes to the "expire_at_unix" field.
func (m *ItemMutation) ResetExpireAtUnix() {
	m.expire_at_unix = nil
	m.addexpire_at_unix = nil
}

// SetSource sets the "source" field.
func (m *ItemMutation) SetSource(s string) {
	m.source = &s
}

// Source returns the value of the "source" field in the mutation.
func (m *ItemMutation) Source() (r string, exists bool) {
	v := m.source
	if v == nil {
		return
	}
	return *v, true
}

// OldSource returns the old "source" field's value of the Item entity.
// If the Item object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ItemMutation) OldSource(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSource is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSource requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSource: %w", err)
	}
	return oldValue.Source, nil
}

// ResetSource resets all changes to the "source" field.
func (m *ItemMutation) ResetSource() {
	m.source = nil
}

// SetCreateAtUnix sets the "create_at_unix" field.
func (m *ItemMutation) SetCreateAtUnix(i int64) {
	m.create_at_unix = &i
	m.addcreate_at_unix = nil
}

// CreateAtUnix returns the value of the "create_at_unix" field in the mutation.
func (m *ItemMutation) CreateAtUnix() (r int64, exists bool) {
	v := m.create_at_unix
	if v == nil {
		return
	}
	return *v, true
}

// OldCreateAtUnix returns the old "create_at_unix" field's value of the Item entity.
// If the Item object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ItemMutation) OldCreateAtUnix(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreateAtUnix is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreateAtUnix requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreateAtUnix: %w", err)
	}
	return oldValue.CreateAtUnix, nil
}

// AddCreateAtUnix adds i to the "create_at_unix" field.
func (m *ItemMutation) AddCreateAtUnix(i int64) {
	if m.addcreate_at_unix != nil {
		*m.addcreate_at_unix += i
	} else {
		m.addcreate_at_unix = &i
	}
}

// AddedCreateAtUnix returns the value that was added to the "create_at_unix" field in this mutation.
func (m *ItemMutation) AddedCreateAtUnix() (r int64, exists bool) {
	v := m.addcreate_at_unix
	if v == nil {
		return
	}
	return *v, true
}

// ResetCreateAtUnix resets all changes to the "create_at_unix" field.
func (m *ItemMutation) ResetCreateAtUnix() {
	m.create_at_unix = nil
	m.addcreate_at_unix = nil
}

// SetUpdateAtUnix sets the "update_at_unix" field.
func (m *ItemMutation) SetUpdateAtUnix(i int64) {
	m.update_at_unix = &i
	m.addupdate_at_unix = nil
}

// UpdateAtUnix returns the value of the "update_at_unix" field in the mutation.
func (m *ItemMutation) UpdateAtUnix() (r int64, exists bool) {
	v := m.update_at_unix
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdateAtUnix returns the old "update_at_unix" field's value of the Item entity.
// If the Item object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ItemMutation) OldUpdateAtUnix(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdateAtUnix is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdateAtUnix requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdateAtUnix: %w", err)
	}
	return oldValue.UpdateAtUnix, nil
}

// AddUpdateAtUnix adds i to the "update_at_unix" field.
func (m *ItemMutation) AddUpdateAtUnix(i int64) {
	if m.addupdate_at_unix != nil {
		*m.addupdate_at_unix += i
	} else {
		m.addupdate_at_unix = &i
	}
}

// AddedUpdateAtUnix returns the value that was added to the "update_at_unix" field in this mutation.
func (m *ItemMutation) AddedUpdateAtUnix() (r int64, exists bool) {
	v := m.addupdate_at_unix
	if v == nil {
		return
	}
	return *v, true
}

// ResetUpdateAtUnix resets all changes to the "update_at_unix" field.
func (m *ItemMutation) ResetUpdateAtUnix() {
	m.update_at_unix = nil
	m.addupdate_at_unix = nil
}

// Where appends a list predicates to the ItemMutation builder.
func (m *ItemMutation) Where(ps ...predicate.Item) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the ItemMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *ItemMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Item, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *ItemMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *ItemMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Item).
func (m *ItemMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ItemMutation) Fields() []string {
	fields := make([]string, 0, 8)
	if m.uid != nil {
		fields = append(fields, item.FieldUID)
	}
	if m.item_id != nil {
		fields = append(fields, item.FieldItemID)
	}
	if m.count != nil {
		fields = append(fields, item.FieldCount)
	}
	if m.used_count != nil {
		fields = append(fields, item.FieldUsedCount)
	}
	if m.expire_at_unix != nil {
		fields = append(fields, item.FieldExpireAtUnix)
	}
	if m.source != nil {
		fields = append(fields, item.FieldSource)
	}
	if m.create_at_unix != nil {
		fields = append(fields, item.FieldCreateAtUnix)
	}
	if m.update_at_unix != nil {
		fields = append(fields, item.FieldUpdateAtUnix)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ItemMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case item.FieldUID:
		return m.UID()
	case item.FieldItemID:
		return m.ItemID()
	case item.FieldCount:
		return m.Count()
	case item.FieldUsedCount:
		return m.UsedCount()
	case item.FieldExpireAtUnix:
		return m.ExpireAtUnix()
	case item.FieldSource:
		return m.Source()
	case item.FieldCreateAtUnix:
		return m.CreateAtUnix()
	case item.FieldUpdateAtUnix:
		return m.UpdateAtUnix()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ItemMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case item.FieldUID:
		return m.OldUID(ctx)
	case item.FieldItemID:
		return m.OldItemID(ctx)
	case item.FieldCount:
		return m.OldCount(ctx)
	case item.FieldUsedCount:
		return m.OldUsedCount(ctx)
	case item.FieldExpireAtUnix:
		return m.OldExpireAtUnix(ctx)
	case item.FieldSource:
		return m.OldSource(ctx)
	case item.FieldCreateAtUnix:
		return m.OldCreateAtUnix(ctx)
	case item.FieldUpdateAtUnix:
		return m.OldUpdateAtUnix(ctx)
	}
	return nil, fmt.Errorf("unknown Item field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ItemMutation) SetField(name string, value ent.Value) error {
	switch name {
	case item.FieldUID:
		v, ok := value.(uint64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUID(v)
		return nil
	case item.FieldItemID:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetItemID(v)
		return nil
	case item.FieldCount:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCount(v)
		return nil
	case item.FieldUsedCount:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUsedCount(v)
		return nil
	case item.FieldExpireAtUnix:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetExpireAtUnix(v)
		return nil
	case item.FieldSource:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSource(v)
		return nil
	case item.FieldCreateAtUnix:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreateAtUnix(v)
		return nil
	case item.FieldUpdateAtUnix:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdateAtUnix(v)
		return nil
	}
	return fmt.Errorf("unknown Item field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ItemMutation) AddedFields() []string {
	var fields []string
	if m.adduid != nil {
		fields = append(fields, item.FieldUID)
	}
	if m.additem_id != nil {
		fields = append(fields, item.FieldItemID)
	}
	if m.addcount != nil {
		fields = append(fields, item.FieldCount)
	}
	if m.addused_count != nil {
		fields = append(fields, item.FieldUsedCount)
	}
	if m.addexpire_at_unix != nil {
		fields = append(fields, item.FieldExpireAtUnix)
	}
	if m.addcreate_at_unix != nil {
		fields = append(fields, item.FieldCreateAtUnix)
	}
	if m.addupdate_at_unix != nil {
		fields = append(fields, item.FieldUpdateAtUnix)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ItemMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case item.FieldUID:
		return m.AddedUID()
	case item.FieldItemID:
		return m.AddedItemID()
	case item.FieldCount:
		return m.AddedCount()
	case item.FieldUsedCount:
		return m.AddedUsedCount()
	case item.FieldExpireAtUnix:
		return m.AddedExpireAtUnix()
	case item.FieldCreateAtUnix:
		return m.AddedCreateAtUnix()
	case item.FieldUpdateAtUnix:
		return m.AddedUpdateAtUnix()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ItemMutation) AddField(name string, value ent.Value) error {
	switch name {
	case item.FieldUID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddUID(v)
		return nil
	case item.FieldItemID:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddItemID(v)
		return nil
	case item.FieldCount:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddCount(v)
		return nil
	case item.FieldUsedCount:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddUsedCount(v)
		return nil
	case item.FieldExpireAtUnix:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddExpireAtUnix(v)
		return nil
	case item.FieldCreateAtUnix:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddCreateAtUnix(v)
		return nil
	case item.FieldUpdateAtUnix:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddUpdateAtUnix(v)
		return nil
	}
	return fmt.Errorf("unknown Item numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ItemMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ItemMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ItemMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Item nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ItemMutation) ResetField(name string) error {
	switch name {
	case item.FieldUID:
		m.ResetUID()
		return nil
	case item.FieldItemID:
		m.ResetItemID()
		return nil
	case item.FieldCount:
		m.ResetCount()
		return nil
	case item.FieldUsedCount:
		m.ResetUsedCount()
		return nil
	case item.FieldExpireAtUnix:
		m.ResetExpireAtUnix()
		return nil
	case item.FieldSource:
		m.ResetSource()
		return nil
	case item.FieldCreateAtUnix:
		m.ResetCreateAtUnix()
		return nil
	case item.FieldUpdateAtUnix:
		m.ResetUpdateAtUnix()
		return nil
	}
	return fmt.Errorf("unknown Item field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ItemMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ItemMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ItemMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ItemMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ItemMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ItemMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ItemMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Item unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ItemMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Item edge %s", name)
}

// ItemNonceMutation represents an operation that mutates the ItemNonce nodes in the graph.
type ItemNonceMutation struct {
	config
	op                Op
	typ               string
	id                *uint64
	uid               *uint64
	adduid            *int64
	nonce             *string
	op_type           *itemTypes.OperationType
	addop_type        *itemTypes.OperationType
	create_at_unix    *int64
	addcreate_at_unix *int64
	clearedFields     map[string]struct{}
	done              bool
	oldValue          func(context.Context) (*ItemNonce, error)
	predicates        []predicate.ItemNonce
}

var _ ent.Mutation = (*ItemNonceMutation)(nil)

// itemnonceOption allows management of the mutation configuration using functional options.
type itemnonceOption func(*ItemNonceMutation)

// newItemNonceMutation creates new mutation for the ItemNonce entity.
func newItemNonceMutation(c config, op Op, opts ...itemnonceOption) *ItemNonceMutation {
	m := &ItemNonceMutation{
		config:        c,
		op:            op,
		typ:           TypeItemNonce,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withItemNonceID sets the ID field of the mutation.
func withItemNonceID(id uint64) itemnonceOption {
	return func(m *ItemNonceMutation) {
		var (
			err   error
			once  sync.Once
			value *ItemNonce
		)
		m.oldValue = func(ctx context.Context) (*ItemNonce, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().ItemNonce.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withItemNonce sets the old ItemNonce of the mutation.
func withItemNonce(node *ItemNonce) itemnonceOption {
	return func(m *ItemNonceMutation) {
		m.oldValue = func(context.Context) (*ItemNonce, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ItemNonceMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ItemNonceMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of ItemNonce entities.
func (m *ItemNonceMutation) SetID(id uint64) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ItemNonceMutation) ID() (id uint64, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ItemNonceMutation) IDs(ctx context.Context) ([]uint64, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uint64{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().ItemNonce.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetUID sets the "uid" field.
func (m *ItemNonceMutation) SetUID(u uint64) {
	m.uid = &u
	m.adduid = nil
}

// UID returns the value of the "uid" field in the mutation.
func (m *ItemNonceMutation) UID() (r uint64, exists bool) {
	v := m.uid
	if v == nil {
		return
	}
	return *v, true
}

// OldUID returns the old "uid" field's value of the ItemNonce entity.
// If the ItemNonce object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ItemNonceMutation) OldUID(ctx context.Context) (v uint64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUID: %w", err)
	}
	return oldValue.UID, nil
}

// AddUID adds u to the "uid" field.
func (m *ItemNonceMutation) AddUID(u int64) {
	if m.adduid != nil {
		*m.adduid += u
	} else {
		m.adduid = &u
	}
}

// AddedUID returns the value that was added to the "uid" field in this mutation.
func (m *ItemNonceMutation) AddedUID() (r int64, exists bool) {
	v := m.adduid
	if v == nil {
		return
	}
	return *v, true
}

// ResetUID resets all changes to the "uid" field.
func (m *ItemNonceMutation) ResetUID() {
	m.uid = nil
	m.adduid = nil
}

// SetNonce sets the "nonce" field.
func (m *ItemNonceMutation) SetNonce(s string) {
	m.nonce = &s
}

// Nonce returns the value of the "nonce" field in the mutation.
func (m *ItemNonceMutation) Nonce() (r string, exists bool) {
	v := m.nonce
	if v == nil {
		return
	}
	return *v, true
}

// OldNonce returns the old "nonce" field's value of the ItemNonce entity.
// If the ItemNonce object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ItemNonceMutation) OldNonce(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldNonce is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldNonce requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldNonce: %w", err)
	}
	return oldValue.Nonce, nil
}

// ResetNonce resets all changes to the "nonce" field.
func (m *ItemNonceMutation) ResetNonce() {
	m.nonce = nil
}

// SetOpType sets the "op_type" field.
func (m *ItemNonceMutation) SetOpType(itt itemTypes.OperationType) {
	m.op_type = &itt
	m.addop_type = nil
}

// OpType returns the value of the "op_type" field in the mutation.
func (m *ItemNonceMutation) OpType() (r itemTypes.OperationType, exists bool) {
	v := m.op_type
	if v == nil {
		return
	}
	return *v, true
}

// OldOpType returns the old "op_type" field's value of the ItemNonce entity.
// If the ItemNonce object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ItemNonceMutation) OldOpType(ctx context.Context) (v itemTypes.OperationType, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOpType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOpType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOpType: %w", err)
	}
	return oldValue.OpType, nil
}

// AddOpType adds itt to the "op_type" field.
func (m *ItemNonceMutation) AddOpType(itt itemTypes.OperationType) {
	if m.addop_type != nil {
		*m.addop_type += itt
	} else {
		m.addop_type = &itt
	}
}

// AddedOpType returns the value that was added to the "op_type" field in this mutation.
func (m *ItemNonceMutation) AddedOpType() (r itemTypes.OperationType, exists bool) {
	v := m.addop_type
	if v == nil {
		return
	}
	return *v, true
}

// ResetOpType resets all changes to the "op_type" field.
func (m *ItemNonceMutation) ResetOpType() {
	m.op_type = nil
	m.addop_type = nil
}

// SetCreateAtUnix sets the "create_at_unix" field.
func (m *ItemNonceMutation) SetCreateAtUnix(i int64) {
	m.create_at_unix = &i
	m.addcreate_at_unix = nil
}

// CreateAtUnix returns the value of the "create_at_unix" field in the mutation.
func (m *ItemNonceMutation) CreateAtUnix() (r int64, exists bool) {
	v := m.create_at_unix
	if v == nil {
		return
	}
	return *v, true
}

// OldCreateAtUnix returns the old "create_at_unix" field's value of the ItemNonce entity.
// If the ItemNonce object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ItemNonceMutation) OldCreateAtUnix(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreateAtUnix is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreateAtUnix requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreateAtUnix: %w", err)
	}
	return oldValue.CreateAtUnix, nil
}

// AddCreateAtUnix adds i to the "create_at_unix" field.
func (m *ItemNonceMutation) AddCreateAtUnix(i int64) {
	if m.addcreate_at_unix != nil {
		*m.addcreate_at_unix += i
	} else {
		m.addcreate_at_unix = &i
	}
}

// AddedCreateAtUnix returns the value that was added to the "create_at_unix" field in this mutation.
func (m *ItemNonceMutation) AddedCreateAtUnix() (r int64, exists bool) {
	v := m.addcreate_at_unix
	if v == nil {
		return
	}
	return *v, true
}

// ResetCreateAtUnix resets all changes to the "create_at_unix" field.
func (m *ItemNonceMutation) ResetCreateAtUnix() {
	m.create_at_unix = nil
	m.addcreate_at_unix = nil
}

// Where appends a list predicates to the ItemNonceMutation builder.
func (m *ItemNonceMutation) Where(ps ...predicate.ItemNonce) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the ItemNonceMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *ItemNonceMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.ItemNonce, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *ItemNonceMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *ItemNonceMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (ItemNonce).
func (m *ItemNonceMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ItemNonceMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.uid != nil {
		fields = append(fields, itemnonce.FieldUID)
	}
	if m.nonce != nil {
		fields = append(fields, itemnonce.FieldNonce)
	}
	if m.op_type != nil {
		fields = append(fields, itemnonce.FieldOpType)
	}
	if m.create_at_unix != nil {
		fields = append(fields, itemnonce.FieldCreateAtUnix)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ItemNonceMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case itemnonce.FieldUID:
		return m.UID()
	case itemnonce.FieldNonce:
		return m.Nonce()
	case itemnonce.FieldOpType:
		return m.OpType()
	case itemnonce.FieldCreateAtUnix:
		return m.CreateAtUnix()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ItemNonceMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case itemnonce.FieldUID:
		return m.OldUID(ctx)
	case itemnonce.FieldNonce:
		return m.OldNonce(ctx)
	case itemnonce.FieldOpType:
		return m.OldOpType(ctx)
	case itemnonce.FieldCreateAtUnix:
		return m.OldCreateAtUnix(ctx)
	}
	return nil, fmt.Errorf("unknown ItemNonce field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ItemNonceMutation) SetField(name string, value ent.Value) error {
	switch name {
	case itemnonce.FieldUID:
		v, ok := value.(uint64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUID(v)
		return nil
	case itemnonce.FieldNonce:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetNonce(v)
		return nil
	case itemnonce.FieldOpType:
		v, ok := value.(itemTypes.OperationType)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOpType(v)
		return nil
	case itemnonce.FieldCreateAtUnix:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreateAtUnix(v)
		return nil
	}
	return fmt.Errorf("unknown ItemNonce field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ItemNonceMutation) AddedFields() []string {
	var fields []string
	if m.adduid != nil {
		fields = append(fields, itemnonce.FieldUID)
	}
	if m.addop_type != nil {
		fields = append(fields, itemnonce.FieldOpType)
	}
	if m.addcreate_at_unix != nil {
		fields = append(fields, itemnonce.FieldCreateAtUnix)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ItemNonceMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case itemnonce.FieldUID:
		return m.AddedUID()
	case itemnonce.FieldOpType:
		return m.AddedOpType()
	case itemnonce.FieldCreateAtUnix:
		return m.AddedCreateAtUnix()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ItemNonceMutation) AddField(name string, value ent.Value) error {
	switch name {
	case itemnonce.FieldUID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddUID(v)
		return nil
	case itemnonce.FieldOpType:
		v, ok := value.(itemTypes.OperationType)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddOpType(v)
		return nil
	case itemnonce.FieldCreateAtUnix:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddCreateAtUnix(v)
		return nil
	}
	return fmt.Errorf("unknown ItemNonce numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ItemNonceMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ItemNonceMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ItemNonceMutation) ClearField(name string) error {
	return fmt.Errorf("unknown ItemNonce nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ItemNonceMutation) ResetField(name string) error {
	switch name {
	case itemnonce.FieldUID:
		m.ResetUID()
		return nil
	case itemnonce.FieldNonce:
		m.ResetNonce()
		return nil
	case itemnonce.FieldOpType:
		m.ResetOpType()
		return nil
	case itemnonce.FieldCreateAtUnix:
		m.ResetCreateAtUnix()
		return nil
	}
	return fmt.Errorf("unknown ItemNonce field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ItemNonceMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ItemNonceMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ItemNonceMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ItemNonceMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ItemNonceMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ItemNonceMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ItemNonceMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown ItemNonce unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ItemNonceMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown ItemNonce edge %s", name)
}

// ItemUserLockMutation represents an operation that mutates the ItemUserLock nodes in the graph.
type ItemUserLockMutation struct {
	config
	op            Op
	typ           string
	id            *uint64
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*ItemUserLock, error)
	predicates    []predicate.ItemUserLock
}

var _ ent.Mutation = (*ItemUserLockMutation)(nil)

// itemuserlockOption allows management of the mutation configuration using functional options.
type itemuserlockOption func(*ItemUserLockMutation)

// newItemUserLockMutation creates new mutation for the ItemUserLock entity.
func newItemUserLockMutation(c config, op Op, opts ...itemuserlockOption) *ItemUserLockMutation {
	m := &ItemUserLockMutation{
		config:        c,
		op:            op,
		typ:           TypeItemUserLock,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withItemUserLockID sets the ID field of the mutation.
func withItemUserLockID(id uint64) itemuserlockOption {
	return func(m *ItemUserLockMutation) {
		var (
			err   error
			once  sync.Once
			value *ItemUserLock
		)
		m.oldValue = func(ctx context.Context) (*ItemUserLock, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().ItemUserLock.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withItemUserLock sets the old ItemUserLock of the mutation.
func withItemUserLock(node *ItemUserLock) itemuserlockOption {
	return func(m *ItemUserLockMutation) {
		m.oldValue = func(context.Context) (*ItemUserLock, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ItemUserLockMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ItemUserLockMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of ItemUserLock entities.
func (m *ItemUserLockMutation) SetID(id uint64) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ItemUserLockMutation) ID() (id uint64, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ItemUserLockMutation) IDs(ctx context.Context) ([]uint64, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uint64{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().ItemUserLock.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// Where appends a list predicates to the ItemUserLockMutation builder.
func (m *ItemUserLockMutation) Where(ps ...predicate.ItemUserLock) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the ItemUserLockMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *ItemUserLockMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.ItemUserLock, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *ItemUserLockMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *ItemUserLockMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (ItemUserLock).
func (m *ItemUserLockMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ItemUserLockMutation) Fields() []string {
	fields := make([]string, 0, 0)
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ItemUserLockMutation) Field(name string) (ent.Value, bool) {
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ItemUserLockMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	return nil, fmt.Errorf("unknown ItemUserLock field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ItemUserLockMutation) SetField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown ItemUserLock field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ItemUserLockMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ItemUserLockMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ItemUserLockMutation) AddField(name string, value ent.Value) error {
	return fmt.Errorf("unknown ItemUserLock numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ItemUserLockMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ItemUserLockMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ItemUserLockMutation) ClearField(name string) error {
	return fmt.Errorf("unknown ItemUserLock nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ItemUserLockMutation) ResetField(name string) error {
	return fmt.Errorf("unknown ItemUserLock field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ItemUserLockMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ItemUserLockMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ItemUserLockMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ItemUserLockMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ItemUserLockMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ItemUserLockMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ItemUserLockMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown ItemUserLock unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ItemUserLockMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown ItemUserLock edge %s", name)
}
