// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/2comjie/taoxi-server/app/Api/items/internal/store/ent/item"
	"github.com/2comjie/taoxi-server/app/Api/items/internal/store/ent/itemnonce"
	"github.com/2comjie/taoxi-server/app/Api/items/internal/store/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	itemFields := schema.Item{}.Fields()
	_ = itemFields
	// itemDescCount is the schema descriptor for count field.
	itemDescCount := itemFields[3].Descriptor()
	// item.CountValidator is a validator for the "count" field. It is called by the builders before save.
	item.CountValidator = itemDescCount.Validators[0].(func(int64) error)
	// itemDescUsedCount is the schema descriptor for used_count field.
	itemDescUsedCount := itemFields[4].Descriptor()
	// item.DefaultUsedCount holds the default value on creation for the used_count field.
	item.DefaultUsedCount = itemDescUsedCount.Default.(int64)
	// item.UsedCountValidator is a validator for the "used_count" field. It is called by the builders before save.
	item.UsedCountValidator = itemDescUsedCount.Validators[0].(func(int64) error)
	// itemDescExpireAtUnix is the schema descriptor for expire_at_unix field.
	itemDescExpireAtUnix := itemFields[5].Descriptor()
	// item.DefaultExpireAtUnix holds the default value on creation for the expire_at_unix field.
	item.DefaultExpireAtUnix = itemDescExpireAtUnix.Default.(int64)
	// itemDescSource is the schema descriptor for source field.
	itemDescSource := itemFields[6].Descriptor()
	// item.DefaultSource holds the default value on creation for the source field.
	item.DefaultSource = itemDescSource.Default.(string)
	// item.SourceValidator is a validator for the "source" field. It is called by the builders before save.
	item.SourceValidator = itemDescSource.Validators[0].(func(string) error)
	// itemDescCreateAtUnix is the schema descriptor for create_at_unix field.
	itemDescCreateAtUnix := itemFields[7].Descriptor()
	// item.DefaultCreateAtUnix holds the default value on creation for the create_at_unix field.
	item.DefaultCreateAtUnix = itemDescCreateAtUnix.Default.(func() int64)
	// itemDescUpdateAtUnix is the schema descriptor for update_at_unix field.
	itemDescUpdateAtUnix := itemFields[8].Descriptor()
	// item.DefaultUpdateAtUnix holds the default value on creation for the update_at_unix field.
	item.DefaultUpdateAtUnix = itemDescUpdateAtUnix.Default.(func() int64)
	// item.UpdateDefaultUpdateAtUnix holds the default value on update for the update_at_unix field.
	item.UpdateDefaultUpdateAtUnix = itemDescUpdateAtUnix.UpdateDefault.(func() int64)
	itemnonceFields := schema.ItemNonce{}.Fields()
	_ = itemnonceFields
	// itemnonceDescNonce is the schema descriptor for nonce field.
	itemnonceDescNonce := itemnonceFields[2].Descriptor()
	// itemnonce.NonceValidator is a validator for the "nonce" field. It is called by the builders before save.
	itemnonce.NonceValidator = itemnonceDescNonce.Validators[0].(func(string) error)
	// itemnonceDescCreateAtUnix is the schema descriptor for create_at_unix field.
	itemnonceDescCreateAtUnix := itemnonceFields[4].Descriptor()
	// itemnonce.DefaultCreateAtUnix holds the default value on creation for the create_at_unix field.
	itemnonce.DefaultCreateAtUnix = itemnonceDescCreateAtUnix.Default.(func() int64)
}
