// Code generated by protoc-gen-go-grpc-locator. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc-locator v1.2.0
// - protoc             v5.28.2
// source: player/player_service_rpc.proto

package pbPlayerServiceRPC

import (
	context "context"
	rpc "github.com/2comjie/nova/rpc"
	client "github.com/2comjie/nova/rpc/client"
	rpcerr "github.com/2comjie/nova/rpc/rpcerr"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PlayerService_Ping_FullMethodName = "/taoxi.player.service_rpc.PlayerService/Ping"
)

// PlayerServiceClient is the client API for PlayerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlayerServiceClient interface {
	Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingRsp, rpcerr.Err)
}

type playerServiceClient struct {
	cc *client.Client
}

func NewPlayerServiceClient(cc *client.Client) PlayerServiceClient {
	return &playerServiceClient{cc}
}

func (c *playerServiceClient) Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingRsp, rpcerr.Err) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	conn, err := c.cc.Conn(ctx)
	if err != nil {
		return nil, rpc.DecodeErr(err)
	}
	out := new(PingRsp)
	err = conn.Invoke(ctx, PlayerService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, rpc.DecodeErr(err)
	}
	return out, nil
}

// PlayerServiceServer is the server API for PlayerService service.
// All implementations must embed UnimplementedPlayerServiceServer
// for forward compatibility.
type PlayerServiceServer interface {
	Ping(context.Context, *PingReq) (*PingRsp, rpcerr.Err)
	mustEmbedUnimplementedPlayerServiceServer()
}

// UnimplementedPlayerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlayerServiceServer struct{}

func (UnimplementedPlayerServiceServer) Ping(context.Context, *PingReq) (*PingRsp, rpcerr.Err) {
	return nil, rpcerr.NewGRPC(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedPlayerServiceServer) mustEmbedUnimplementedPlayerServiceServer() {}
func (UnimplementedPlayerServiceServer) testEmbeddedByValue()                       {}

// UnsafePlayerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlayerServiceServer will
// result in compilation errors.
type UnsafePlayerServiceServer interface {
	mustEmbedUnimplementedPlayerServiceServer()
}

func RegisterPlayerServiceServer(s grpc.ServiceRegistrar, srv PlayerServiceServer) {
	// If the following call panics, it indicates UnimplementedPlayerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlayerService_ServiceDesc, srv)
}

func _PlayerService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		response, err := srv.(PlayerServiceServer).Ping(ctx, in)
		return response, rpc.EncodeError(err)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).Ping(ctx, req.(*PingReq))
	}
	response, err := interceptor(ctx, in, info, handler)
	return response, rpc.EncodeError(err)
}

// PlayerService_ServiceDesc is the grpc.ServiceDesc for PlayerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlayerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "taoxi.player.service_rpc.PlayerService",
	HandlerType: (*PlayerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _PlayerService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "player/player_service_rpc.proto",
}
