// Code generated by ent, DO NOT EDIT.

package account

import (
	"entgo.io/ent/dialect/sql"
	"github.com/2comjie/taoxi-server/app/Api/login/internal/store/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uint64) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint64) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint64) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint64) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint64) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint64) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint64) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint64) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint64) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldID, id))
}

// IsDeleted applies equality check predicate on the "is_deleted" field. It's identical to IsDeletedEQ.
func IsDeleted(v bool) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldIsDeleted, v))
}

// CreateAtUnix applies equality check predicate on the "create_at_unix" field. It's identical to CreateAtUnixEQ.
func CreateAtUnix(v int64) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldCreateAtUnix, v))
}

// UpdateAtUnix applies equality check predicate on the "update_at_unix" field. It's identical to UpdateAtUnixEQ.
func UpdateAtUnix(v int64) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldUpdateAtUnix, v))
}

// IsDeletedEQ applies the EQ predicate on the "is_deleted" field.
func IsDeletedEQ(v bool) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldIsDeleted, v))
}

// IsDeletedNEQ applies the NEQ predicate on the "is_deleted" field.
func IsDeletedNEQ(v bool) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldIsDeleted, v))
}

// CreateAtUnixEQ applies the EQ predicate on the "create_at_unix" field.
func CreateAtUnixEQ(v int64) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldCreateAtUnix, v))
}

// CreateAtUnixNEQ applies the NEQ predicate on the "create_at_unix" field.
func CreateAtUnixNEQ(v int64) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldCreateAtUnix, v))
}

// CreateAtUnixIn applies the In predicate on the "create_at_unix" field.
func CreateAtUnixIn(vs ...int64) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldCreateAtUnix, vs...))
}

// CreateAtUnixNotIn applies the NotIn predicate on the "create_at_unix" field.
func CreateAtUnixNotIn(vs ...int64) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldCreateAtUnix, vs...))
}

// CreateAtUnixGT applies the GT predicate on the "create_at_unix" field.
func CreateAtUnixGT(v int64) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldCreateAtUnix, v))
}

// CreateAtUnixGTE applies the GTE predicate on the "create_at_unix" field.
func CreateAtUnixGTE(v int64) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldCreateAtUnix, v))
}

// CreateAtUnixLT applies the LT predicate on the "create_at_unix" field.
func CreateAtUnixLT(v int64) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldCreateAtUnix, v))
}

// CreateAtUnixLTE applies the LTE predicate on the "create_at_unix" field.
func CreateAtUnixLTE(v int64) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldCreateAtUnix, v))
}

// UpdateAtUnixEQ applies the EQ predicate on the "update_at_unix" field.
func UpdateAtUnixEQ(v int64) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldUpdateAtUnix, v))
}

// UpdateAtUnixNEQ applies the NEQ predicate on the "update_at_unix" field.
func UpdateAtUnixNEQ(v int64) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldUpdateAtUnix, v))
}

// UpdateAtUnixIn applies the In predicate on the "update_at_unix" field.
func UpdateAtUnixIn(vs ...int64) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldUpdateAtUnix, vs...))
}

// UpdateAtUnixNotIn applies the NotIn predicate on the "update_at_unix" field.
func UpdateAtUnixNotIn(vs ...int64) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldUpdateAtUnix, vs...))
}

// UpdateAtUnixGT applies the GT predicate on the "update_at_unix" field.
func UpdateAtUnixGT(v int64) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldUpdateAtUnix, v))
}

// UpdateAtUnixGTE applies the GTE predicate on the "update_at_unix" field.
func UpdateAtUnixGTE(v int64) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldUpdateAtUnix, v))
}

// UpdateAtUnixLT applies the LT predicate on the "update_at_unix" field.
func UpdateAtUnixLT(v int64) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldUpdateAtUnix, v))
}

// UpdateAtUnixLTE applies the LTE predicate on the "update_at_unix" field.
func UpdateAtUnixLTE(v int64) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldUpdateAtUnix, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Account) predicate.Account {
	return predicate.Account(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Account) predicate.Account {
	return predicate.Account(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Account) predicate.Account {
	return predicate.Account(sql.NotPredicates(p))
}
