// Code generated by ent, DO NOT EDIT.

package itemuserlock

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the itemuserlock type in the database.
	Label = "item_user_lock"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "uid"
	// Table holds the table name of the itemuserlock in the database.
	Table = "item_user_locks"
)

// Columns holds all SQL columns for itemuserlock fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the ItemUserLock queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}
