// Code generated by ent, DO NOT EDIT.

package itemnonce

import (
	"entgo.io/ent/dialect/sql"
	"github.com/2comjie/taoxi-server/app/Api/items/internal/store/ent/predicate"
	itemTypes "github.com/2comjie/taoxi-server/app/Api/items/types"
)

// ID filters vertices based on their ID field.
func ID(id uint64) predicate.ItemNonce {
	return predicate.ItemNonce(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint64) predicate.ItemNonce {
	return predicate.ItemNonce(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint64) predicate.ItemNonce {
	return predicate.ItemNonce(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint64) predicate.ItemNonce {
	return predicate.ItemNonce(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint64) predicate.ItemNonce {
	return predicate.ItemNonce(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint64) predicate.ItemNonce {
	return predicate.ItemNonce(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint64) predicate.ItemNonce {
	return predicate.ItemNonce(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint64) predicate.ItemNonce {
	return predicate.ItemNonce(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint64) predicate.ItemNonce {
	return predicate.ItemNonce(sql.FieldLTE(FieldID, id))
}

// UID applies equality check predicate on the "uid" field. It's identical to UIDEQ.
func UID(v uint64) predicate.ItemNonce {
	return predicate.ItemNonce(sql.FieldEQ(FieldUID, v))
}

// Nonce applies equality check predicate on the "nonce" field. It's identical to NonceEQ.
func Nonce(v string) predicate.ItemNonce {
	return predicate.ItemNonce(sql.FieldEQ(FieldNonce, v))
}

// OpType applies equality check predicate on the "op_type" field. It's identical to OpTypeEQ.
func OpType(v itemTypes.OperationType) predicate.ItemNonce {
	vc := int32(v)
	return predicate.ItemNonce(sql.FieldEQ(FieldOpType, vc))
}

// CreateAtUnix applies equality check predicate on the "create_at_unix" field. It's identical to CreateAtUnixEQ.
func CreateAtUnix(v int64) predicate.ItemNonce {
	return predicate.ItemNonce(sql.FieldEQ(FieldCreateAtUnix, v))
}

// UIDEQ applies the EQ predicate on the "uid" field.
func UIDEQ(v uint64) predicate.ItemNonce {
	return predicate.ItemNonce(sql.FieldEQ(FieldUID, v))
}

// UIDNEQ applies the NEQ predicate on the "uid" field.
func UIDNEQ(v uint64) predicate.ItemNonce {
	return predicate.ItemNonce(sql.FieldNEQ(FieldUID, v))
}

// UIDIn applies the In predicate on the "uid" field.
func UIDIn(vs ...uint64) predicate.ItemNonce {
	return predicate.ItemNonce(sql.FieldIn(FieldUID, vs...))
}

// UIDNotIn applies the NotIn predicate on the "uid" field.
func UIDNotIn(vs ...uint64) predicate.ItemNonce {
	return predicate.ItemNonce(sql.FieldNotIn(FieldUID, vs...))
}

// UIDGT applies the GT predicate on the "uid" field.
func UIDGT(v uint64) predicate.ItemNonce {
	return predicate.ItemNonce(sql.FieldGT(FieldUID, v))
}

// UIDGTE applies the GTE predicate on the "uid" field.
func UIDGTE(v uint64) predicate.ItemNonce {
	return predicate.ItemNonce(sql.FieldGTE(FieldUID, v))
}

// UIDLT applies the LT predicate on the "uid" field.
func UIDLT(v uint64) predicate.ItemNonce {
	return predicate.ItemNonce(sql.FieldLT(FieldUID, v))
}

// UIDLTE applies the LTE predicate on the "uid" field.
func UIDLTE(v uint64) predicate.ItemNonce {
	return predicate.ItemNonce(sql.FieldLTE(FieldUID, v))
}

// NonceEQ applies the EQ predicate on the "nonce" field.
func NonceEQ(v string) predicate.ItemNonce {
	return predicate.ItemNonce(sql.FieldEQ(FieldNonce, v))
}

// NonceNEQ applies the NEQ predicate on the "nonce" field.
func NonceNEQ(v string) predicate.ItemNonce {
	return predicate.ItemNonce(sql.FieldNEQ(FieldNonce, v))
}

// NonceIn applies the In predicate on the "nonce" field.
func NonceIn(vs ...string) predicate.ItemNonce {
	return predicate.ItemNonce(sql.FieldIn(FieldNonce, vs...))
}

// NonceNotIn applies the NotIn predicate on the "nonce" field.
func NonceNotIn(vs ...string) predicate.ItemNonce {
	return predicate.ItemNonce(sql.FieldNotIn(FieldNonce, vs...))
}

// NonceGT applies the GT predicate on the "nonce" field.
func NonceGT(v string) predicate.ItemNonce {
	return predicate.ItemNonce(sql.FieldGT(FieldNonce, v))
}

// NonceGTE applies the GTE predicate on the "nonce" field.
func NonceGTE(v string) predicate.ItemNonce {
	return predicate.ItemNonce(sql.FieldGTE(FieldNonce, v))
}

// NonceLT applies the LT predicate on the "nonce" field.
func NonceLT(v string) predicate.ItemNonce {
	return predicate.ItemNonce(sql.FieldLT(FieldNonce, v))
}

// NonceLTE applies the LTE predicate on the "nonce" field.
func NonceLTE(v string) predicate.ItemNonce {
	return predicate.ItemNonce(sql.FieldLTE(FieldNonce, v))
}

// NonceContains applies the Contains predicate on the "nonce" field.
func NonceContains(v string) predicate.ItemNonce {
	return predicate.ItemNonce(sql.FieldContains(FieldNonce, v))
}

// NonceHasPrefix applies the HasPrefix predicate on the "nonce" field.
func NonceHasPrefix(v string) predicate.ItemNonce {
	return predicate.ItemNonce(sql.FieldHasPrefix(FieldNonce, v))
}

// NonceHasSuffix applies the HasSuffix predicate on the "nonce" field.
func NonceHasSuffix(v string) predicate.ItemNonce {
	return predicate.ItemNonce(sql.FieldHasSuffix(FieldNonce, v))
}

// NonceEqualFold applies the EqualFold predicate on the "nonce" field.
func NonceEqualFold(v string) predicate.ItemNonce {
	return predicate.ItemNonce(sql.FieldEqualFold(FieldNonce, v))
}

// NonceContainsFold applies the ContainsFold predicate on the "nonce" field.
func NonceContainsFold(v string) predicate.ItemNonce {
	return predicate.ItemNonce(sql.FieldContainsFold(FieldNonce, v))
}

// OpTypeEQ applies the EQ predicate on the "op_type" field.
func OpTypeEQ(v itemTypes.OperationType) predicate.ItemNonce {
	vc := int32(v)
	return predicate.ItemNonce(sql.FieldEQ(FieldOpType, vc))
}

// OpTypeNEQ applies the NEQ predicate on the "op_type" field.
func OpTypeNEQ(v itemTypes.OperationType) predicate.ItemNonce {
	vc := int32(v)
	return predicate.ItemNonce(sql.FieldNEQ(FieldOpType, vc))
}

// OpTypeIn applies the In predicate on the "op_type" field.
func OpTypeIn(vs ...itemTypes.OperationType) predicate.ItemNonce {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int32(vs[i])
	}
	return predicate.ItemNonce(sql.FieldIn(FieldOpType, v...))
}

// OpTypeNotIn applies the NotIn predicate on the "op_type" field.
func OpTypeNotIn(vs ...itemTypes.OperationType) predicate.ItemNonce {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int32(vs[i])
	}
	return predicate.ItemNonce(sql.FieldNotIn(FieldOpType, v...))
}

// OpTypeGT applies the GT predicate on the "op_type" field.
func OpTypeGT(v itemTypes.OperationType) predicate.ItemNonce {
	vc := int32(v)
	return predicate.ItemNonce(sql.FieldGT(FieldOpType, vc))
}

// OpTypeGTE applies the GTE predicate on the "op_type" field.
func OpTypeGTE(v itemTypes.OperationType) predicate.ItemNonce {
	vc := int32(v)
	return predicate.ItemNonce(sql.FieldGTE(FieldOpType, vc))
}

// OpTypeLT applies the LT predicate on the "op_type" field.
func OpTypeLT(v itemTypes.OperationType) predicate.ItemNonce {
	vc := int32(v)
	return predicate.ItemNonce(sql.FieldLT(FieldOpType, vc))
}

// OpTypeLTE applies the LTE predicate on the "op_type" field.
func OpTypeLTE(v itemTypes.OperationType) predicate.ItemNonce {
	vc := int32(v)
	return predicate.ItemNonce(sql.FieldLTE(FieldOpType, vc))
}

// CreateAtUnixEQ applies the EQ predicate on the "create_at_unix" field.
func CreateAtUnixEQ(v int64) predicate.ItemNonce {
	return predicate.ItemNonce(sql.FieldEQ(FieldCreateAtUnix, v))
}

// CreateAtUnixNEQ applies the NEQ predicate on the "create_at_unix" field.
func CreateAtUnixNEQ(v int64) predicate.ItemNonce {
	return predicate.ItemNonce(sql.FieldNEQ(FieldCreateAtUnix, v))
}

// CreateAtUnixIn applies the In predicate on the "create_at_unix" field.
func CreateAtUnixIn(vs ...int64) predicate.ItemNonce {
	return predicate.ItemNonce(sql.FieldIn(FieldCreateAtUnix, vs...))
}

// CreateAtUnixNotIn applies the NotIn predicate on the "create_at_unix" field.
func CreateAtUnixNotIn(vs ...int64) predicate.ItemNonce {
	return predicate.ItemNonce(sql.FieldNotIn(FieldCreateAtUnix, vs...))
}

// CreateAtUnixGT applies the GT predicate on the "create_at_unix" field.
func CreateAtUnixGT(v int64) predicate.ItemNonce {
	return predicate.ItemNonce(sql.FieldGT(FieldCreateAtUnix, v))
}

// CreateAtUnixGTE applies the GTE predicate on the "create_at_unix" field.
func CreateAtUnixGTE(v int64) predicate.ItemNonce {
	return predicate.ItemNonce(sql.FieldGTE(FieldCreateAtUnix, v))
}

// CreateAtUnixLT applies the LT predicate on the "create_at_unix" field.
func CreateAtUnixLT(v int64) predicate.ItemNonce {
	return predicate.ItemNonce(sql.FieldLT(FieldCreateAtUnix, v))
}

// CreateAtUnixLTE applies the LTE predicate on the "create_at_unix" field.
func CreateAtUnixLTE(v int64) predicate.ItemNonce {
	return predicate.ItemNonce(sql.FieldLTE(FieldCreateAtUnix, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ItemNonce) predicate.ItemNonce {
	return predicate.ItemNonce(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ItemNonce) predicate.ItemNonce {
	return predicate.ItemNonce(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ItemNonce) predicate.ItemNonce {
	return predicate.ItemNonce(sql.NotPredicates(p))
}
