// Code generated by ent, DO NOT EDIT.

package paymentorder

import (
	"entgo.io/ent/dialect/sql"
	paymentTypes "github.com/2comjie/taoxi-server/app/Api/payment/types"
)

const (
	// Label holds the string label denoting the paymentorder type in the database.
	Label = "payment_order"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUID holds the string denoting the uid field in the database.
	FieldUID = "uid"
	// FieldProductID holds the string denoting the product_id field in the database.
	FieldProductID = "product_id"
	// FieldThirdPartyProductID holds the string denoting the third_party_product_id field in the database.
	FieldThirdPartyProductID = "third_party_product_id"
	// FieldPaymentType holds the string denoting the payment_type field in the database.
	FieldPaymentType = "payment_type"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldOrderAmountUnit holds the string denoting the order_amount_unit field in the database.
	FieldOrderAmountUnit = "order_amount_unit"
	// FieldOrderAmountNanos holds the string denoting the order_amount_nanos field in the database.
	FieldOrderAmountNanos = "order_amount_nanos"
	// FieldOrderCurrency holds the string denoting the order_currency field in the database.
	FieldOrderCurrency = "order_currency"
	// FieldRealAmountUnit holds the string denoting the real_amount_unit field in the database.
	FieldRealAmountUnit = "real_amount_unit"
	// FieldRealAmountNanos holds the string denoting the real_amount_nanos field in the database.
	FieldRealAmountNanos = "real_amount_nanos"
	// FieldRealCurrency holds the string denoting the real_currency field in the database.
	FieldRealCurrency = "real_currency"
	// FieldThirdPartyOrderID holds the string denoting the third_party_order_id field in the database.
	FieldThirdPartyOrderID = "third_party_order_id"
	// FieldCredential holds the string denoting the credential field in the database.
	FieldCredential = "credential"
	// FieldCredentialHash holds the string denoting the credential_hash field in the database.
	FieldCredentialHash = "credential_hash"
	// FieldRewards holds the string denoting the rewards field in the database.
	FieldRewards = "rewards"
	// FieldRetryTimes holds the string denoting the retry_times field in the database.
	FieldRetryTimes = "retry_times"
	// FieldCancelReason holds the string denoting the cancel_reason field in the database.
	FieldCancelReason = "cancel_reason"
	// FieldRefundReason holds the string denoting the refund_reason field in the database.
	FieldRefundReason = "refund_reason"
	// FieldIsSandbox holds the string denoting the is_sandbox field in the database.
	FieldIsSandbox = "is_sandbox"
	// FieldCreateAtUnix holds the string denoting the create_at_unix field in the database.
	FieldCreateAtUnix = "create_at_unix"
	// FieldUpdateAtUnix holds the string denoting the update_at_unix field in the database.
	FieldUpdateAtUnix = "update_at_unix"
	// FieldPayAtUnix holds the string denoting the pay_at_unix field in the database.
	FieldPayAtUnix = "pay_at_unix"
	// FieldRefundAtUnix holds the string denoting the refund_at_unix field in the database.
	FieldRefundAtUnix = "refund_at_unix"
	// FieldCancelAtUnix holds the string denoting the cancel_at_unix field in the database.
	FieldCancelAtUnix = "cancel_at_unix"
	// Table holds the table name of the paymentorder in the database.
	Table = "payment_orders"
)

// Columns holds all SQL columns for paymentorder fields.
var Columns = []string{
	FieldID,
	FieldUID,
	FieldProductID,
	FieldThirdPartyProductID,
	FieldPaymentType,
	FieldStatus,
	FieldOrderAmountUnit,
	FieldOrderAmountNanos,
	FieldOrderCurrency,
	FieldRealAmountUnit,
	FieldRealAmountNanos,
	FieldRealCurrency,
	FieldThirdPartyOrderID,
	FieldCredential,
	FieldCredentialHash,
	FieldRewards,
	FieldRetryTimes,
	FieldCancelReason,
	FieldRefundReason,
	FieldIsSandbox,
	FieldCreateAtUnix,
	FieldUpdateAtUnix,
	FieldPayAtUnix,
	FieldRefundAtUnix,
	FieldCancelAtUnix,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus paymentTypes.OrderStatus
	// DefaultRealAmountUnit holds the default value on creation for the "real_amount_unit" field.
	DefaultRealAmountUnit int64
	// DefaultRealAmountNanos holds the default value on creation for the "real_amount_nanos" field.
	DefaultRealAmountNanos int32
	// DefaultRealCurrency holds the default value on creation for the "real_currency" field.
	DefaultRealCurrency string
	// DefaultRetryTimes holds the default value on creation for the "retry_times" field.
	DefaultRetryTimes int32
	// DefaultCancelReason holds the default value on creation for the "cancel_reason" field.
	DefaultCancelReason string
	// DefaultRefundReason holds the default value on creation for the "refund_reason" field.
	DefaultRefundReason string
	// DefaultIsSandbox holds the default value on creation for the "is_sandbox" field.
	DefaultIsSandbox bool
	// DefaultCreateAtUnix holds the default value on creation for the "create_at_unix" field.
	DefaultCreateAtUnix func() int64
	// DefaultUpdateAtUnix holds the default value on creation for the "update_at_unix" field.
	DefaultUpdateAtUnix func() int64
	// UpdateDefaultUpdateAtUnix holds the default value on update for the "update_at_unix" field.
	UpdateDefaultUpdateAtUnix func() int64
	// DefaultPayAtUnix holds the default value on creation for the "pay_at_unix" field.
	DefaultPayAtUnix int64
	// DefaultRefundAtUnix holds the default value on creation for the "refund_at_unix" field.
	DefaultRefundAtUnix int64
	// DefaultCancelAtUnix holds the default value on creation for the "cancel_at_unix" field.
	DefaultCancelAtUnix int64
)

// OrderOption defines the ordering options for the PaymentOrder queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUID orders the results by the uid field.
func ByUID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUID, opts...).ToFunc()
}

// ByProductID orders the results by the product_id field.
func ByProductID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProductID, opts...).ToFunc()
}

// ByThirdPartyProductID orders the results by the third_party_product_id field.
func ByThirdPartyProductID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldThirdPartyProductID, opts...).ToFunc()
}

// ByPaymentType orders the results by the payment_type field.
func ByPaymentType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaymentType, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByOrderAmountUnit orders the results by the order_amount_unit field.
func ByOrderAmountUnit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderAmountUnit, opts...).ToFunc()
}

// ByOrderAmountNanos orders the results by the order_amount_nanos field.
func ByOrderAmountNanos(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderAmountNanos, opts...).ToFunc()
}

// ByOrderCurrency orders the results by the order_currency field.
func ByOrderCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderCurrency, opts...).ToFunc()
}

// ByRealAmountUnit orders the results by the real_amount_unit field.
func ByRealAmountUnit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRealAmountUnit, opts...).ToFunc()
}

// ByRealAmountNanos orders the results by the real_amount_nanos field.
func ByRealAmountNanos(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRealAmountNanos, opts...).ToFunc()
}

// ByRealCurrency orders the results by the real_currency field.
func ByRealCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRealCurrency, opts...).ToFunc()
}

// ByThirdPartyOrderID orders the results by the third_party_order_id field.
func ByThirdPartyOrderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldThirdPartyOrderID, opts...).ToFunc()
}

// ByCredential orders the results by the credential field.
func ByCredential(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCredential, opts...).ToFunc()
}

// ByCredentialHash orders the results by the credential_hash field.
func ByCredentialHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCredentialHash, opts...).ToFunc()
}

// ByRetryTimes orders the results by the retry_times field.
func ByRetryTimes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRetryTimes, opts...).ToFunc()
}

// ByCancelReason orders the results by the cancel_reason field.
func ByCancelReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCancelReason, opts...).ToFunc()
}

// ByRefundReason orders the results by the refund_reason field.
func ByRefundReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefundReason, opts...).ToFunc()
}

// ByIsSandbox orders the results by the is_sandbox field.
func ByIsSandbox(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsSandbox, opts...).ToFunc()
}

// ByCreateAtUnix orders the results by the create_at_unix field.
func ByCreateAtUnix(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateAtUnix, opts...).ToFunc()
}

// ByUpdateAtUnix orders the results by the update_at_unix field.
func ByUpdateAtUnix(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateAtUnix, opts...).ToFunc()
}

// ByPayAtUnix orders the results by the pay_at_unix field.
func ByPayAtUnix(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPayAtUnix, opts...).ToFunc()
}

// ByRefundAtUnix orders the results by the refund_at_unix field.
func ByRefundAtUnix(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefundAtUnix, opts...).ToFunc()
}

// ByCancelAtUnix orders the results by the cancel_at_unix field.
func ByCancelAtUnix(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCancelAtUnix, opts...).ToFunc()
}
