// Code generated by ent, DO NOT EDIT.

package paymentorder

import (
	"entgo.io/ent/dialect/sql"
	"github.com/2comjie/taoxi-server/app/Api/payment/internal/store/ent/predicate"
	paymentTypes "github.com/2comjie/taoxi-server/app/Api/payment/types"
)

// ID filters vertices based on their ID field.
func ID(id uint64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLTE(FieldID, id))
}

// UID applies equality check predicate on the "uid" field. It's identical to UIDEQ.
func UID(v uint64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldUID, v))
}

// ProductID applies equality check predicate on the "product_id" field. It's identical to ProductIDEQ.
func ProductID(v int32) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldProductID, v))
}

// ThirdPartyProductID applies equality check predicate on the "third_party_product_id" field. It's identical to ThirdPartyProductIDEQ.
func ThirdPartyProductID(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldThirdPartyProductID, v))
}

// PaymentType applies equality check predicate on the "payment_type" field. It's identical to PaymentTypeEQ.
func PaymentType(v int32) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldPaymentType, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v paymentTypes.OrderStatus) predicate.PaymentOrder {
	vc := int32(v)
	return predicate.PaymentOrder(sql.FieldEQ(FieldStatus, vc))
}

// OrderAmountUnit applies equality check predicate on the "order_amount_unit" field. It's identical to OrderAmountUnitEQ.
func OrderAmountUnit(v int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldOrderAmountUnit, v))
}

// OrderAmountNanos applies equality check predicate on the "order_amount_nanos" field. It's identical to OrderAmountNanosEQ.
func OrderAmountNanos(v int32) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldOrderAmountNanos, v))
}

// OrderCurrency applies equality check predicate on the "order_currency" field. It's identical to OrderCurrencyEQ.
func OrderCurrency(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldOrderCurrency, v))
}

// RealAmountUnit applies equality check predicate on the "real_amount_unit" field. It's identical to RealAmountUnitEQ.
func RealAmountUnit(v int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldRealAmountUnit, v))
}

// RealAmountNanos applies equality check predicate on the "real_amount_nanos" field. It's identical to RealAmountNanosEQ.
func RealAmountNanos(v int32) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldRealAmountNanos, v))
}

// RealCurrency applies equality check predicate on the "real_currency" field. It's identical to RealCurrencyEQ.
func RealCurrency(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldRealCurrency, v))
}

// ThirdPartyOrderID applies equality check predicate on the "third_party_order_id" field. It's identical to ThirdPartyOrderIDEQ.
func ThirdPartyOrderID(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldThirdPartyOrderID, v))
}

// Credential applies equality check predicate on the "credential" field. It's identical to CredentialEQ.
func Credential(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldCredential, v))
}

// CredentialHash applies equality check predicate on the "credential_hash" field. It's identical to CredentialHashEQ.
func CredentialHash(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldCredentialHash, v))
}

// RetryTimes applies equality check predicate on the "retry_times" field. It's identical to RetryTimesEQ.
func RetryTimes(v int32) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldRetryTimes, v))
}

// CancelReason applies equality check predicate on the "cancel_reason" field. It's identical to CancelReasonEQ.
func CancelReason(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldCancelReason, v))
}

// RefundReason applies equality check predicate on the "refund_reason" field. It's identical to RefundReasonEQ.
func RefundReason(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldRefundReason, v))
}

// IsSandbox applies equality check predicate on the "is_sandbox" field. It's identical to IsSandboxEQ.
func IsSandbox(v bool) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldIsSandbox, v))
}

// CreateAtUnix applies equality check predicate on the "create_at_unix" field. It's identical to CreateAtUnixEQ.
func CreateAtUnix(v int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldCreateAtUnix, v))
}

// UpdateAtUnix applies equality check predicate on the "update_at_unix" field. It's identical to UpdateAtUnixEQ.
func UpdateAtUnix(v int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldUpdateAtUnix, v))
}

// PayAtUnix applies equality check predicate on the "pay_at_unix" field. It's identical to PayAtUnixEQ.
func PayAtUnix(v int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldPayAtUnix, v))
}

// RefundAtUnix applies equality check predicate on the "refund_at_unix" field. It's identical to RefundAtUnixEQ.
func RefundAtUnix(v int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldRefundAtUnix, v))
}

// CancelAtUnix applies equality check predicate on the "cancel_at_unix" field. It's identical to CancelAtUnixEQ.
func CancelAtUnix(v int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldCancelAtUnix, v))
}

// UIDEQ applies the EQ predicate on the "uid" field.
func UIDEQ(v uint64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldUID, v))
}

// UIDNEQ applies the NEQ predicate on the "uid" field.
func UIDNEQ(v uint64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNEQ(FieldUID, v))
}

// UIDIn applies the In predicate on the "uid" field.
func UIDIn(vs ...uint64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldIn(FieldUID, vs...))
}

// UIDNotIn applies the NotIn predicate on the "uid" field.
func UIDNotIn(vs ...uint64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNotIn(FieldUID, vs...))
}

// UIDGT applies the GT predicate on the "uid" field.
func UIDGT(v uint64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGT(FieldUID, v))
}

// UIDGTE applies the GTE predicate on the "uid" field.
func UIDGTE(v uint64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGTE(FieldUID, v))
}

// UIDLT applies the LT predicate on the "uid" field.
func UIDLT(v uint64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLT(FieldUID, v))
}

// UIDLTE applies the LTE predicate on the "uid" field.
func UIDLTE(v uint64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLTE(FieldUID, v))
}

// ProductIDEQ applies the EQ predicate on the "product_id" field.
func ProductIDEQ(v int32) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldProductID, v))
}

// ProductIDNEQ applies the NEQ predicate on the "product_id" field.
func ProductIDNEQ(v int32) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNEQ(FieldProductID, v))
}

// ProductIDIn applies the In predicate on the "product_id" field.
func ProductIDIn(vs ...int32) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldIn(FieldProductID, vs...))
}

// ProductIDNotIn applies the NotIn predicate on the "product_id" field.
func ProductIDNotIn(vs ...int32) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNotIn(FieldProductID, vs...))
}

// ProductIDGT applies the GT predicate on the "product_id" field.
func ProductIDGT(v int32) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGT(FieldProductID, v))
}

// ProductIDGTE applies the GTE predicate on the "product_id" field.
func ProductIDGTE(v int32) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGTE(FieldProductID, v))
}

// ProductIDLT applies the LT predicate on the "product_id" field.
func ProductIDLT(v int32) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLT(FieldProductID, v))
}

// ProductIDLTE applies the LTE predicate on the "product_id" field.
func ProductIDLTE(v int32) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLTE(FieldProductID, v))
}

// ThirdPartyProductIDEQ applies the EQ predicate on the "third_party_product_id" field.
func ThirdPartyProductIDEQ(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldThirdPartyProductID, v))
}

// ThirdPartyProductIDNEQ applies the NEQ predicate on the "third_party_product_id" field.
func ThirdPartyProductIDNEQ(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNEQ(FieldThirdPartyProductID, v))
}

// ThirdPartyProductIDIn applies the In predicate on the "third_party_product_id" field.
func ThirdPartyProductIDIn(vs ...string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldIn(FieldThirdPartyProductID, vs...))
}

// ThirdPartyProductIDNotIn applies the NotIn predicate on the "third_party_product_id" field.
func ThirdPartyProductIDNotIn(vs ...string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNotIn(FieldThirdPartyProductID, vs...))
}

// ThirdPartyProductIDGT applies the GT predicate on the "third_party_product_id" field.
func ThirdPartyProductIDGT(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGT(FieldThirdPartyProductID, v))
}

// ThirdPartyProductIDGTE applies the GTE predicate on the "third_party_product_id" field.
func ThirdPartyProductIDGTE(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGTE(FieldThirdPartyProductID, v))
}

// ThirdPartyProductIDLT applies the LT predicate on the "third_party_product_id" field.
func ThirdPartyProductIDLT(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLT(FieldThirdPartyProductID, v))
}

// ThirdPartyProductIDLTE applies the LTE predicate on the "third_party_product_id" field.
func ThirdPartyProductIDLTE(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLTE(FieldThirdPartyProductID, v))
}

// ThirdPartyProductIDContains applies the Contains predicate on the "third_party_product_id" field.
func ThirdPartyProductIDContains(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldContains(FieldThirdPartyProductID, v))
}

// ThirdPartyProductIDHasPrefix applies the HasPrefix predicate on the "third_party_product_id" field.
func ThirdPartyProductIDHasPrefix(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldHasPrefix(FieldThirdPartyProductID, v))
}

// ThirdPartyProductIDHasSuffix applies the HasSuffix predicate on the "third_party_product_id" field.
func ThirdPartyProductIDHasSuffix(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldHasSuffix(FieldThirdPartyProductID, v))
}

// ThirdPartyProductIDEqualFold applies the EqualFold predicate on the "third_party_product_id" field.
func ThirdPartyProductIDEqualFold(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEqualFold(FieldThirdPartyProductID, v))
}

// ThirdPartyProductIDContainsFold applies the ContainsFold predicate on the "third_party_product_id" field.
func ThirdPartyProductIDContainsFold(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldContainsFold(FieldThirdPartyProductID, v))
}

// PaymentTypeEQ applies the EQ predicate on the "payment_type" field.
func PaymentTypeEQ(v int32) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldPaymentType, v))
}

// PaymentTypeNEQ applies the NEQ predicate on the "payment_type" field.
func PaymentTypeNEQ(v int32) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNEQ(FieldPaymentType, v))
}

// PaymentTypeIn applies the In predicate on the "payment_type" field.
func PaymentTypeIn(vs ...int32) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldIn(FieldPaymentType, vs...))
}

// PaymentTypeNotIn applies the NotIn predicate on the "payment_type" field.
func PaymentTypeNotIn(vs ...int32) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNotIn(FieldPaymentType, vs...))
}

// PaymentTypeGT applies the GT predicate on the "payment_type" field.
func PaymentTypeGT(v int32) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGT(FieldPaymentType, v))
}

// PaymentTypeGTE applies the GTE predicate on the "payment_type" field.
func PaymentTypeGTE(v int32) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGTE(FieldPaymentType, v))
}

// PaymentTypeLT applies the LT predicate on the "payment_type" field.
func PaymentTypeLT(v int32) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLT(FieldPaymentType, v))
}

// PaymentTypeLTE applies the LTE predicate on the "payment_type" field.
func PaymentTypeLTE(v int32) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLTE(FieldPaymentType, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v paymentTypes.OrderStatus) predicate.PaymentOrder {
	vc := int32(v)
	return predicate.PaymentOrder(sql.FieldEQ(FieldStatus, vc))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v paymentTypes.OrderStatus) predicate.PaymentOrder {
	vc := int32(v)
	return predicate.PaymentOrder(sql.FieldNEQ(FieldStatus, vc))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...paymentTypes.OrderStatus) predicate.PaymentOrder {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int32(vs[i])
	}
	return predicate.PaymentOrder(sql.FieldIn(FieldStatus, v...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...paymentTypes.OrderStatus) predicate.PaymentOrder {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int32(vs[i])
	}
	return predicate.PaymentOrder(sql.FieldNotIn(FieldStatus, v...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v paymentTypes.OrderStatus) predicate.PaymentOrder {
	vc := int32(v)
	return predicate.PaymentOrder(sql.FieldGT(FieldStatus, vc))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v paymentTypes.OrderStatus) predicate.PaymentOrder {
	vc := int32(v)
	return predicate.PaymentOrder(sql.FieldGTE(FieldStatus, vc))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v paymentTypes.OrderStatus) predicate.PaymentOrder {
	vc := int32(v)
	return predicate.PaymentOrder(sql.FieldLT(FieldStatus, vc))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v paymentTypes.OrderStatus) predicate.PaymentOrder {
	vc := int32(v)
	return predicate.PaymentOrder(sql.FieldLTE(FieldStatus, vc))
}

// OrderAmountUnitEQ applies the EQ predicate on the "order_amount_unit" field.
func OrderAmountUnitEQ(v int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldOrderAmountUnit, v))
}

// OrderAmountUnitNEQ applies the NEQ predicate on the "order_amount_unit" field.
func OrderAmountUnitNEQ(v int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNEQ(FieldOrderAmountUnit, v))
}

// OrderAmountUnitIn applies the In predicate on the "order_amount_unit" field.
func OrderAmountUnitIn(vs ...int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldIn(FieldOrderAmountUnit, vs...))
}

// OrderAmountUnitNotIn applies the NotIn predicate on the "order_amount_unit" field.
func OrderAmountUnitNotIn(vs ...int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNotIn(FieldOrderAmountUnit, vs...))
}

// OrderAmountUnitGT applies the GT predicate on the "order_amount_unit" field.
func OrderAmountUnitGT(v int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGT(FieldOrderAmountUnit, v))
}

// OrderAmountUnitGTE applies the GTE predicate on the "order_amount_unit" field.
func OrderAmountUnitGTE(v int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGTE(FieldOrderAmountUnit, v))
}

// OrderAmountUnitLT applies the LT predicate on the "order_amount_unit" field.
func OrderAmountUnitLT(v int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLT(FieldOrderAmountUnit, v))
}

// OrderAmountUnitLTE applies the LTE predicate on the "order_amount_unit" field.
func OrderAmountUnitLTE(v int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLTE(FieldOrderAmountUnit, v))
}

// OrderAmountNanosEQ applies the EQ predicate on the "order_amount_nanos" field.
func OrderAmountNanosEQ(v int32) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldOrderAmountNanos, v))
}

// OrderAmountNanosNEQ applies the NEQ predicate on the "order_amount_nanos" field.
func OrderAmountNanosNEQ(v int32) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNEQ(FieldOrderAmountNanos, v))
}

// OrderAmountNanosIn applies the In predicate on the "order_amount_nanos" field.
func OrderAmountNanosIn(vs ...int32) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldIn(FieldOrderAmountNanos, vs...))
}

// OrderAmountNanosNotIn applies the NotIn predicate on the "order_amount_nanos" field.
func OrderAmountNanosNotIn(vs ...int32) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNotIn(FieldOrderAmountNanos, vs...))
}

// OrderAmountNanosGT applies the GT predicate on the "order_amount_nanos" field.
func OrderAmountNanosGT(v int32) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGT(FieldOrderAmountNanos, v))
}

// OrderAmountNanosGTE applies the GTE predicate on the "order_amount_nanos" field.
func OrderAmountNanosGTE(v int32) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGTE(FieldOrderAmountNanos, v))
}

// OrderAmountNanosLT applies the LT predicate on the "order_amount_nanos" field.
func OrderAmountNanosLT(v int32) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLT(FieldOrderAmountNanos, v))
}

// OrderAmountNanosLTE applies the LTE predicate on the "order_amount_nanos" field.
func OrderAmountNanosLTE(v int32) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLTE(FieldOrderAmountNanos, v))
}

// OrderCurrencyEQ applies the EQ predicate on the "order_currency" field.
func OrderCurrencyEQ(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldOrderCurrency, v))
}

// OrderCurrencyNEQ applies the NEQ predicate on the "order_currency" field.
func OrderCurrencyNEQ(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNEQ(FieldOrderCurrency, v))
}

// OrderCurrencyIn applies the In predicate on the "order_currency" field.
func OrderCurrencyIn(vs ...string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldIn(FieldOrderCurrency, vs...))
}

// OrderCurrencyNotIn applies the NotIn predicate on the "order_currency" field.
func OrderCurrencyNotIn(vs ...string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNotIn(FieldOrderCurrency, vs...))
}

// OrderCurrencyGT applies the GT predicate on the "order_currency" field.
func OrderCurrencyGT(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGT(FieldOrderCurrency, v))
}

// OrderCurrencyGTE applies the GTE predicate on the "order_currency" field.
func OrderCurrencyGTE(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGTE(FieldOrderCurrency, v))
}

// OrderCurrencyLT applies the LT predicate on the "order_currency" field.
func OrderCurrencyLT(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLT(FieldOrderCurrency, v))
}

// OrderCurrencyLTE applies the LTE predicate on the "order_currency" field.
func OrderCurrencyLTE(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLTE(FieldOrderCurrency, v))
}

// OrderCurrencyContains applies the Contains predicate on the "order_currency" field.
func OrderCurrencyContains(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldContains(FieldOrderCurrency, v))
}

// OrderCurrencyHasPrefix applies the HasPrefix predicate on the "order_currency" field.
func OrderCurrencyHasPrefix(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldHasPrefix(FieldOrderCurrency, v))
}

// OrderCurrencyHasSuffix applies the HasSuffix predicate on the "order_currency" field.
func OrderCurrencyHasSuffix(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldHasSuffix(FieldOrderCurrency, v))
}

// OrderCurrencyEqualFold applies the EqualFold predicate on the "order_currency" field.
func OrderCurrencyEqualFold(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEqualFold(FieldOrderCurrency, v))
}

// OrderCurrencyContainsFold applies the ContainsFold predicate on the "order_currency" field.
func OrderCurrencyContainsFold(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldContainsFold(FieldOrderCurrency, v))
}

// RealAmountUnitEQ applies the EQ predicate on the "real_amount_unit" field.
func RealAmountUnitEQ(v int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldRealAmountUnit, v))
}

// RealAmountUnitNEQ applies the NEQ predicate on the "real_amount_unit" field.
func RealAmountUnitNEQ(v int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNEQ(FieldRealAmountUnit, v))
}

// RealAmountUnitIn applies the In predicate on the "real_amount_unit" field.
func RealAmountUnitIn(vs ...int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldIn(FieldRealAmountUnit, vs...))
}

// RealAmountUnitNotIn applies the NotIn predicate on the "real_amount_unit" field.
func RealAmountUnitNotIn(vs ...int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNotIn(FieldRealAmountUnit, vs...))
}

// RealAmountUnitGT applies the GT predicate on the "real_amount_unit" field.
func RealAmountUnitGT(v int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGT(FieldRealAmountUnit, v))
}

// RealAmountUnitGTE applies the GTE predicate on the "real_amount_unit" field.
func RealAmountUnitGTE(v int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGTE(FieldRealAmountUnit, v))
}

// RealAmountUnitLT applies the LT predicate on the "real_amount_unit" field.
func RealAmountUnitLT(v int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLT(FieldRealAmountUnit, v))
}

// RealAmountUnitLTE applies the LTE predicate on the "real_amount_unit" field.
func RealAmountUnitLTE(v int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLTE(FieldRealAmountUnit, v))
}

// RealAmountNanosEQ applies the EQ predicate on the "real_amount_nanos" field.
func RealAmountNanosEQ(v int32) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldRealAmountNanos, v))
}

// RealAmountNanosNEQ applies the NEQ predicate on the "real_amount_nanos" field.
func RealAmountNanosNEQ(v int32) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNEQ(FieldRealAmountNanos, v))
}

// RealAmountNanosIn applies the In predicate on the "real_amount_nanos" field.
func RealAmountNanosIn(vs ...int32) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldIn(FieldRealAmountNanos, vs...))
}

// RealAmountNanosNotIn applies the NotIn predicate on the "real_amount_nanos" field.
func RealAmountNanosNotIn(vs ...int32) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNotIn(FieldRealAmountNanos, vs...))
}

// RealAmountNanosGT applies the GT predicate on the "real_amount_nanos" field.
func RealAmountNanosGT(v int32) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGT(FieldRealAmountNanos, v))
}

// RealAmountNanosGTE applies the GTE predicate on the "real_amount_nanos" field.
func RealAmountNanosGTE(v int32) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGTE(FieldRealAmountNanos, v))
}

// RealAmountNanosLT applies the LT predicate on the "real_amount_nanos" field.
func RealAmountNanosLT(v int32) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLT(FieldRealAmountNanos, v))
}

// RealAmountNanosLTE applies the LTE predicate on the "real_amount_nanos" field.
func RealAmountNanosLTE(v int32) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLTE(FieldRealAmountNanos, v))
}

// RealCurrencyEQ applies the EQ predicate on the "real_currency" field.
func RealCurrencyEQ(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldRealCurrency, v))
}

// RealCurrencyNEQ applies the NEQ predicate on the "real_currency" field.
func RealCurrencyNEQ(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNEQ(FieldRealCurrency, v))
}

// RealCurrencyIn applies the In predicate on the "real_currency" field.
func RealCurrencyIn(vs ...string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldIn(FieldRealCurrency, vs...))
}

// RealCurrencyNotIn applies the NotIn predicate on the "real_currency" field.
func RealCurrencyNotIn(vs ...string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNotIn(FieldRealCurrency, vs...))
}

// RealCurrencyGT applies the GT predicate on the "real_currency" field.
func RealCurrencyGT(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGT(FieldRealCurrency, v))
}

// RealCurrencyGTE applies the GTE predicate on the "real_currency" field.
func RealCurrencyGTE(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGTE(FieldRealCurrency, v))
}

// RealCurrencyLT applies the LT predicate on the "real_currency" field.
func RealCurrencyLT(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLT(FieldRealCurrency, v))
}

// RealCurrencyLTE applies the LTE predicate on the "real_currency" field.
func RealCurrencyLTE(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLTE(FieldRealCurrency, v))
}

// RealCurrencyContains applies the Contains predicate on the "real_currency" field.
func RealCurrencyContains(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldContains(FieldRealCurrency, v))
}

// RealCurrencyHasPrefix applies the HasPrefix predicate on the "real_currency" field.
func RealCurrencyHasPrefix(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldHasPrefix(FieldRealCurrency, v))
}

// RealCurrencyHasSuffix applies the HasSuffix predicate on the "real_currency" field.
func RealCurrencyHasSuffix(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldHasSuffix(FieldRealCurrency, v))
}

// RealCurrencyEqualFold applies the EqualFold predicate on the "real_currency" field.
func RealCurrencyEqualFold(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEqualFold(FieldRealCurrency, v))
}

// RealCurrencyContainsFold applies the ContainsFold predicate on the "real_currency" field.
func RealCurrencyContainsFold(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldContainsFold(FieldRealCurrency, v))
}

// ThirdPartyOrderIDEQ applies the EQ predicate on the "third_party_order_id" field.
func ThirdPartyOrderIDEQ(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldThirdPartyOrderID, v))
}

// ThirdPartyOrderIDNEQ applies the NEQ predicate on the "third_party_order_id" field.
func ThirdPartyOrderIDNEQ(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNEQ(FieldThirdPartyOrderID, v))
}

// ThirdPartyOrderIDIn applies the In predicate on the "third_party_order_id" field.
func ThirdPartyOrderIDIn(vs ...string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldIn(FieldThirdPartyOrderID, vs...))
}

// ThirdPartyOrderIDNotIn applies the NotIn predicate on the "third_party_order_id" field.
func ThirdPartyOrderIDNotIn(vs ...string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNotIn(FieldThirdPartyOrderID, vs...))
}

// ThirdPartyOrderIDGT applies the GT predicate on the "third_party_order_id" field.
func ThirdPartyOrderIDGT(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGT(FieldThirdPartyOrderID, v))
}

// ThirdPartyOrderIDGTE applies the GTE predicate on the "third_party_order_id" field.
func ThirdPartyOrderIDGTE(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGTE(FieldThirdPartyOrderID, v))
}

// ThirdPartyOrderIDLT applies the LT predicate on the "third_party_order_id" field.
func ThirdPartyOrderIDLT(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLT(FieldThirdPartyOrderID, v))
}

// ThirdPartyOrderIDLTE applies the LTE predicate on the "third_party_order_id" field.
func ThirdPartyOrderIDLTE(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLTE(FieldThirdPartyOrderID, v))
}

// ThirdPartyOrderIDContains applies the Contains predicate on the "third_party_order_id" field.
func ThirdPartyOrderIDContains(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldContains(FieldThirdPartyOrderID, v))
}

// ThirdPartyOrderIDHasPrefix applies the HasPrefix predicate on the "third_party_order_id" field.
func ThirdPartyOrderIDHasPrefix(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldHasPrefix(FieldThirdPartyOrderID, v))
}

// ThirdPartyOrderIDHasSuffix applies the HasSuffix predicate on the "third_party_order_id" field.
func ThirdPartyOrderIDHasSuffix(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldHasSuffix(FieldThirdPartyOrderID, v))
}

// ThirdPartyOrderIDIsNil applies the IsNil predicate on the "third_party_order_id" field.
func ThirdPartyOrderIDIsNil() predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldIsNull(FieldThirdPartyOrderID))
}

// ThirdPartyOrderIDNotNil applies the NotNil predicate on the "third_party_order_id" field.
func ThirdPartyOrderIDNotNil() predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNotNull(FieldThirdPartyOrderID))
}

// ThirdPartyOrderIDEqualFold applies the EqualFold predicate on the "third_party_order_id" field.
func ThirdPartyOrderIDEqualFold(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEqualFold(FieldThirdPartyOrderID, v))
}

// ThirdPartyOrderIDContainsFold applies the ContainsFold predicate on the "third_party_order_id" field.
func ThirdPartyOrderIDContainsFold(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldContainsFold(FieldThirdPartyOrderID, v))
}

// CredentialEQ applies the EQ predicate on the "credential" field.
func CredentialEQ(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldCredential, v))
}

// CredentialNEQ applies the NEQ predicate on the "credential" field.
func CredentialNEQ(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNEQ(FieldCredential, v))
}

// CredentialIn applies the In predicate on the "credential" field.
func CredentialIn(vs ...string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldIn(FieldCredential, vs...))
}

// CredentialNotIn applies the NotIn predicate on the "credential" field.
func CredentialNotIn(vs ...string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNotIn(FieldCredential, vs...))
}

// CredentialGT applies the GT predicate on the "credential" field.
func CredentialGT(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGT(FieldCredential, v))
}

// CredentialGTE applies the GTE predicate on the "credential" field.
func CredentialGTE(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGTE(FieldCredential, v))
}

// CredentialLT applies the LT predicate on the "credential" field.
func CredentialLT(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLT(FieldCredential, v))
}

// CredentialLTE applies the LTE predicate on the "credential" field.
func CredentialLTE(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLTE(FieldCredential, v))
}

// CredentialContains applies the Contains predicate on the "credential" field.
func CredentialContains(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldContains(FieldCredential, v))
}

// CredentialHasPrefix applies the HasPrefix predicate on the "credential" field.
func CredentialHasPrefix(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldHasPrefix(FieldCredential, v))
}

// CredentialHasSuffix applies the HasSuffix predicate on the "credential" field.
func CredentialHasSuffix(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldHasSuffix(FieldCredential, v))
}

// CredentialIsNil applies the IsNil predicate on the "credential" field.
func CredentialIsNil() predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldIsNull(FieldCredential))
}

// CredentialNotNil applies the NotNil predicate on the "credential" field.
func CredentialNotNil() predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNotNull(FieldCredential))
}

// CredentialEqualFold applies the EqualFold predicate on the "credential" field.
func CredentialEqualFold(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEqualFold(FieldCredential, v))
}

// CredentialContainsFold applies the ContainsFold predicate on the "credential" field.
func CredentialContainsFold(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldContainsFold(FieldCredential, v))
}

// CredentialHashEQ applies the EQ predicate on the "credential_hash" field.
func CredentialHashEQ(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldCredentialHash, v))
}

// CredentialHashNEQ applies the NEQ predicate on the "credential_hash" field.
func CredentialHashNEQ(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNEQ(FieldCredentialHash, v))
}

// CredentialHashIn applies the In predicate on the "credential_hash" field.
func CredentialHashIn(vs ...string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldIn(FieldCredentialHash, vs...))
}

// CredentialHashNotIn applies the NotIn predicate on the "credential_hash" field.
func CredentialHashNotIn(vs ...string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNotIn(FieldCredentialHash, vs...))
}

// CredentialHashGT applies the GT predicate on the "credential_hash" field.
func CredentialHashGT(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGT(FieldCredentialHash, v))
}

// CredentialHashGTE applies the GTE predicate on the "credential_hash" field.
func CredentialHashGTE(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGTE(FieldCredentialHash, v))
}

// CredentialHashLT applies the LT predicate on the "credential_hash" field.
func CredentialHashLT(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLT(FieldCredentialHash, v))
}

// CredentialHashLTE applies the LTE predicate on the "credential_hash" field.
func CredentialHashLTE(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLTE(FieldCredentialHash, v))
}

// CredentialHashContains applies the Contains predicate on the "credential_hash" field.
func CredentialHashContains(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldContains(FieldCredentialHash, v))
}

// CredentialHashHasPrefix applies the HasPrefix predicate on the "credential_hash" field.
func CredentialHashHasPrefix(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldHasPrefix(FieldCredentialHash, v))
}

// CredentialHashHasSuffix applies the HasSuffix predicate on the "credential_hash" field.
func CredentialHashHasSuffix(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldHasSuffix(FieldCredentialHash, v))
}

// CredentialHashIsNil applies the IsNil predicate on the "credential_hash" field.
func CredentialHashIsNil() predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldIsNull(FieldCredentialHash))
}

// CredentialHashNotNil applies the NotNil predicate on the "credential_hash" field.
func CredentialHashNotNil() predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNotNull(FieldCredentialHash))
}

// CredentialHashEqualFold applies the EqualFold predicate on the "credential_hash" field.
func CredentialHashEqualFold(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEqualFold(FieldCredentialHash, v))
}

// CredentialHashContainsFold applies the ContainsFold predicate on the "credential_hash" field.
func CredentialHashContainsFold(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldContainsFold(FieldCredentialHash, v))
}

// RewardsIsNil applies the IsNil predicate on the "rewards" field.
func RewardsIsNil() predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldIsNull(FieldRewards))
}

// RewardsNotNil applies the NotNil predicate on the "rewards" field.
func RewardsNotNil() predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNotNull(FieldRewards))
}

// RetryTimesEQ applies the EQ predicate on the "retry_times" field.
func RetryTimesEQ(v int32) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldRetryTimes, v))
}

// RetryTimesNEQ applies the NEQ predicate on the "retry_times" field.
func RetryTimesNEQ(v int32) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNEQ(FieldRetryTimes, v))
}

// RetryTimesIn applies the In predicate on the "retry_times" field.
func RetryTimesIn(vs ...int32) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldIn(FieldRetryTimes, vs...))
}

// RetryTimesNotIn applies the NotIn predicate on the "retry_times" field.
func RetryTimesNotIn(vs ...int32) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNotIn(FieldRetryTimes, vs...))
}

// RetryTimesGT applies the GT predicate on the "retry_times" field.
func RetryTimesGT(v int32) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGT(FieldRetryTimes, v))
}

// RetryTimesGTE applies the GTE predicate on the "retry_times" field.
func RetryTimesGTE(v int32) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGTE(FieldRetryTimes, v))
}

// RetryTimesLT applies the LT predicate on the "retry_times" field.
func RetryTimesLT(v int32) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLT(FieldRetryTimes, v))
}

// RetryTimesLTE applies the LTE predicate on the "retry_times" field.
func RetryTimesLTE(v int32) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLTE(FieldRetryTimes, v))
}

// CancelReasonEQ applies the EQ predicate on the "cancel_reason" field.
func CancelReasonEQ(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldCancelReason, v))
}

// CancelReasonNEQ applies the NEQ predicate on the "cancel_reason" field.
func CancelReasonNEQ(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNEQ(FieldCancelReason, v))
}

// CancelReasonIn applies the In predicate on the "cancel_reason" field.
func CancelReasonIn(vs ...string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldIn(FieldCancelReason, vs...))
}

// CancelReasonNotIn applies the NotIn predicate on the "cancel_reason" field.
func CancelReasonNotIn(vs ...string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNotIn(FieldCancelReason, vs...))
}

// CancelReasonGT applies the GT predicate on the "cancel_reason" field.
func CancelReasonGT(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGT(FieldCancelReason, v))
}

// CancelReasonGTE applies the GTE predicate on the "cancel_reason" field.
func CancelReasonGTE(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGTE(FieldCancelReason, v))
}

// CancelReasonLT applies the LT predicate on the "cancel_reason" field.
func CancelReasonLT(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLT(FieldCancelReason, v))
}

// CancelReasonLTE applies the LTE predicate on the "cancel_reason" field.
func CancelReasonLTE(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLTE(FieldCancelReason, v))
}

// CancelReasonContains applies the Contains predicate on the "cancel_reason" field.
func CancelReasonContains(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldContains(FieldCancelReason, v))
}

// CancelReasonHasPrefix applies the HasPrefix predicate on the "cancel_reason" field.
func CancelReasonHasPrefix(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldHasPrefix(FieldCancelReason, v))
}

// CancelReasonHasSuffix applies the HasSuffix predicate on the "cancel_reason" field.
func CancelReasonHasSuffix(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldHasSuffix(FieldCancelReason, v))
}

// CancelReasonEqualFold applies the EqualFold predicate on the "cancel_reason" field.
func CancelReasonEqualFold(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEqualFold(FieldCancelReason, v))
}

// CancelReasonContainsFold applies the ContainsFold predicate on the "cancel_reason" field.
func CancelReasonContainsFold(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldContainsFold(FieldCancelReason, v))
}

// RefundReasonEQ applies the EQ predicate on the "refund_reason" field.
func RefundReasonEQ(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldRefundReason, v))
}

// RefundReasonNEQ applies the NEQ predicate on the "refund_reason" field.
func RefundReasonNEQ(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNEQ(FieldRefundReason, v))
}

// RefundReasonIn applies the In predicate on the "refund_reason" field.
func RefundReasonIn(vs ...string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldIn(FieldRefundReason, vs...))
}

// RefundReasonNotIn applies the NotIn predicate on the "refund_reason" field.
func RefundReasonNotIn(vs ...string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNotIn(FieldRefundReason, vs...))
}

// RefundReasonGT applies the GT predicate on the "refund_reason" field.
func RefundReasonGT(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGT(FieldRefundReason, v))
}

// RefundReasonGTE applies the GTE predicate on the "refund_reason" field.
func RefundReasonGTE(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGTE(FieldRefundReason, v))
}

// RefundReasonLT applies the LT predicate on the "refund_reason" field.
func RefundReasonLT(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLT(FieldRefundReason, v))
}

// RefundReasonLTE applies the LTE predicate on the "refund_reason" field.
func RefundReasonLTE(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLTE(FieldRefundReason, v))
}

// RefundReasonContains applies the Contains predicate on the "refund_reason" field.
func RefundReasonContains(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldContains(FieldRefundReason, v))
}

// RefundReasonHasPrefix applies the HasPrefix predicate on the "refund_reason" field.
func RefundReasonHasPrefix(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldHasPrefix(FieldRefundReason, v))
}

// RefundReasonHasSuffix applies the HasSuffix predicate on the "refund_reason" field.
func RefundReasonHasSuffix(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldHasSuffix(FieldRefundReason, v))
}

// RefundReasonEqualFold applies the EqualFold predicate on the "refund_reason" field.
func RefundReasonEqualFold(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEqualFold(FieldRefundReason, v))
}

// RefundReasonContainsFold applies the ContainsFold predicate on the "refund_reason" field.
func RefundReasonContainsFold(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldContainsFold(FieldRefundReason, v))
}

// IsSandboxEQ applies the EQ predicate on the "is_sandbox" field.
func IsSandboxEQ(v bool) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldIsSandbox, v))
}

// IsSandboxNEQ applies the NEQ predicate on the "is_sandbox" field.
func IsSandboxNEQ(v bool) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNEQ(FieldIsSandbox, v))
}

// CreateAtUnixEQ applies the EQ predicate on the "create_at_unix" field.
func CreateAtUnixEQ(v int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldCreateAtUnix, v))
}

// CreateAtUnixNEQ applies the NEQ predicate on the "create_at_unix" field.
func CreateAtUnixNEQ(v int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNEQ(FieldCreateAtUnix, v))
}

// CreateAtUnixIn applies the In predicate on the "create_at_unix" field.
func CreateAtUnixIn(vs ...int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldIn(FieldCreateAtUnix, vs...))
}

// CreateAtUnixNotIn applies the NotIn predicate on the "create_at_unix" field.
func CreateAtUnixNotIn(vs ...int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNotIn(FieldCreateAtUnix, vs...))
}

// CreateAtUnixGT applies the GT predicate on the "create_at_unix" field.
func CreateAtUnixGT(v int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGT(FieldCreateAtUnix, v))
}

// CreateAtUnixGTE applies the GTE predicate on the "create_at_unix" field.
func CreateAtUnixGTE(v int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGTE(FieldCreateAtUnix, v))
}

// CreateAtUnixLT applies the LT predicate on the "create_at_unix" field.
func CreateAtUnixLT(v int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLT(FieldCreateAtUnix, v))
}

// CreateAtUnixLTE applies the LTE predicate on the "create_at_unix" field.
func CreateAtUnixLTE(v int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLTE(FieldCreateAtUnix, v))
}

// UpdateAtUnixEQ applies the EQ predicate on the "update_at_unix" field.
func UpdateAtUnixEQ(v int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldUpdateAtUnix, v))
}

// UpdateAtUnixNEQ applies the NEQ predicate on the "update_at_unix" field.
func UpdateAtUnixNEQ(v int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNEQ(FieldUpdateAtUnix, v))
}

// UpdateAtUnixIn applies the In predicate on the "update_at_unix" field.
func UpdateAtUnixIn(vs ...int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldIn(FieldUpdateAtUnix, vs...))
}

// UpdateAtUnixNotIn applies the NotIn predicate on the "update_at_unix" field.
func UpdateAtUnixNotIn(vs ...int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNotIn(FieldUpdateAtUnix, vs...))
}

// UpdateAtUnixGT applies the GT predicate on the "update_at_unix" field.
func UpdateAtUnixGT(v int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGT(FieldUpdateAtUnix, v))
}

// UpdateAtUnixGTE applies the GTE predicate on the "update_at_unix" field.
func UpdateAtUnixGTE(v int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGTE(FieldUpdateAtUnix, v))
}

// UpdateAtUnixLT applies the LT predicate on the "update_at_unix" field.
func UpdateAtUnixLT(v int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLT(FieldUpdateAtUnix, v))
}

// UpdateAtUnixLTE applies the LTE predicate on the "update_at_unix" field.
func UpdateAtUnixLTE(v int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLTE(FieldUpdateAtUnix, v))
}

// PayAtUnixEQ applies the EQ predicate on the "pay_at_unix" field.
func PayAtUnixEQ(v int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldPayAtUnix, v))
}

// PayAtUnixNEQ applies the NEQ predicate on the "pay_at_unix" field.
func PayAtUnixNEQ(v int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNEQ(FieldPayAtUnix, v))
}

// PayAtUnixIn applies the In predicate on the "pay_at_unix" field.
func PayAtUnixIn(vs ...int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldIn(FieldPayAtUnix, vs...))
}

// PayAtUnixNotIn applies the NotIn predicate on the "pay_at_unix" field.
func PayAtUnixNotIn(vs ...int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNotIn(FieldPayAtUnix, vs...))
}

// PayAtUnixGT applies the GT predicate on the "pay_at_unix" field.
func PayAtUnixGT(v int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGT(FieldPayAtUnix, v))
}

// PayAtUnixGTE applies the GTE predicate on the "pay_at_unix" field.
func PayAtUnixGTE(v int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGTE(FieldPayAtUnix, v))
}

// PayAtUnixLT applies the LT predicate on the "pay_at_unix" field.
func PayAtUnixLT(v int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLT(FieldPayAtUnix, v))
}

// PayAtUnixLTE applies the LTE predicate on the "pay_at_unix" field.
func PayAtUnixLTE(v int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLTE(FieldPayAtUnix, v))
}

// RefundAtUnixEQ applies the EQ predicate on the "refund_at_unix" field.
func RefundAtUnixEQ(v int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldRefundAtUnix, v))
}

// RefundAtUnixNEQ applies the NEQ predicate on the "refund_at_unix" field.
func RefundAtUnixNEQ(v int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNEQ(FieldRefundAtUnix, v))
}

// RefundAtUnixIn applies the In predicate on the "refund_at_unix" field.
func RefundAtUnixIn(vs ...int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldIn(FieldRefundAtUnix, vs...))
}

// RefundAtUnixNotIn applies the NotIn predicate on the "refund_at_unix" field.
func RefundAtUnixNotIn(vs ...int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNotIn(FieldRefundAtUnix, vs...))
}

// RefundAtUnixGT applies the GT predicate on the "refund_at_unix" field.
func RefundAtUnixGT(v int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGT(FieldRefundAtUnix, v))
}

// RefundAtUnixGTE applies the GTE predicate on the "refund_at_unix" field.
func RefundAtUnixGTE(v int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGTE(FieldRefundAtUnix, v))
}

// RefundAtUnixLT applies the LT predicate on the "refund_at_unix" field.
func RefundAtUnixLT(v int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLT(FieldRefundAtUnix, v))
}

// RefundAtUnixLTE applies the LTE predicate on the "refund_at_unix" field.
func RefundAtUnixLTE(v int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLTE(FieldRefundAtUnix, v))
}

// CancelAtUnixEQ applies the EQ predicate on the "cancel_at_unix" field.
func CancelAtUnixEQ(v int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldCancelAtUnix, v))
}

// CancelAtUnixNEQ applies the NEQ predicate on the "cancel_at_unix" field.
func CancelAtUnixNEQ(v int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNEQ(FieldCancelAtUnix, v))
}

// CancelAtUnixIn applies the In predicate on the "cancel_at_unix" field.
func CancelAtUnixIn(vs ...int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldIn(FieldCancelAtUnix, vs...))
}

// CancelAtUnixNotIn applies the NotIn predicate on the "cancel_at_unix" field.
func CancelAtUnixNotIn(vs ...int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNotIn(FieldCancelAtUnix, vs...))
}

// CancelAtUnixGT applies the GT predicate on the "cancel_at_unix" field.
func CancelAtUnixGT(v int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGT(FieldCancelAtUnix, v))
}

// CancelAtUnixGTE applies the GTE predicate on the "cancel_at_unix" field.
func CancelAtUnixGTE(v int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGTE(FieldCancelAtUnix, v))
}

// CancelAtUnixLT applies the LT predicate on the "cancel_at_unix" field.
func CancelAtUnixLT(v int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLT(FieldCancelAtUnix, v))
}

// CancelAtUnixLTE applies the LTE predicate on the "cancel_at_unix" field.
func CancelAtUnixLTE(v int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLTE(FieldCancelAtUnix, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PaymentOrder) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PaymentOrder) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PaymentOrder) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.NotPredicates(p))
}
