// Code generated by ent, DO NOT EDIT.

package item

import (
	"entgo.io/ent/dialect/sql"
	"github.com/2comjie/taoxi-server/app/Api/items/internal/store/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Item {
	return predicate.Item(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Item {
	return predicate.Item(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Item {
	return predicate.Item(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Item {
	return predicate.Item(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Item {
	return predicate.Item(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Item {
	return predicate.Item(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Item {
	return predicate.Item(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Item {
	return predicate.Item(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Item {
	return predicate.Item(sql.FieldLTE(FieldID, id))
}

// UID applies equality check predicate on the "uid" field. It's identical to UIDEQ.
func UID(v uint64) predicate.Item {
	return predicate.Item(sql.FieldEQ(FieldUID, v))
}

// ItemID applies equality check predicate on the "item_id" field. It's identical to ItemIDEQ.
func ItemID(v int32) predicate.Item {
	return predicate.Item(sql.FieldEQ(FieldItemID, v))
}

// Count applies equality check predicate on the "count" field. It's identical to CountEQ.
func Count(v int64) predicate.Item {
	return predicate.Item(sql.FieldEQ(FieldCount, v))
}

// UsedCount applies equality check predicate on the "used_count" field. It's identical to UsedCountEQ.
func UsedCount(v int64) predicate.Item {
	return predicate.Item(sql.FieldEQ(FieldUsedCount, v))
}

// ExpireAtUnix applies equality check predicate on the "expire_at_unix" field. It's identical to ExpireAtUnixEQ.
func ExpireAtUnix(v int64) predicate.Item {
	return predicate.Item(sql.FieldEQ(FieldExpireAtUnix, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.Item {
	return predicate.Item(sql.FieldEQ(FieldSource, v))
}

// CreateAtUnix applies equality check predicate on the "create_at_unix" field. It's identical to CreateAtUnixEQ.
func CreateAtUnix(v int64) predicate.Item {
	return predicate.Item(sql.FieldEQ(FieldCreateAtUnix, v))
}

// UpdateAtUnix applies equality check predicate on the "update_at_unix" field. It's identical to UpdateAtUnixEQ.
func UpdateAtUnix(v int64) predicate.Item {
	return predicate.Item(sql.FieldEQ(FieldUpdateAtUnix, v))
}

// UIDEQ applies the EQ predicate on the "uid" field.
func UIDEQ(v uint64) predicate.Item {
	return predicate.Item(sql.FieldEQ(FieldUID, v))
}

// UIDNEQ applies the NEQ predicate on the "uid" field.
func UIDNEQ(v uint64) predicate.Item {
	return predicate.Item(sql.FieldNEQ(FieldUID, v))
}

// UIDIn applies the In predicate on the "uid" field.
func UIDIn(vs ...uint64) predicate.Item {
	return predicate.Item(sql.FieldIn(FieldUID, vs...))
}

// UIDNotIn applies the NotIn predicate on the "uid" field.
func UIDNotIn(vs ...uint64) predicate.Item {
	return predicate.Item(sql.FieldNotIn(FieldUID, vs...))
}

// UIDGT applies the GT predicate on the "uid" field.
func UIDGT(v uint64) predicate.Item {
	return predicate.Item(sql.FieldGT(FieldUID, v))
}

// UIDGTE applies the GTE predicate on the "uid" field.
func UIDGTE(v uint64) predicate.Item {
	return predicate.Item(sql.FieldGTE(FieldUID, v))
}

// UIDLT applies the LT predicate on the "uid" field.
func UIDLT(v uint64) predicate.Item {
	return predicate.Item(sql.FieldLT(FieldUID, v))
}

// UIDLTE applies the LTE predicate on the "uid" field.
func UIDLTE(v uint64) predicate.Item {
	return predicate.Item(sql.FieldLTE(FieldUID, v))
}

// ItemIDEQ applies the EQ predicate on the "item_id" field.
func ItemIDEQ(v int32) predicate.Item {
	return predicate.Item(sql.FieldEQ(FieldItemID, v))
}

// ItemIDNEQ applies the NEQ predicate on the "item_id" field.
func ItemIDNEQ(v int32) predicate.Item {
	return predicate.Item(sql.FieldNEQ(FieldItemID, v))
}

// ItemIDIn applies the In predicate on the "item_id" field.
func ItemIDIn(vs ...int32) predicate.Item {
	return predicate.Item(sql.FieldIn(FieldItemID, vs...))
}

// ItemIDNotIn applies the NotIn predicate on the "item_id" field.
func ItemIDNotIn(vs ...int32) predicate.Item {
	return predicate.Item(sql.FieldNotIn(FieldItemID, vs...))
}

// ItemIDGT applies the GT predicate on the "item_id" field.
func ItemIDGT(v int32) predicate.Item {
	return predicate.Item(sql.FieldGT(FieldItemID, v))
}

// ItemIDGTE applies the GTE predicate on the "item_id" field.
func ItemIDGTE(v int32) predicate.Item {
	return predicate.Item(sql.FieldGTE(FieldItemID, v))
}

// ItemIDLT applies the LT predicate on the "item_id" field.
func ItemIDLT(v int32) predicate.Item {
	return predicate.Item(sql.FieldLT(FieldItemID, v))
}

// ItemIDLTE applies the LTE predicate on the "item_id" field.
func ItemIDLTE(v int32) predicate.Item {
	return predicate.Item(sql.FieldLTE(FieldItemID, v))
}

// CountEQ applies the EQ predicate on the "count" field.
func CountEQ(v int64) predicate.Item {
	return predicate.Item(sql.FieldEQ(FieldCount, v))
}

// CountNEQ applies the NEQ predicate on the "count" field.
func CountNEQ(v int64) predicate.Item {
	return predicate.Item(sql.FieldNEQ(FieldCount, v))
}

// CountIn applies the In predicate on the "count" field.
func CountIn(vs ...int64) predicate.Item {
	return predicate.Item(sql.FieldIn(FieldCount, vs...))
}

// CountNotIn applies the NotIn predicate on the "count" field.
func CountNotIn(vs ...int64) predicate.Item {
	return predicate.Item(sql.FieldNotIn(FieldCount, vs...))
}

// CountGT applies the GT predicate on the "count" field.
func CountGT(v int64) predicate.Item {
	return predicate.Item(sql.FieldGT(FieldCount, v))
}

// CountGTE applies the GTE predicate on the "count" field.
func CountGTE(v int64) predicate.Item {
	return predicate.Item(sql.FieldGTE(FieldCount, v))
}

// CountLT applies the LT predicate on the "count" field.
func CountLT(v int64) predicate.Item {
	return predicate.Item(sql.FieldLT(FieldCount, v))
}

// CountLTE applies the LTE predicate on the "count" field.
func CountLTE(v int64) predicate.Item {
	return predicate.Item(sql.FieldLTE(FieldCount, v))
}

// UsedCountEQ applies the EQ predicate on the "used_count" field.
func UsedCountEQ(v int64) predicate.Item {
	return predicate.Item(sql.FieldEQ(FieldUsedCount, v))
}

// UsedCountNEQ applies the NEQ predicate on the "used_count" field.
func UsedCountNEQ(v int64) predicate.Item {
	return predicate.Item(sql.FieldNEQ(FieldUsedCount, v))
}

// UsedCountIn applies the In predicate on the "used_count" field.
func UsedCountIn(vs ...int64) predicate.Item {
	return predicate.Item(sql.FieldIn(FieldUsedCount, vs...))
}

// UsedCountNotIn applies the NotIn predicate on the "used_count" field.
func UsedCountNotIn(vs ...int64) predicate.Item {
	return predicate.Item(sql.FieldNotIn(FieldUsedCount, vs...))
}

// UsedCountGT applies the GT predicate on the "used_count" field.
func UsedCountGT(v int64) predicate.Item {
	return predicate.Item(sql.FieldGT(FieldUsedCount, v))
}

// UsedCountGTE applies the GTE predicate on the "used_count" field.
func UsedCountGTE(v int64) predicate.Item {
	return predicate.Item(sql.FieldGTE(FieldUsedCount, v))
}

// UsedCountLT applies the LT predicate on the "used_count" field.
func UsedCountLT(v int64) predicate.Item {
	return predicate.Item(sql.FieldLT(FieldUsedCount, v))
}

// UsedCountLTE applies the LTE predicate on the "used_count" field.
func UsedCountLTE(v int64) predicate.Item {
	return predicate.Item(sql.FieldLTE(FieldUsedCount, v))
}

// ExpireAtUnixEQ applies the EQ predicate on the "expire_at_unix" field.
func ExpireAtUnixEQ(v int64) predicate.Item {
	return predicate.Item(sql.FieldEQ(FieldExpireAtUnix, v))
}

// ExpireAtUnixNEQ applies the NEQ predicate on the "expire_at_unix" field.
func ExpireAtUnixNEQ(v int64) predicate.Item {
	return predicate.Item(sql.FieldNEQ(FieldExpireAtUnix, v))
}

// ExpireAtUnixIn applies the In predicate on the "expire_at_unix" field.
func ExpireAtUnixIn(vs ...int64) predicate.Item {
	return predicate.Item(sql.FieldIn(FieldExpireAtUnix, vs...))
}

// ExpireAtUnixNotIn applies the NotIn predicate on the "expire_at_unix" field.
func ExpireAtUnixNotIn(vs ...int64) predicate.Item {
	return predicate.Item(sql.FieldNotIn(FieldExpireAtUnix, vs...))
}

// ExpireAtUnixGT applies the GT predicate on the "expire_at_unix" field.
func ExpireAtUnixGT(v int64) predicate.Item {
	return predicate.Item(sql.FieldGT(FieldExpireAtUnix, v))
}

// ExpireAtUnixGTE applies the GTE predicate on the "expire_at_unix" field.
func ExpireAtUnixGTE(v int64) predicate.Item {
	return predicate.Item(sql.FieldGTE(FieldExpireAtUnix, v))
}

// ExpireAtUnixLT applies the LT predicate on the "expire_at_unix" field.
func ExpireAtUnixLT(v int64) predicate.Item {
	return predicate.Item(sql.FieldLT(FieldExpireAtUnix, v))
}

// ExpireAtUnixLTE applies the LTE predicate on the "expire_at_unix" field.
func ExpireAtUnixLTE(v int64) predicate.Item {
	return predicate.Item(sql.FieldLTE(FieldExpireAtUnix, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.Item {
	return predicate.Item(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.Item {
	return predicate.Item(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.Item {
	return predicate.Item(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.Item {
	return predicate.Item(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.Item {
	return predicate.Item(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.Item {
	return predicate.Item(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.Item {
	return predicate.Item(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.Item {
	return predicate.Item(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.Item {
	return predicate.Item(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.Item {
	return predicate.Item(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.Item {
	return predicate.Item(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.Item {
	return predicate.Item(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.Item {
	return predicate.Item(sql.FieldContainsFold(FieldSource, v))
}

// CreateAtUnixEQ applies the EQ predicate on the "create_at_unix" field.
func CreateAtUnixEQ(v int64) predicate.Item {
	return predicate.Item(sql.FieldEQ(FieldCreateAtUnix, v))
}

// CreateAtUnixNEQ applies the NEQ predicate on the "create_at_unix" field.
func CreateAtUnixNEQ(v int64) predicate.Item {
	return predicate.Item(sql.FieldNEQ(FieldCreateAtUnix, v))
}

// CreateAtUnixIn applies the In predicate on the "create_at_unix" field.
func CreateAtUnixIn(vs ...int64) predicate.Item {
	return predicate.Item(sql.FieldIn(FieldCreateAtUnix, vs...))
}

// CreateAtUnixNotIn applies the NotIn predicate on the "create_at_unix" field.
func CreateAtUnixNotIn(vs ...int64) predicate.Item {
	return predicate.Item(sql.FieldNotIn(FieldCreateAtUnix, vs...))
}

// CreateAtUnixGT applies the GT predicate on the "create_at_unix" field.
func CreateAtUnixGT(v int64) predicate.Item {
	return predicate.Item(sql.FieldGT(FieldCreateAtUnix, v))
}

// CreateAtUnixGTE applies the GTE predicate on the "create_at_unix" field.
func CreateAtUnixGTE(v int64) predicate.Item {
	return predicate.Item(sql.FieldGTE(FieldCreateAtUnix, v))
}

// CreateAtUnixLT applies the LT predicate on the "create_at_unix" field.
func CreateAtUnixLT(v int64) predicate.Item {
	return predicate.Item(sql.FieldLT(FieldCreateAtUnix, v))
}

// CreateAtUnixLTE applies the LTE predicate on the "create_at_unix" field.
func CreateAtUnixLTE(v int64) predicate.Item {
	return predicate.Item(sql.FieldLTE(FieldCreateAtUnix, v))
}

// UpdateAtUnixEQ applies the EQ predicate on the "update_at_unix" field.
func UpdateAtUnixEQ(v int64) predicate.Item {
	return predicate.Item(sql.FieldEQ(FieldUpdateAtUnix, v))
}

// UpdateAtUnixNEQ applies the NEQ predicate on the "update_at_unix" field.
func UpdateAtUnixNEQ(v int64) predicate.Item {
	return predicate.Item(sql.FieldNEQ(FieldUpdateAtUnix, v))
}

// UpdateAtUnixIn applies the In predicate on the "update_at_unix" field.
func UpdateAtUnixIn(vs ...int64) predicate.Item {
	return predicate.Item(sql.FieldIn(FieldUpdateAtUnix, vs...))
}

// UpdateAtUnixNotIn applies the NotIn predicate on the "update_at_unix" field.
func UpdateAtUnixNotIn(vs ...int64) predicate.Item {
	return predicate.Item(sql.FieldNotIn(FieldUpdateAtUnix, vs...))
}

// UpdateAtUnixGT applies the GT predicate on the "update_at_unix" field.
func UpdateAtUnixGT(v int64) predicate.Item {
	return predicate.Item(sql.FieldGT(FieldUpdateAtUnix, v))
}

// UpdateAtUnixGTE applies the GTE predicate on the "update_at_unix" field.
func UpdateAtUnixGTE(v int64) predicate.Item {
	return predicate.Item(sql.FieldGTE(FieldUpdateAtUnix, v))
}

// UpdateAtUnixLT applies the LT predicate on the "update_at_unix" field.
func UpdateAtUnixLT(v int64) predicate.Item {
	return predicate.Item(sql.FieldLT(FieldUpdateAtUnix, v))
}

// UpdateAtUnixLTE applies the LTE predicate on the "update_at_unix" field.
func UpdateAtUnixLTE(v int64) predicate.Item {
	return predicate.Item(sql.FieldLTE(FieldUpdateAtUnix, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Item) predicate.Item {
	return predicate.Item(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Item) predicate.Item {
	return predicate.Item(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Item) predicate.Item {
	return predicate.Item(sql.NotPredicates(p))
}
