### 创建 Google Play 订单
POST {{baseUrl}}/api/payment/create_order
Content-Type: application/json
format: 1
lang: zh-CN
token: {{accessToken}}

{
  "product_id": 1001,
  "payment_type": 2
}

### 上传 Google Play purchaseToken
# 将 googlePurchaseToken 替换为客户端购买成功后返回的 purchaseToken
POST {{baseUrl}}/api/payment/upload_receipt
Content-Type: application/json
format: 1
lang: zh-CN
token: {{accessToken}}

{
  "payment_type": 2,
  "credential": "111"
}
