### 首次游客登录：guest_id 为空时由服务端生成
POST {{baseUrl}}/api/login
Content-Type: application/json
format: 1
lang: zh-CN

{
  "login_type": 1,
  "guest_id": "cusdsad"
}

### 已有游客再次登录：使用上一个请求返回的 openid
POST {{baseUrl}}/api/login
Content-Type: application/json
format: 1
lang: zh-CN

{
  "login_type": 1,
  "guest_id": ""
}