// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/2comjie/taoxi-server/app/Api/login/internal/store/ent/account"
)

// AccountCreate is the builder for creating a Account entity.
type AccountCreate struct {
	config
	mutation *AccountMutation
	hooks    []Hook
}

// SetIsDeleted sets the "is_deleted" field.
func (_c *AccountCreate) SetIsDeleted(v bool) *AccountCreate {
	_c.mutation.SetIsDeleted(v)
	return _c
}

// SetNillableIsDeleted sets the "is_deleted" field if the given value is not nil.
func (_c *AccountCreate) SetNillableIsDeleted(v *bool) *AccountCreate {
	if v != nil {
		_c.SetIsDeleted(*v)
	}
	return _c
}

// SetCreateAtUnix sets the "create_at_unix" field.
func (_c *AccountCreate) SetCreateAtUnix(v int64) *AccountCreate {
	_c.mutation.SetCreateAtUnix(v)
	return _c
}

// SetNillableCreateAtUnix sets the "create_at_unix" field if the given value is not nil.
func (_c *AccountCreate) SetNillableCreateAtUnix(v *int64) *AccountCreate {
	if v != nil {
		_c.SetCreateAtUnix(*v)
	}
	return _c
}

// SetUpdateAtUnix sets the "update_at_unix" field.
func (_c *AccountCreate) SetUpdateAtUnix(v int64) *AccountCreate {
	_c.mutation.SetUpdateAtUnix(v)
	return _c
}

// SetNillableUpdateAtUnix sets the "update_at_unix" field if the given value is not nil.
func (_c *AccountCreate) SetNillableUpdateAtUnix(v *int64) *AccountCreate {
	if v != nil {
		_c.SetUpdateAtUnix(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AccountCreate) SetID(v uint64) *AccountCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the AccountMutation object of the builder.
func (_c *AccountCreate) Mutation() *AccountMutation {
	return _c.mutation
}

// Save creates the Account in the database.
func (_c *AccountCreate) Save(ctx context.Context) (*Account, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccountCreate) SaveX(ctx context.Context) *Account {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccountCreate) defaults() {
	if _, ok := _c.mutation.IsDeleted(); !ok {
		v := account.DefaultIsDeleted
		_c.mutation.SetIsDeleted(v)
	}
	if _, ok := _c.mutation.CreateAtUnix(); !ok {
		v := account.DefaultCreateAtUnix()
		_c.mutation.SetCreateAtUnix(v)
	}
	if _, ok := _c.mutation.UpdateAtUnix(); !ok {
		v := account.DefaultUpdateAtUnix()
		_c.mutation.SetUpdateAtUnix(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccountCreate) check() error {
	if _, ok := _c.mutation.IsDeleted(); !ok {
		return &ValidationError{Name: "is_deleted", err: errors.New(`ent: missing required field "Account.is_deleted"`)}
	}
	if _, ok := _c.mutation.CreateAtUnix(); !ok {
		return &ValidationError{Name: "create_at_unix", err: errors.New(`ent: missing required field "Account.create_at_unix"`)}
	}
	if _, ok := _c.mutation.UpdateAtUnix(); !ok {
		return &ValidationError{Name: "update_at_unix", err: errors.New(`ent: missing required field "Account.update_at_unix"`)}
	}
	return nil
}

func (_c *AccountCreate) sqlSave(ctx context.Context) (*Account, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccountCreate) createSpec() (*Account, *sqlgraph.CreateSpec) {
	var (
		_node = &Account{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(account.Table, sqlgraph.NewFieldSpec(account.FieldID, field.TypeUint64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.IsDeleted(); ok {
		_spec.SetField(account.FieldIsDeleted, field.TypeBool, value)
		_node.IsDeleted = value
	}
	if value, ok := _c.mutation.CreateAtUnix(); ok {
		_spec.SetField(account.FieldCreateAtUnix, field.TypeInt64, value)
		_node.CreateAtUnix = value
	}
	if value, ok := _c.mutation.UpdateAtUnix(); ok {
		_spec.SetField(account.FieldUpdateAtUnix, field.TypeInt64, value)
		_node.UpdateAtUnix = value
	}
	return _node, _spec
}

// AccountCreateBulk is the builder for creating many Account entities in bulk.
type AccountCreateBulk struct {
	config
	err      error
	builders []*AccountCreate
}

// Save creates the Account entities in the database.
func (_c *AccountCreateBulk) Save(ctx context.Context) ([]*Account, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Account, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccountCreateBulk) SaveX(ctx context.Context) []*Account {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
