// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/2comjie/taoxi-server/app/Api/login/internal/store/ent/identity"
)

// IdentityCreate is the builder for creating a Identity entity.
type IdentityCreate struct {
	config
	mutation *IdentityMutation
	hooks    []Hook
}

// SetUID sets the "uid" field.
func (_c *IdentityCreate) SetUID(v uint64) *IdentityCreate {
	_c.mutation.SetUID(v)
	return _c
}

// SetLoginType sets the "login_type" field.
func (_c *IdentityCreate) SetLoginType(v int32) *IdentityCreate {
	_c.mutation.SetLoginType(v)
	return _c
}

// SetAppID sets the "app_id" field.
func (_c *IdentityCreate) SetAppID(v string) *IdentityCreate {
	_c.mutation.SetAppID(v)
	return _c
}

// SetOpenID sets the "open_id" field.
func (_c *IdentityCreate) SetOpenID(v string) *IdentityCreate {
	_c.mutation.SetOpenID(v)
	return _c
}

// SetUnionID sets the "union_id" field.
func (_c *IdentityCreate) SetUnionID(v string) *IdentityCreate {
	_c.mutation.SetUnionID(v)
	return _c
}

// SetNillableUnionID sets the "union_id" field if the given value is not nil.
func (_c *IdentityCreate) SetNillableUnionID(v *string) *IdentityCreate {
	if v != nil {
		_c.SetUnionID(*v)
	}
	return _c
}

// SetCreateAtUnix sets the "create_at_unix" field.
func (_c *IdentityCreate) SetCreateAtUnix(v int64) *IdentityCreate {
	_c.mutation.SetCreateAtUnix(v)
	return _c
}

// SetNillableCreateAtUnix sets the "create_at_unix" field if the given value is not nil.
func (_c *IdentityCreate) SetNillableCreateAtUnix(v *int64) *IdentityCreate {
	if v != nil {
		_c.SetCreateAtUnix(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *IdentityCreate) SetID(v uint64) *IdentityCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the IdentityMutation object of the builder.
func (_c *IdentityCreate) Mutation() *IdentityMutation {
	return _c.mutation
}

// Save creates the Identity in the database.
func (_c *IdentityCreate) Save(ctx context.Context) (*Identity, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *IdentityCreate) SaveX(ctx context.Context) *Identity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IdentityCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IdentityCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *IdentityCreate) defaults() {
	if _, ok := _c.mutation.CreateAtUnix(); !ok {
		v := identity.DefaultCreateAtUnix()
		_c.mutation.SetCreateAtUnix(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *IdentityCreate) check() error {
	if _, ok := _c.mutation.UID(); !ok {
		return &ValidationError{Name: "uid", err: errors.New(`ent: missing required field "Identity.uid"`)}
	}
	if _, ok := _c.mutation.LoginType(); !ok {
		return &ValidationError{Name: "login_type", err: errors.New(`ent: missing required field "Identity.login_type"`)}
	}
	if _, ok := _c.mutation.AppID(); !ok {
		return &ValidationError{Name: "app_id", err: errors.New(`ent: missing required field "Identity.app_id"`)}
	}
	if v, ok := _c.mutation.AppID(); ok {
		if err := identity.AppIDValidator(v); err != nil {
			return &ValidationError{Name: "app_id", err: fmt.Errorf(`ent: validator failed for field "Identity.app_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OpenID(); !ok {
		return &ValidationError{Name: "open_id", err: errors.New(`ent: missing required field "Identity.open_id"`)}
	}
	if v, ok := _c.mutation.OpenID(); ok {
		if err := identity.OpenIDValidator(v); err != nil {
			return &ValidationError{Name: "open_id", err: fmt.Errorf(`ent: validator failed for field "Identity.open_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.UnionID(); ok {
		if err := identity.UnionIDValidator(v); err != nil {
			return &ValidationError{Name: "union_id", err: fmt.Errorf(`ent: validator failed for field "Identity.union_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreateAtUnix(); !ok {
		return &ValidationError{Name: "create_at_unix", err: errors.New(`ent: missing required field "Identity.create_at_unix"`)}
	}
	return nil
}

func (_c *IdentityCreate) sqlSave(ctx context.Context) (*Identity, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *IdentityCreate) createSpec() (*Identity, *sqlgraph.CreateSpec) {
	var (
		_node = &Identity{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(identity.Table, sqlgraph.NewFieldSpec(identity.FieldID, field.TypeUint64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.UID(); ok {
		_spec.SetField(identity.FieldUID, field.TypeUint64, value)
		_node.UID = value
	}
	if value, ok := _c.mutation.LoginType(); ok {
		_spec.SetField(identity.FieldLoginType, field.TypeInt32, value)
		_node.LoginType = value
	}
	if value, ok := _c.mutation.AppID(); ok {
		_spec.SetField(identity.FieldAppID, field.TypeString, value)
		_node.AppID = value
	}
	if value, ok := _c.mutation.OpenID(); ok {
		_spec.SetField(identity.FieldOpenID, field.TypeString, value)
		_node.OpenID = value
	}
	if value, ok := _c.mutation.UnionID(); ok {
		_spec.SetField(identity.FieldUnionID, field.TypeString, value)
		_node.UnionID = &value
	}
	if value, ok := _c.mutation.CreateAtUnix(); ok {
		_spec.SetField(identity.FieldCreateAtUnix, field.TypeInt64, value)
		_node.CreateAtUnix = value
	}
	return _node, _spec
}

// IdentityCreateBulk is the builder for creating many Identity entities in bulk.
type IdentityCreateBulk struct {
	config
	err      error
	builders []*IdentityCreate
}

// Save creates the Identity entities in the database.
func (_c *IdentityCreateBulk) Save(ctx context.Context) ([]*Identity, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Identity, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IdentityMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *IdentityCreateBulk) SaveX(ctx context.Context) []*Identity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IdentityCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IdentityCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
