// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/2comjie/taoxi-server/app/Api/login/internal/store/ent/identity"
)

// Identity is the model entity for the Identity schema.
type Identity struct {
	config `json:"-"`
	// ID of the ent.
	// 身份记录自增主键
	ID uint64 `json:"id,omitempty"`
	// 玩家UID
	UID uint64 `json:"uid,omitempty"`
	// 登录类型
	LoginType int32 `json:"login_type,omitempty"`
	// 第三方应用ID
	AppID string `json:"app_id,omitempty"`
	// 第三方账号ID
	OpenID string `json:"open_id,omitempty"`
	// 第三方跨应用账号ID
	UnionID *string `json:"union_id,omitempty"`
	// 创建时间，Unix秒
	CreateAtUnix int64 `json:"create_at_unix,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Identity) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case identity.FieldID, identity.FieldUID, identity.FieldLoginType, identity.FieldCreateAtUnix:
			values[i] = new(sql.NullInt64)
		case identity.FieldAppID, identity.FieldOpenID, identity.FieldUnionID:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Identity fields.
func (_m *Identity) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case identity.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint64(value.Int64)
		case identity.FieldUID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field uid", values[i])
			} else if value.Valid {
				_m.UID = uint64(value.Int64)
			}
		case identity.FieldLoginType:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field login_type", values[i])
			} else if value.Valid {
				_m.LoginType = int32(value.Int64)
			}
		case identity.FieldAppID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field app_id", values[i])
			} else if value.Valid {
				_m.AppID = value.String
			}
		case identity.FieldOpenID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field open_id", values[i])
			} else if value.Valid {
				_m.OpenID = value.String
			}
		case identity.FieldUnionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field union_id", values[i])
			} else if value.Valid {
				_m.UnionID = new(string)
				*_m.UnionID = value.String
			}
		case identity.FieldCreateAtUnix:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field create_at_unix", values[i])
			} else if value.Valid {
				_m.CreateAtUnix = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Identity.
// This includes values selected through modifiers, order, etc.
func (_m *Identity) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Identity.
// Note that you need to call Identity.Unwrap() before calling this method if this Identity
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Identity) Update() *IdentityUpdateOne {
	return NewIdentityClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Identity entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Identity) Unwrap() *Identity {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Identity is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Identity) String() string {
	var builder strings.Builder
	builder.WriteString("Identity(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("uid=")
	builder.WriteString(fmt.Sprintf("%v", _m.UID))
	builder.WriteString(", ")
	builder.WriteString("login_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.LoginType))
	builder.WriteString(", ")
	builder.WriteString("app_id=")
	builder.WriteString(_m.AppID)
	builder.WriteString(", ")
	builder.WriteString("open_id=")
	builder.WriteString(_m.OpenID)
	builder.WriteString(", ")
	if v := _m.UnionID; v != nil {
		builder.WriteString("union_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("create_at_unix=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreateAtUnix))
	builder.WriteByte(')')
	return builder.String()
}

// Identities is a parsable slice of Identity.
type Identities []*Identity
