// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/2comjie/taoxi-server/app/Api/login/internal/store/ent/playeridentity"
)

// PlayerIdentityCreate is the builder for creating a PlayerIdentity entity.
type PlayerIdentityCreate struct {
	config
	mutation *PlayerIdentityMutation
	hooks    []Hook
}

// SetUID sets the "uid" field.
func (_c *PlayerIdentityCreate) SetUID(v string) *PlayerIdentityCreate {
	_c.mutation.SetUID(v)
	return _c
}

// SetLoginType sets the "login_type" field.
func (_c *PlayerIdentityCreate) SetLoginType(v int32) *PlayerIdentityCreate {
	_c.mutation.SetLoginType(v)
	return _c
}

// SetAppID sets the "app_id" field.
func (_c *PlayerIdentityCreate) SetAppID(v string) *PlayerIdentityCreate {
	_c.mutation.SetAppID(v)
	return _c
}

// SetOpenID sets the "open_id" field.
func (_c *PlayerIdentityCreate) SetOpenID(v string) *PlayerIdentityCreate {
	_c.mutation.SetOpenID(v)
	return _c
}

// SetUnionID sets the "union_id" field.
func (_c *PlayerIdentityCreate) SetUnionID(v string) *PlayerIdentityCreate {
	_c.mutation.SetUnionID(v)
	return _c
}

// SetNillableUnionID sets the "union_id" field if the given value is not nil.
func (_c *PlayerIdentityCreate) SetNillableUnionID(v *string) *PlayerIdentityCreate {
	if v != nil {
		_c.SetUnionID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PlayerIdentityCreate) SetCreatedAt(v time.Time) *PlayerIdentityCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PlayerIdentityCreate) SetNillableCreatedAt(v *time.Time) *PlayerIdentityCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the PlayerIdentityMutation object of the builder.
func (_c *PlayerIdentityCreate) Mutation() *PlayerIdentityMutation {
	return _c.mutation
}

// Save creates the PlayerIdentity in the database.
func (_c *PlayerIdentityCreate) Save(ctx context.Context) (*PlayerIdentity, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PlayerIdentityCreate) SaveX(ctx context.Context) *PlayerIdentity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlayerIdentityCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlayerIdentityCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PlayerIdentityCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := playeridentity.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PlayerIdentityCreate) check() error {
	if _, ok := _c.mutation.UID(); !ok {
		return &ValidationError{Name: "uid", err: errors.New(`ent: missing required field "PlayerIdentity.uid"`)}
	}
	if v, ok := _c.mutation.UID(); ok {
		if err := playeridentity.UIDValidator(v); err != nil {
			return &ValidationError{Name: "uid", err: fmt.Errorf(`ent: validator failed for field "PlayerIdentity.uid": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LoginType(); !ok {
		return &ValidationError{Name: "login_type", err: errors.New(`ent: missing required field "PlayerIdentity.login_type"`)}
	}
	if _, ok := _c.mutation.AppID(); !ok {
		return &ValidationError{Name: "app_id", err: errors.New(`ent: missing required field "PlayerIdentity.app_id"`)}
	}
	if v, ok := _c.mutation.AppID(); ok {
		if err := playeridentity.AppIDValidator(v); err != nil {
			return &ValidationError{Name: "app_id", err: fmt.Errorf(`ent: validator failed for field "PlayerIdentity.app_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OpenID(); !ok {
		return &ValidationError{Name: "open_id", err: errors.New(`ent: missing required field "PlayerIdentity.open_id"`)}
	}
	if v, ok := _c.mutation.OpenID(); ok {
		if err := playeridentity.OpenIDValidator(v); err != nil {
			return &ValidationError{Name: "open_id", err: fmt.Errorf(`ent: validator failed for field "PlayerIdentity.open_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.UnionID(); ok {
		if err := playeridentity.UnionIDValidator(v); err != nil {
			return &ValidationError{Name: "union_id", err: fmt.Errorf(`ent: validator failed for field "PlayerIdentity.union_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PlayerIdentity.created_at"`)}
	}
	return nil
}

func (_c *PlayerIdentityCreate) sqlSave(ctx context.Context) (*PlayerIdentity, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PlayerIdentityCreate) createSpec() (*PlayerIdentity, *sqlgraph.CreateSpec) {
	var (
		_node = &PlayerIdentity{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(playeridentity.Table, sqlgraph.NewFieldSpec(playeridentity.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.UID(); ok {
		_spec.SetField(playeridentity.FieldUID, field.TypeString, value)
		_node.UID = value
	}
	if value, ok := _c.mutation.LoginType(); ok {
		_spec.SetField(playeridentity.FieldLoginType, field.TypeInt32, value)
		_node.LoginType = value
	}
	if value, ok := _c.mutation.AppID(); ok {
		_spec.SetField(playeridentity.FieldAppID, field.TypeString, value)
		_node.AppID = value
	}
	if value, ok := _c.mutation.OpenID(); ok {
		_spec.SetField(playeridentity.FieldOpenID, field.TypeString, value)
		_node.OpenID = value
	}
	if value, ok := _c.mutation.UnionID(); ok {
		_spec.SetField(playeridentity.FieldUnionID, field.TypeString, value)
		_node.UnionID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(playeridentity.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// PlayerIdentityCreateBulk is the builder for creating many PlayerIdentity entities in bulk.
type PlayerIdentityCreateBulk struct {
	config
	err      error
	builders []*PlayerIdentityCreate
}

// Save creates the PlayerIdentity entities in the database.
func (_c *PlayerIdentityCreateBulk) Save(ctx context.Context) ([]*PlayerIdentity, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PlayerIdentity, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PlayerIdentityMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PlayerIdentityCreateBulk) SaveX(ctx context.Context) []*PlayerIdentity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlayerIdentityCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlayerIdentityCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
