// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.2
// source: player/player_actor_rpc.proto

package pbPlayerActorRPC

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Route int32

const (
	Route_Unknown  Route = 0
	Route_GetState Route = 1
)

// Enum value maps for Route.
var (
	Route_name = map[int32]string{
		0: "Unknown",
		1: "GetState",
	}
	Route_value = map[string]int32{
		"Unknown":  0,
		"GetState": 1,
	}
)

func (x Route) Enum() *Route {
	p := new(Route)
	*p = x
	return p
}

func (x Route) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Route) Descriptor() protoreflect.EnumDescriptor {
	return file_player_player_actor_rpc_proto_enumTypes[0].Descriptor()
}

func (Route) Type() protoreflect.EnumType {
	return &file_player_player_actor_rpc_proto_enumTypes[0]
}

func (x Route) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Route.Descriptor instead.
func (Route) EnumDescriptor() ([]byte, []int) {
	return file_player_player_actor_rpc_proto_rawDescGZIP(), []int{0}
}

type GetStateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateReq) Reset() {
	*x = GetStateReq{}
	mi := &file_player_player_actor_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateReq) ProtoMessage() {}

func (x *GetStateReq) ProtoReflect() protoreflect.Message {
	mi := &file_player_player_actor_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateReq.ProtoReflect.Descriptor instead.
func (*GetStateReq) Descriptor() ([]byte, []int) {
	return file_player_player_actor_rpc_proto_rawDescGZIP(), []int{0}
}

type GetStateRsp struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Uid             uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	LastOfflineTime int64                  `protobuf:"varint,2,opt,name=last_offline_time,json=lastOfflineTime,proto3" json:"last_offline_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetStateRsp) Reset() {
	*x = GetStateRsp{}
	mi := &file_player_player_actor_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateRsp) ProtoMessage() {}

func (x *GetStateRsp) ProtoReflect() protoreflect.Message {
	mi := &file_player_player_actor_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateRsp.ProtoReflect.Descriptor instead.
func (*GetStateRsp) Descriptor() ([]byte, []int) {
	return file_player_player_actor_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *GetStateRsp) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GetStateRsp) GetLastOfflineTime() int64 {
	if x != nil {
		return x.LastOfflineTime
	}
	return 0
}

var File_player_player_actor_rpc_proto protoreflect.FileDescriptor

const file_player_player_actor_rpc_proto_rawDesc = "" +
	"\n" +
	"\x1dplayer/player_actor_rpc.proto\x12\x16taoxi.player.actor_rpc\"\r\n" +
	"\vGetStateReq\"K\n" +
	"\vGetStateRsp\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x12*\n" +
	"\x11last_offline_time\x18\x02 \x01(\x03R\x0flastOfflineTime*\"\n" +
	"\x05Route\x12\v\n" +
	"\aUnknown\x10\x00\x12\f\n" +
	"\bGetState\x10\x01BFZDgithub.com/2comjie/taoxi-server/pb/player/actor_rpc;pbPlayerActorRPCb\x06proto3"

var (
	file_player_player_actor_rpc_proto_rawDescOnce sync.Once
	file_player_player_actor_rpc_proto_rawDescData []byte
)

func file_player_player_actor_rpc_proto_rawDescGZIP() []byte {
	file_player_player_actor_rpc_proto_rawDescOnce.Do(func() {
		file_player_player_actor_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_player_player_actor_rpc_proto_rawDesc), len(file_player_player_actor_rpc_proto_rawDesc)))
	})
	return file_player_player_actor_rpc_proto_rawDescData
}

var file_player_player_actor_rpc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_player_player_actor_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_player_player_actor_rpc_proto_goTypes = []any{
	(Route)(0),          // 0: taoxi.player.actor_rpc.Route
	(*GetStateReq)(nil), // 1: taoxi.player.actor_rpc.GetStateReq
	(*GetStateRsp)(nil), // 2: taoxi.player.actor_rpc.GetStateRsp
}
var file_player_player_actor_rpc_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_player_player_actor_rpc_proto_init() }
func file_player_player_actor_rpc_proto_init() {
	if File_player_player_actor_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_player_player_actor_rpc_proto_rawDesc), len(file_player_player_actor_rpc_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_player_player_actor_rpc_proto_goTypes,
		DependencyIndexes: file_player_player_actor_rpc_proto_depIdxs,
		EnumInfos:         file_player_player_actor_rpc_proto_enumTypes,
		MessageInfos:      file_player_player_actor_rpc_proto_msgTypes,
	}.Build()
	File_player_player_actor_rpc_proto = out.File
	file_player_player_actor_rpc_proto_goTypes = nil
	file_player_player_actor_rpc_proto_depIdxs = nil
}
