// Code generated by protoc-gen-go-diff. DO NOT EDIT.
// protoc-gen-go-diff v0.1.0
// source: player/actor/actor.proto

package pbPlayerActor

import (
	diff "github.com/2comjie/nova/diff"
)

type PlayerApplyHooks struct {
	OnUidChanged             func(oldValue, newValue uint64)
	OnLastOfflineTimeChanged func(oldValue, newValue int64)
}

const playerStateDirtyUidWord uint32 = 0
const playerStateDirtyUidMask uint64 = 1
const playerStateDirtyLastOfflineTimeWord uint32 = 0
const playerStateDirtyLastOfflineTimeMask uint64 = 2

type PlayerState struct {
	value      *Player
	dirty      [1]uint64
	markParent func()
}

func NewPlayerState(value *Player) *PlayerState {
	return newPlayerState(value, nil)
}

func NewPlayerStateWithParent(value *Player, markParent func()) *PlayerState {
	return newPlayerState(value, markParent)
}

func newPlayerState(value *Player, markParent func()) *PlayerState {
	state := &PlayerState{value: value, markParent: markParent}
	return state
}

func (s *PlayerState) GetRawValue() *Player {
	return s.value
}

func (s *PlayerState) IsDirty() bool {
	return diff.AnyDirty(s.dirty[:])
}

func (s *PlayerState) GetUid() uint64 {
	return s.value.Uid
}

func (s *PlayerState) SetUid(value uint64) {
	if s.value.Uid == value {
		return
	}
	s.value.Uid = value
	if diff.MarkDirty(&s.dirty[playerStateDirtyUidWord], playerStateDirtyUidMask) && s.markParent != nil {
		s.markParent()
	}
}

func (s *PlayerState) GetLastOfflineTime() int64 {
	return s.value.LastOfflineTime
}

func (s *PlayerState) SetLastOfflineTime(value int64) {
	if s.value.LastOfflineTime == value {
		return
	}
	s.value.LastOfflineTime = value
	if diff.MarkDirty(&s.dirty[playerStateDirtyLastOfflineTimeWord], playerStateDirtyLastOfflineTimeMask) && s.markParent != nil {
		s.markParent()
	}
}

func (s *PlayerState) WriteDiff(writer *diff.Writer) {
	if diff.HasDirty(s.dirty[playerStateDirtyUidWord], playerStateDirtyUidMask) {
		writer.Uint64(1, s.value.Uid)
	}
	if diff.HasDirty(s.dirty[playerStateDirtyLastOfflineTimeWord], playerStateDirtyLastOfflineTimeMask) {
		writer.Int64(2, s.value.LastOfflineTime)
	}
}

func ApplyPlayerDiff(value *Player, data []byte) error {
	return applyPlayerDiff(value, data, nil)
}

func ApplyPlayerDiffWithHooks(value *Player, data []byte, hooks *PlayerApplyHooks) error {
	return applyPlayerDiff(value, data, hooks)
}

func applyPlayerDiff(value *Player, data []byte, hooks *PlayerApplyHooks) error {
	reader := diff.NewReader(data)
	for {
		fieldNumber, operation, payload, ok, err := reader.Next()
		if err != nil || !ok {
			return err
		}
		switch fieldNumber {
		case 1:
			if operation != diff.OperationSetVarint {
				return diff.ErrInvalidData
			}
			oldValue := value.Uid
			value.Uid = diff.DecodeUint64(payload)
			if hooks != nil && hooks.OnUidChanged != nil {
				hooks.OnUidChanged(oldValue, value.Uid)
			}
		case 2:
			if operation != diff.OperationSetVarint {
				return diff.ErrInvalidData
			}
			oldValue := value.LastOfflineTime
			value.LastOfflineTime = diff.DecodeInt64(payload)
			if hooks != nil && hooks.OnLastOfflineTimeChanged != nil {
				hooks.OnLastOfflineTimeChanged(oldValue, value.LastOfflineTime)
			}
		}
	}
}

func (s *PlayerState) ClearDirty() {
	diff.ClearDirty(s.dirty[:])
}
