// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.2
// source: shared/actor_type.proto

package pbShared

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActorType int32

const (
	ActorType_Unknown ActorType = 0
	ActorType_Player  ActorType = 1
)

// Enum value maps for ActorType.
var (
	ActorType_name = map[int32]string{
		0: "Unknown",
		1: "Player",
	}
	ActorType_value = map[string]int32{
		"Unknown": 0,
		"Player":  1,
	}
)

func (x ActorType) Enum() *ActorType {
	p := new(ActorType)
	*p = x
	return p
}

func (x ActorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActorType) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_actor_type_proto_enumTypes[0].Descriptor()
}

func (ActorType) Type() protoreflect.EnumType {
	return &file_shared_actor_type_proto_enumTypes[0]
}

func (x ActorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActorType.Descriptor instead.
func (ActorType) EnumDescriptor() ([]byte, []int) {
	return file_shared_actor_type_proto_rawDescGZIP(), []int{0}
}

var File_shared_actor_type_proto protoreflect.FileDescriptor

const file_shared_actor_type_proto_rawDesc = "" +
	"\n" +
	"\x17shared/actor_type.proto\x12\ftaoxi.shared*$\n" +
	"\tActorType\x12\v\n" +
	"\aUnknown\x10\x00\x12\n" +
	"\n" +
	"\x06Player\x10\x01B4Z2github.com/2comjie/taoxi-server/pb/shared;pbSharedb\x06proto3"

var (
	file_shared_actor_type_proto_rawDescOnce sync.Once
	file_shared_actor_type_proto_rawDescData []byte
)

func file_shared_actor_type_proto_rawDescGZIP() []byte {
	file_shared_actor_type_proto_rawDescOnce.Do(func() {
		file_shared_actor_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_actor_type_proto_rawDesc), len(file_shared_actor_type_proto_rawDesc)))
	})
	return file_shared_actor_type_proto_rawDescData
}

var file_shared_actor_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_shared_actor_type_proto_goTypes = []any{
	(ActorType)(0), // 0: taoxi.shared.ActorType
}
var file_shared_actor_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shared_actor_type_proto_init() }
func file_shared_actor_type_proto_init() {
	if File_shared_actor_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_actor_type_proto_rawDesc), len(file_shared_actor_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shared_actor_type_proto_goTypes,
		DependencyIndexes: file_shared_actor_type_proto_depIdxs,
		EnumInfos:         file_shared_actor_type_proto_enumTypes,
	}.Build()
	File_shared_actor_type_proto = out.File
	file_shared_actor_type_proto_goTypes = nil
	file_shared_actor_type_proto_depIdxs = nil
}
